### ISSUE TITLE
bootstrap.py fails on OSX MacPorts consistently

### ISSUE THREAD

**Issue by anjos** [buildout/buildout#128]
Following the distribute/setuptools merger, MacPorts has decided to disable the "distribute" port and update the "setuptools" port to 0.7.4, following what is on PyPI. Now, all of our `bootstrap.py`'s fail with the following error message:

``` sh
>> python bootstrap.py 
Traceback (most recent call last):
  File "bootstrap.py", line 108, in <module>
    pkg_resources.Requirement.parse('distribute')).location
AttributeError: 'NoneType' object has no attribute 'location'
```

Is there a solution for this problem that would not go through downgrading the whole software stack? I ask because there are piles of software that depend on "setuptools", so, downgrading that package will cause a major pain.

**Comment by uqueia** [comment]
When I installed 

'$ wget http://downloads.buildout.org/2/bootstrap.py
$ python bootstrap.py'

'python bootstrap.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.2.zip
Extracting in /var/folders/60/_jh623296gvf3r9vkrt6l5jh0000gn/T/tmpFRViiW
Now working in /var/folders/60/_jh623296gvf3r9vkrt6l5jh0000gn/T/tmpFRViiW/setuptools-18.2
Building a Setuptools egg in /var/folders/60/_jh623296gvf3r9vkrt6l5jh0000gn/T/bootstrap-bZkd7o
/var/folders/60/_jh623296gvf3r9vkrt6l5jh0000gn/T/bootstrap-bZkd7o/setuptools-18.2-py2.6.egg
While:
  Initializing.
Error: Couldn't open /Users/uqueia/buildout.cfg'

What do I do about the buildout.cfg error?

**Comment by mgedmin** [comment]
Please do not comment on unrelated old issues.  Come ask questions on IRC (irc.freenode.net, channel `#buildout`) and have patience (it may take hours for someone to respond, depending on timezones -- it's not a very active channel).

**Comment by reinout** [comment]
Create the `buildout.cfg` file? You cannot run buildout without a buildout config file.
