### ISSUE TITLE
Requirement error doesn't say where requirement comes from

### ISSUE THREAD

**Issue by djay** [buildout/buildout#160]
e.g. "The constraint, 2.4.5dev, is not consistent with the requirement, 'z3c.form>=3.0.0a1'".

The constraint is easy to find and debug. However the requirement could be anywhere in any setup.py in any of the dependencies. In a complex buildout this is hard to track down. Even with -vv this information is not available. It would be very helpful if buildout could give a more helpful error message that indicated both the source of the requirement (and constraint if possible).

**Comment by sunew** [comment]
This has always been the most time-consuming problem with buildout. A fix is so much needed. Check out modern tools like bower for inspiration.

**Comment by jimfulton** [comment]
Did you use verbose mode? -v

**Comment by jimfulton** [comment]
Oh, he did. Usually, -v provides the needed information.  There do seem to be some holes though.
-vv usually provides too much data.

**Comment by sunew** [comment]
I tried to fix this a while ago (printing what egg has the requirement), as far as I remember I ended up somewhere deep down in setuptools - it required some changes in the flow of information that I did not have enough knowledge to implement. Perhaps eggdeps can be helpful here?

**Comment by djay** [comment]
I find -v often does not provide enough information. What is needed is a
list of everything that required that package and if it was version pinned
or inside a setup.py or inside a recipe etc.

**Comment by reinout** [comment]
Big problem is that some of the I-need-a-package code is inside setuptools. Monkey-patching that is hard/impossible/unrealistic/nightmare.

Note that recent setuptools versions seem to be more diligent in reporting version conflicts/requirements.

Second note: I think there's a difference between installing regular egg dependencies and installing recipes (which might have their own dependencies). Regular dependencies seem to report dependency problems pretty well nowadays. I have the feeling that the problems start when a recipe depends on things. (Not sure actually, I'm trying to re-play previous deep debugging sessions in my head right now).

**Comment by reinout** [comment]
I've got a PR #282 that ought to help a **lot**. See the example I pasted at the top of the PR text, that's the output I'm getting now. It helped me figure out which dependency was causing the problem.

**Comment by djay** [comment]
Nice

**Comment by reinout** [comment]
Can you check out version 2.5.0? That ought to have fixed it mostly.
