### ISSUE TITLE
Shouldn't the cache-directory be created if missing

### ISSUE THREAD

**Issue by lelit** [buildout/buildout#171]
Currently the download-cache directory must be already present, if it is specified in the [buildout] section, otherwise buildout immediately exits with the following error:

```
bin/buildout 
While:
  Initializing.
Error: The specified download cache:
'/tmp/dc-test/download-cache'
Doesn't exist.
```

Shouldn't it create the directory instead? When it is set, buildout automatically creates the `dist` subdirectory under that if it is missing, but not the parent...

My current use-case is that I'm trying to make the installation of a product as simple as possible using buildout: given that the product setup may require the download of a third-party component (done by a custom recipe), I'd like to cache that to avoid repeated download (when the product is updated). I thought that buildout own download-cache setting was appropriate for this, but it suffer of the above problem.

Of course my custom recipe is able to create the directory by itself, but it seemed sensible to reuse the global setting...

I'm willing to code the fix with the needed tests, if you think this is reasonable.

**Comment by WouterVH** [comment]
what is blocking this issue ?

**Comment by lelit** [comment]
Good question indeed!

**Comment by reinout** [comment]
The tilde-expansion is what I wanted.

Blocking? It needed someone trying to get through as many as possible of the 20+ pull requests. I think I've merged 8 or so in the last couple of weeks. 

Now we need to wait for a new release (#249). I cannot release buildout, so I'll drop an email into the mailinglist to ask for someone else to pick it up.

I'm closing this issue, but feel very, very free to add "yeah, release me" messages to #249 .
