### ISSUE TITLE
Problem with latest buildout bootstrap on Windows with Python 3.3

### ISSUE THREAD

**Issue by lelit** [buildout/buildout#186]
Executing the latest bootstrap script under Windows with Python 3.3 I obtain an
ImportError on the standard `getopt` module.

Digging a bit, I see that ``site.getsitepackages()`` returns a list
composed by two elements, ``c:\\Python33`` and
``c:\\Python33\\lib\\site-packages``: effectively even the 3.4 code at
http://hg.python.org/cpython/file/bc160f985b7b/Lib/site.py#l312
explicitly puts the plain "prefix" into the list.

Then the buildout bootstrap script does something like::
```
  for sitepackage_path in site.getsitepackages():
      sys.path[:] = [x for x in sys.path if sitepackage_path not in x]
```

and obviously after that `sys.path` does *not* contain any standard
library path (which lives under "c:\\Python33\\Lib"), just the current
working directory and `c:\\Windows\\system32\\python33.zip`.

The code in the bootstrap script seems correct (even if it should
probably use something like ``not x.startswith(sitepackage_path)``),
what seems strange is that, under Windows, the ``getsitepackages()``
result contains a bare ``c:\\Python33``... for comparison, on my Debian
sid I get::
```
  Python 3.3.5 (default, Mar 22 2014, 13:24:53) 
  [GCC 4.8.2] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import site
  >>> site.getsitepackages()
  ['/usr/local/lib/python3.3/dist-packages',
   '/usr/lib/python3/dist-packages', '/usr/lib/python3.3/dist-packages',
   '/usr/lib/dist-python']
  >>> 
```

The following patch seems to cure the problem, but I'm not sure it's the right approach:
```
diff --git a/bootstrap.py b/bootstrap.py
index ed57894..95714ad 100644
--- a/bootstrap.py
+++ b/bootstrap.py
@@ -85,8 +85,8 @@ if not options.allow_site_packages:
     # inside a virtualenv, there is no 'getsitepackages'. 
     # We can't remove these reliably
     if hasattr(site, 'getsitepackages'):
-        for sitepackage_path in site.getsitepackages():
-            sys.path[:] = [x for x in sys.path if sitepackage_path not in x]
+        sitepkgs = set(site.getsitepackages())
+        sys.path[:] = [x for x in sys.path if x not in sitepkgs]
 
 setup_args = dict(to_dir=tmpeggs, download_delay=0)
 ez['use_setuptools'](**setup_args)
```

**Comment by reinout** [comment]
The suggested fix is now in the latest bootstrap.py (https://bootstrap.pypa.io/bootstrap-buildout.py). Can you see if it indeed fixes the issue? And re-open if not?

**Comment by lelit** [comment]
I'm sorry, but I won't be able to test buildout on windows system any time soon, since I'm focused on completely different things these days. Thank you for taking care of the problem, though!
