### ISSUE TITLE
up/downgrade fails with extension (mr.developer)

### ISSUE THREAD

**Issue by agroszer** [buildout/buildout#198]
Having the following buildout.cfg:

```
[buildout]
extensions = mr.developer
sources-dir = dep
auto-checkout = *
parts = scripts
develop = .
versions = versions

[versions]
zc.buildout = 2.2.0

#  jedi and epc are eggs needed for jedi.  Folded into the scripts
#  part in order to reduce the number of parts that take time.
[scripts]
recipe = zc.recipe.egg
eggs = jedi
       epc
       RBTools

interpreter = python

```

results in:
```
bin/buildout
While:
  Installing.
  Loading extensions.
Error: There is a version conflict.
We already have: zc.buildout 2.2.3
```

The current zc.buildout version is 2.2.3, that gets downloaded by bootstrap.py
The problem can be fixed by either ```python bootstrap.py --version=2.2.0``` or nailing zc.buildout = 2.2.3

**Comment by reinout** [comment]
See pull request #248. Buildout already has code to remove develop eggs that it knows about. The problem is the ones it doesn't know about. So in #248, I'm simply removing the develop-eggs directory in buildout's own `bootstrap()` phase.

**Comment by reinout** [comment]
#248 is part of the new 2.4.0 buildout release, so I think this issue can be closed now. Feel free to re-open when there's still an error.

Note that you'd better also grab the latest bootstrap.py, as that also has a fix dealing with global paths.
