### ISSUE TITLE
Make downloads.buildout.org available over HTTPS

### ISSUE THREAD

**Issue by mgedmin** [buildout/buildout#205]
The documentation directs users to download the bootstrap script from http://download.buildout.org.  This leaves buildout's users open to man-in-the-middle attacks.

Currently https://downloads.buildout.org fails because it serves an SSL certificate for `*.hostmonster.com`.  This would need to be fixed first.

**Comment by k4ml** [comment]
This page - http://www.buildout.org/en/latest/install.html is pointing to bootstrap.pypa.io website:-
```
$ cd newproject
$ wget -O bootstrap.py https://bootstrap.pypa.io/bootstrap-buildout.py
```
So I think this issue is solved now.

**Comment by reinout** [comment]
Right now, http://downloads.buildout.org/2/bootstrap.py even redirects to the https bootstrap.pypa.io site, so I'm closing this.
