### ISSUE TITLE
Travis CI does not test pull requests

### ISSUE THREAD

**Issue by mgedmin** [buildout/buildout#206]
If you submit a pull request for buildout, you'll notice that GitHub doesn't show a Travis build status for it.

You'll also notice that https://travis-ci.org/buildout/buildout/pull_requests is empty.

This reminds me of https://github.com/zopefoundation/zope.githubsupport/issues/1.  Assuming the cause of the problem is the same, the easiest way to fix this would be to go into the settings and disable then re-enable Travis CI integration.

I cannot do this because I don't have administrative access to the buildout repository.

**Comment by mgedmin** [comment]
> \<J1m> I'm looking at the settings for buildout in travis and it says build pull requests is on.
> \<mgedmin> can you turn it off and then back on?
> \<J1m> sure
> \<J1m> done

Let's hope that fixes it.

**Comment by mgedmin** [comment]
> Let's hope that fixes it.

Nope :(.  I just created https://github.com/buildout/buildout/pull/231 and https://travis-ci.org/buildout/buildout/pull_requests remains empty.

**Comment by reinout** [comment]
Switching "enable PR builds" off and back on again didn't solve it. If I read @mgedmin's linked issues correctly, the whole travis integration would have to be switched off and back on again on the *github* side of things. That might reset the wrong setting, but I'm afraid it also resets the cache and other things.

Anyway, I've created a travis issue: https://github.com/travis-ci/travis-ci/issues/4739. I hope they either fix the button and/or enable PR builds by hand for our repo.

Doing clicky-clicky in the github settings is something we can try later on.

**Comment by reinout** [comment]
Hurray, fixed by travis in https://github.com/travis-ci/travis-ci/issues/4739#issuecomment-137046189

<img width="867" alt="screen shot 2015-09-02 at 14 32 26" src="https://cloud.githubusercontent.com/assets/121433/9631211/a7b031dc-517f-11e5-9e0c-a47e156a95b4.png">

**Comment by mgedmin** [comment]
\o/
