### ISSUE TITLE
bootstrap.py does not work if buildout.org is down

### ISSUE THREAD

**Issue by mfelsche** [buildout/buildout#21]
At this moment (Mi 26. Sep 10:23:28 CEST 2012) buildout.org is down.
Wanted to setup a buildout, "python bootstrap.py" refuses to work with:

Download error on http://buildout.org: [Errno -2] Name or service not known -- Some packages may not be found!

tried different -v options, -t etc. nothing works.
Why does it want to resolve buildout.org when all zc.buildout-packages reside on pypi.python.org ?

Seems that on http://pypi.python.org/simple/zc.buildout/ some "home_page" links point to buildout.org. dunno what exactly happens. Any idea?

**Comment by reinout** [comment]
With the changes in pypi/pypa infrastructure and also buildout's own bootstrap script, I think this can be closed now.
