### ISSUE TITLE
bootstrap.py without --allow-site-packages fails with ImportError on Windows

### ISSUE THREAD

**Issue by fpatz** [buildout/buildout#217]
On Windows, bootstrap.py does not work without --allow-site-packages. Bootstrapping fails with an ImportError, not finding "email" from the standard library (see traceback below). The reason is the code for allow_site_packages=False: it removes everything from sys.path that contains anything from site.getsitepackages(). But on Windows, for whatever reason, site.getsitepackages() contains the base installation path C:\Python27 (this is sys.prefix, as added by site.py for the Windows case). Thus the code path for allow_site_packages=False removes *everything* from sys.path.

I think this was introduced with buildout/buildout@682dd5a690ca9c39ba7c98d3aca35028ac04cd41; the failure is also visible on winbot.zope.org.

> c:\Python27\python bootstrap.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-8.0.1.zip 
[...]
Traceback (most recent call last):
  File "bootstrap.py", line 92, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 140, in use_setuptools
  File "<string>", line 128, in _do_download
  File "build\bdist.win32\egg\setuptools\__init__.py", line 5, in <module>
  File "c:\Python27\lib\distutils\core.py", line 19, in <module>
    from distutils.dist import Distribution
  File "c:\Python27\lib\distutils\dist.py", line 10, in <module>
    from email import message_from_file
ImportError: No module named email

**Comment by mgedmin** [comment]
@jimfulton you asked for a nag ;)

This issue is causing ZODB tests to [fail on winbot](http://winbot.zope.org/builders/ZODB_dev%20py_270_win32/builds/1624/steps/bootstrap/logs/stdio) and is the only remaining unresolved issue on the daily zope-dev test failure report.

The fix in #218 seems pretty straightforward.

**Comment by lelit** [comment]
Maybe a second nag is needed... FWIW, I confirm that #218 fixed the problem for me too.

**Comment by mgedmin** [comment]
#218 was merged, now we wait for somebody who can to update the copy at https://bootstrap.pypa.io/

**Comment by mgedmin** [comment]
FWIW the new bootstrap [fixed](http://winbot.zope.org/builders/ZODB_dev%20py_270_win32/builds/1716) ZODB tests on winbot.

**Comment by agroszer** [comment]
winbot fixed: yeah!

**Comment by tseaver** [comment]
We need a release *here* which fixes the issue.

**Comment by reinout** [comment]
@tseaver: what do you mean with "a release *here*"? You mean that the current `bootstrap.py` needs to be copied to the main location(s), right?

**Comment by tseaver** [comment]
I meant that @mgedmin's https://github.com/mgedmin/scripts/commit/ffde9f651540dd8904b214cd85df3f248d3ef0a0 commit referenced this issue as "fixes buildout/buildout#217" but the fix is not part of the buildout tree -- it is a local workaround.

**Comment by reinout** [comment]
Ah, I get it.

a) That's a very useful-looking script @mgedmin has made! I might copy/paste that locally :-)

b) There is a fix in the buildout tree, #218. There's another bootstrap.py fix, #222, so bootstrap needs releasing.

c) Ticket can be closed after bootstrap release.

**Comment by reinout** [comment]
The newest bootstrap is out! Grab it from https://bootstrap.pypa.io/bootstrap-buildout.py

(To test if you've got the latest, run `python bootstrap.py --version`)
