### ISSUE TITLE
dev.py fails with recent setuptools.

### ISSUE THREAD

**Issue by mgedmin** [buildout/buildout#227]
Someone complained on IRC that buildout's tests are failing.  You can see the same failure on Travis: https://travis-ci.org/buildout/buildout/jobs/46070031#L97

The commit that triggered that build appears to be unrelated to the failure.

Last successful build on Travis was 22 [days ago](https://travis-ci.org/buildout/buildout/jobs/44200651#L97) and used setuptools 8.0.4.  The failing build uses setuptools 11.3.

I'm pretty sure the following setuptools change broke buildout's dev.py: [Moved pkg_resources into its own package](https://bitbucket.org/pypa/setuptools/commits/02658cf09ced08b8ff4a81e24c614eee3d219c70).

Bitbucket makes it hard to see which releases contain that commit.  GitHub makes it [easy](https://github.com/jaraco/setuptools/commit/79a0c55d8c09d3fdd68157faa8658ecd85aa5d45): every release since setuptools 8.3.

**Comment by jimfulton** [comment]
Sigh. Thanks.
