### ISSUE TITLE
2.3.1 release on pypi but not on github?

### ISSUE THREAD

**Issue by daybarr** [buildout/buildout#243]
zc.buildout 2.3.1 is available for download from PyPI (https://pypi.python.org/pypi/zc.buildout/2.3.1) since upload on 2014-12-16. The [change history for 2.3.1 on PyPI](https://pypi.python.org/pypi/zc.buildout/2.3.1#id3) says:

> * Fixed: Buildout merged single-version requirements with version-range requirements in a way that caused it to think there wasn’t a single-version requirement. IOW, buildout throught that versions were being picked when they weren’t.
> * Suppress spurios (and possibly non-spurious) version-parsing warnings.

The git repo [here](https://github.com/buildout/buildout) has no tag for the 2.3.1 release. It does not show a 2.3.1 release in [current master CHANGES.rst](https://github.com/buildout/buildout/blob/37adf716f55472ada5f18aa3ced71ee9ddee627f/CHANGES.rst), but the change history entry for unreleased code is identical to that given on pypi although missing the second bullet point.

Does someone need to push recent changes to github?

Thanks

**Comment by tseaver** [comment]
@jimfulton you pushed the commits whose comments match the PyPI changelog entries for 2.3.1.  Do you just need to `git push --tags`?

**Comment by daybarr** [comment]
I can see 86d0cdbb0c4a3d9e3b2576f61fd54d196b5635b9 has now been pushed to update the changelog, and the 2.3.1 tag is here (1e9cc1ebc86f375cddd8d0facd39b621e112586c). Thanks.
