### ISSUE TITLE
Nicer error message instead of "MissingSectionHeaderError" for corrupted or gzipped *.cfg files

### ISSUE THREAD

**Issue by idgserpro** [buildout/buildout#245]
When trying to do a ```python bootstrap.py```, using the last one from this repository, we got:

```
$ python bootstrap.py 
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-17.1.1.zip
Extracting in /tmp/tmpFAyq3_
Now working in /tmp/tmpFAyq3_/setuptools-17.1.1
Building a Setuptools egg in /tmp/tmpY6I5EU
/tmp/tmpY6I5EU/setuptools-17.1.1-py2.7.egg
> bootstrap.py(194)<module>()
-> zc.buildout.buildout.main(args)
(Pdb) c
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1945, in main
    user_defaults, command, args)
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 225, in __init__
    data['buildout'].copy(), override, set()))
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1582, in _open
    downloaded)
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1582, in _open
    downloaded)
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1582, in _open
    downloaded)
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1562, in _open
    result = zc.buildout.configparser.parse(fp, filename, _default_globals)
  File "/tmp/tmpY6I5EU/zc.buildout-2.3.1-py2.7.egg/zc/buildout/configparser.py", line 207, in parse
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: http://dist.plone.org/release/4.3-latest/versions.cfg, line: 1
'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\x8cS\xc1n\xdb0\x0c\xbd\xeb+\x08\xe4:\xb3\x96\xedf\xe9\x80\x0c[;l\xa7b\xc3\x9a\xd3\x8a\x1e\x14\x89I\x84\xc8\x92F\xc9Y\xbb\xaf\x1fd\']\xbb\xf60\xdfL?>>>>\xdf\xae\x07\xebL\x18\xf2\x9d\xa0\xfbL\xde$X\xc2.\xe7\xf8\xee\xec\xcc\xd8\x941\xba\xe0\t\x03o\xcf\x0e\xc4\xc9\x06\x9f\xce~\x87H9\x04\xb7\xb7\xb9\x92U]-\xaaRQ1V\'\x08\xea\xcdV\xc0\xe3\xf3\x1f|US\xc9\xb6j\x9a\xe7\x14\xe2\xf6\xf4z\'f\xf0#D\x82p fk(\t\x13\xf4\x90\xad+\x82k\xbc@)f\xf0\x852\xa4!\xc6\xc0\x196\x81\xe1C"=\xb0\xcd\x0f`H\x07V9p\x12\x1f\xb5\xa6\x94\xae\x82\xcf\x1c\x1c,\xa1\xc5\x1a\x17b\x06\xd7\x81\tz\xea\x03?\x00m6V[\xf2\x19\x8e\x02\xde\xc0\x8a\x95\x86\x99le-\xc5\'\x95ie{:v\xb7b\x06\xdf8\x98A\xe7\x84\x97+&\xfa\x1c\x9c!n\xa0A\xd9b\x07Z\r\x89\x12(`\xda2\xa5B(^oXN-\x85\xf1\xebqS\x18|\xb6\x0e\x8aK`\x13\x0c\xd1\xa8L\xe6o\xffMV\xde(6WJ\xef\xe8Zy\xb5%.\xa6\x8cD\xc5\x95\x7f\x89\xf2\xfe)\xcfM\xdcY\x7f\x0fK\x90(\xc7\xb9L?\x07\xcbdF\x07\x99tq\xe1w\xabq\x13\xb8\x07\xe5\r\xe8\x9d\xea\xc9Q\xf0\xa2h\xc2\xa8\xb6\x94\xa9\x8fN\xe5\xc9\x909\xb6B\x88\x19\\\x96hAIJ\x12\xa7\x98\xa1\x19\xfa\x18\xad\xde\x939\x9dv\xbc\xdf\xb9\xd0\xc19\xd2\xd9\x1e\x08\x99\xb4\x8d\x84\xa1L\xc9#i\x8d\xf25\xc4\x93\xb1\x12/\x9e\x02\xee{\x97)e\xa61\x0b\xe5s\xf1\xe21\x05\xa3\xce\x0ekQ2\xc9v=\x1c\xa7\xcc\xb1Y\x88\x9e\xd1\xd0\x81\\\x88T\x80\x12\x1b)\xa6\xd8\x1e\xc7*7\x92\x17\xe5\x12\xbb\xe7\xdf\x8a%\x8d\xf5)+\xaf\x0bg\x87M\xd1\xfe\x1cC!\x11\x1fN\xec8\x17\x89\xf2\x10G\xa7&\x19ZJQ<\xd7%\xeej;-\xd8`=\x16c\xd6\xa1\x8fjZ\xab\xc6\t\xf9\xcc\x8a\xae\x14)edr\xa4\xd28\xa8\xc5\xae\x9d\x0e6\x1a3x?\x96;\x94(\xcb\xb5\xbe\x87u\xc8\xb0\xa2\x94\xad\xdf\x1e\xf5\xaa\x18\x91K}\xc3\xaa\xa7_\x81\xf7\xb0\x84\xf7\xe5o\xeb\xc4\x8bz\x83\x8b\x17\xe5*\x91#o\x87\xbeqv\xcd\x8a\x1fFy\xe7XO\xb84\xd8\xa3\xe29\xd6\xe2\x84\x1d\xb9\xba\x16k\xd1\x07]\x98\xa7-#\xc5\xc5\xb1\xfd\xad\xb8Tkr\x7f\x00\x00\x00\xff\xff\x84\x97\xdfs\xe26\x10\xc7\xdf\xfdW0\xd3g<\x06\x12\xc8=\xa6\\\xd2\xd2\tS.p\x97\x99\xbe\xc9\xd2b\xeb\x90%W\x92CH\xa7\xff{g%\x83%\x1b\xa6zK\xf2\xc9z\xb5\xfb\xdd\x1f\xf2y\xbd\xf9IC5\x804\xa5r\x99\xca\\\xbe\x8dS;\xc5\xe2\xe7\xf9xp\x07\x84\x06\x06\x19\xe4M\xd1\xf9\x8f\xf5\xee\xcd\x8c\xb5ec[\x82k\x04Y:I\xef\x93\xcd\xa9\xa8@\xb6\xd2\x98c\\\x9f>,hI\xc4\x88A\r\x92\x81\xa4\x1cL\xb2&\xfa\xc0\xd4Q\xba\xbb\xa2\xc5\xcd\xea\xa5\xad\xc1E\xb2\xe1B\xa8\xa3\xfb\x13F\xe1\x97\xd1w\xc9Q\xba\x0cFY\x9a\xdd\xa5\xffL\xc7_\xfe\x1d\xe5\x1a\xc8a\xe4\x84\x98t\x00:\x92a\xfeA\x00zb5\x9c\xd5\xb3\x18O\xb3l\x91=L\x17\xe3Z\xc3;\x87c\x02\x1f5h\x8e\x1c\x11)5\x06cGQX\xe8\xd2\x1f\\\xfe$\xbe%-\xd2Y\xb2\x07`5\xd1^M\xf7.%\xe2\xa3\xc2$\xa0\x9b\xf3\xa4"\\pY\x08U\x14\xad\xe0\x16i\x96(\xcd@\x03c\xdc\x99E\xad\xd5\'[*9\xc6\xee\x83\xfd\xdb\xa7\xf4\xfc[U\x83\xe4\xcc\xd9\x9c\xa6\xf7\t\xd6\xef\xa7\xabfn\x9dQ\xec\x14\x86W\xb5\x80\x9fF\xf9\xe8\xdd\xa7\xd3\xc4p\xdf\xc1\xb0D\xde \xff3oU\xf3\xe0\x1a\xd1\x06\xc5<jk!\xf1?\xfd\xdf\xc1\xca\x98\xa5w]\x9b}\xdc\xe1\xc8\x00iw\xa7\x1a\xcc\x80\x9eb\x1dE\xf8+\xecA\x83\xa4\xf0\xabVG\x03\xfa\x8d\xb3\x02l\x8bc^;V\xd3\x12\xec\x15\xb3\x9e\x9d\xa4_\xd2\x87\x8e^\xae\x9f\x1f\xa9\xe5J\xae(v\xcf>\x8d\x8e\xcc"zI\x04\xe0\x84\xe8\xa1-=\xed\xd38\x06\xaf\x1eO\xc7\x9e|\x85=i\x84\xbf\xd55:\x88\x08\xd2|\xbf\xdf)%\xfal\xebw\xcc\x9e$\xa98\xfd\xc1\xe1\xf8\xbc[\xc5\xec]\x8a:\x08\xe9\'\xc61$\xfdp\\\xfc\x98\xc4\xc6\x9f\x95\xae\xda\r@@\x14\x98\xf3D\x0f\xe9\x8d \x14\xf6\x8dxS\xfa\xb0\xc7\xca\x0chlG\x93 \x97\x0e\xbf%\xb0VT\xbd\x9b~k8=\xacpd\xa03a|\xbc3\x8b\x88\xc6\x0e\xbd$\xe6\xca\x07\xda=h\x1a\xe3\xaa\xe6\xb4O\xba\xd3\x06&\xa2\xbfs\xd6\xc7\xda3\xa0\xb1\x87\x82\xb4\x15/4\xc1\xd0\x0fh\x9c\xc8\x17\xfa\xebr\x18\xbc\x88\x8e\xa4\x82=S2`\x1bb\xcb\x95d\xf0\x11\xd38\xca#\x16\xfb+*@\xf55\xee;j\x90\x9e\xdf@\x82\xe6t\x8b\xf3\xb6\xc7zz\x11\n'
```

It was hard to track this bug because we're using ```~/.buildout``` (and so ```~/.buildout/extends```, where the cfgs are downloaded and cached), and, somehow, an instance downloaded a gzipped versions.cfg when using the ```bin/buildout -n```, and all other instances that uses the .buildout folder and weren't using -n (thus using the wrong cached version)  were having this error. The only similar result to this problem is in the [Plone mailing list](http://plone.293351.n2.nabble.com/Error-getting-4-3-1-versions-cfg-with-buildout-td7566149.html), but it doesn't give a solution.

The solution to the problem is to either remove ```~/.buildout/extends``` or to run any buildout in the machine with the ```-n``` - this forces to re-download all cached cfgs (stored using as an unique identifier it's own name in md5sum).

The problem happened as well even when not using the ```~/.buildout```: a gzipped file was downloaded and to avoid the problem you need to manually download the *.cfg files and concatenate one by one (single you can have multiple extends) in a single file by hand, or by adding a parameter to your url in extends like this

```
http://dist.plone.org/release/4.3-latest/versions.cfg?v=100
```

We know this is not a buildout issue *per se* (and maybe just a corporate network proxy/cache error or even a server sending the gzip), but we're just thinking if a better message could be shown.

We suggest catching the exception above and show a better error message, like "Some of your cfg's downloaded files in your cache may be corrupted in a gzip form. Try deleting your ~/.buildout/extends if applicable of running bin/buildout -n to redownload them.", or similar. What do you think?

**Comment by idgserpro** [comment]
This problem still occurs. The [_open](https://github.com/buildout/buildout/blob/master/src/zc/buildout/buildout.py#L1560) method could verify if downloaded file is a zip file and extract the contents before proceeding.

@reinout you can help here?

**Comment by reinout** [comment]
Automatically gunzipping if there's some mis-configuration in some custom server or corporate proxy? That is out of scope for buildout, I would say.

I *have* however a pull request #258 which also reports the cached file's location. Like this:

    MissingSectionHeaderError: File contains no section headers.
    file: http://localhost/faulty.cfg (cached at /var/folders/dl/wpghhqhj2bs9bcnn213f1nqw0000gn/T/buildout-TJQNE8), line: 1
    'This is definitively not\n'

Look at the **cached at ...** part. Would that solve most of your issue?

**Comment by idgserpro** [comment]
@reinout this makes it easy to find the problem. Thank you!


However, if the problem occurs, either problem on the web server, either by my proxy, buildout will not work. Solve of gzip file  problem may be out of reach. To work, you have to download the file and use it locally. This is bad because the file may change in the server and its buildout can be versioned.

The gedit for example reads this zip file without user action.

**Comment by reinout** [comment]
Well, you *could* unzip the file yourself and copy it to the cached filename you saw in the error message. The next time buildout will use your nicely unzipped version :-)

**Comment by idgserpro** [comment]
Each time the buildout is executed, the file name is changed.

**Comment by reinout** [comment]
Oh? How can that be? I mean, if it is supposed to work as a cache, the filename needs to be predictable. 

I just checked: buildout makes an md5 hash of the encoded url and uses that as the cached file's name. 

So if you have a different name every time: how can that happen? Is there a random component in there somehow?

**Comment by idgserpro** [comment]
When not use ```extends-cache``` in ```.buildout/default.cfg```, it downloads the files in / tmp each time with a different name.

**Comment by idgserpro** [comment]
I think that's here:

https://github.com/buildout/buildout/blob/master/src/zc/buildout/download.py#L193

**Comment by reinout** [comment]
Can you try out buildout version 2.4.2? I just released it.

I've changed the wording of the error message a bit so that it also fits tempfiles.

You're right that a tempfile gets a fresh name every time. Originally you said you were using the extends cache, however. Perhaps you could switch that on again, now that there's a proper error message that indicates the problematic filename?

**Comment by idgserpro** [comment]
@reinout  I tested the version 2.4.2  and now when I don't use the ```extends-cache``` and the error occurs, the file path is shown. Thank you!

To work around the problem, I tried use his suggestion to use ```extends-cache``` and edit the problem file. However, this has not worked. It downloaded the file again and replaced the file to with the problem file. It maybe compare the MD5 or size, and how different, download the file again. Any suggestion?

**Comment by reinout** [comment]
An md5 can only be compared if there's an md5 hash in the url. Normally that's done with a query parameter or a `#`. (`http://someserver.org/myfile.cfg?md5=324234234234234`) If so, you might try removing the hash.

What's the URL that gives you problems?

**Comment by idgserpro** [comment]
The url that was giving problem is:

http://dist.plone.org/release/4.3-latest/versions.cfg

However it is working now. To test, I took the file with problem and put in a local server.

**Comment by idgserpro** [comment]
We just had the same problem this morning but now with a different url.

```
python bootstrap-buildout.py               
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-21.2.2.zip
Extracting in /tmp/tmpJ1sI_Z
Now working in /tmp/tmpJ1sI_Z/setuptools-21.2.2
Building a Setuptools egg in /tmp/bootstrap-V5SkJr
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-V5SkJr/setuptools-21.2.2-py2.7.egg
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1991, in main
    user_defaults, command, args)
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 231, in __init__
    data['buildout'].copy(), override, set()))
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1626, in _open
    downloaded)
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1629, in _open
    downloaded))
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1626, in _open
    downloaded)
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1605, in _open
    fp, filename_for_logging, _default_globals)
  File "/tmp/bootstrap-V5SkJr/zc.buildout-2.5.1-py2.7.egg/zc/buildout/configparser.py", line 207, in parse
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg (downloaded as /tmp/buildout-ByazVA), line: 1
'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\\T=\xaf\xdb0\x0c\xdc\xf3+\x0c\xbc\xb9r\xfc\xf2\xd9\x02\xd9\xbau\xed\xd4\xa2\x83,\xd3\x8e\x10I\x14(:\x89\xdf\xaf/\xecPN\x9c-\xbe#\x8f\xe4\x91\xcaG\xf1\x13o\xc1\xa1n\xa0)ZB_\x9c\x99\xe3\x8f\xb2l\x04V_\x18A!u\xe5\xf8\x83\x11\xdd\xc5riC\x03\xf7\xb2Rku,\xbf\xf8\xf2\xed\n'
```

Somehow this file just begun coming as gzip, and we don't know if that's from plone itself or an internal proxy/cache.

We did a strange *workaround* that seems to work, but we still don't know the full explanation for it. Basically, we copied this snippet of code, https://github.com/buildout/buildout/blob/de219ed3f63c055105ac91fa1ea33d079fb410f4/src/zc/buildout/download.py#L33 (mainly the `urlretrieve` function) to a `test_urlretrieve.py file`, and, after the line https://github.com/buildout/buildout/blob/de219ed3f63c055105ac91fa1ea33d079fb410f4/src/zc/buildout/download.py#L51, we added

```python
req.add_header('Pragma', 'no-cache')
```

And at the end of `test_urlretrieve.py file`:

```python
urlretrieve('http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg', '/tmp/zopetoolkit-1-0-8-ztk-versions.cfg')
```

In the end, we have as `test_urlretrieve.py`:

```python

import base64
from urlparse import urlparse
from urlparse import urlunparse
import urllib2

def urlretrieve(url, tmp_path):
    """Work around Python issue 24599 includig basic auth support
    """
    scheme, netloc, path, params, query, frag = urlparse(url)
    auth, host = urllib2.splituser(netloc)
    if auth:
        url = urlunparse((scheme, host, path, params, query, frag))
        req = urllib2.Request(url)
        base64string = base64.encodestring(auth)[:-1]
        basic = "Basic " + base64string
        req.add_header("Authorization", basic)
    else:
        req = urllib2.Request(url)
        req.add_header('Pragma', 'no-cache')
    url_obj = urllib2.urlopen(req)
    with open(tmp_path, 'wb') as fp:
        fp.write(url_obj.read())
    return tmp_path, url_obj.info()

urlretrieve('http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg', '/tmp/zopetoolkit-1-0-8-ztk-versions.cfg')
```

After calling `python test_urlretrieve.py` now the file isn't downloaded as gzip (it seems the cache at the server for all requests from now on is cleared) when running buildout or bootstrap.py in all of the machines that were having problems in our infra structure.
