### ISSUE TITLE
2.4.0 buildout release needed + 2.0.2 zc.recipe.egg release

### ISSUE THREAD

**Issue by reinout** [buildout/buildout#249]
I think a 2.4.0 release would be a good idea. Most fixes are already merged into master and only await a release.

There are two additional pull releases that I think are good to go.

- #247 can be merged, it doesn't impact the actual code.

- #248 needs a review, but it would seriously improve buildout reliability in my office :-)

#248 (and one or two other already-merged pull requests) need a new bootstrap release.

Similarly, #229 needs a **zc.recipe.egg** release (and first a quick changelog entry copy/paste).

The other pull requests need more work/documentation/tests/design desicions. At least, that's my impression of going through the list a few times in the last couple of days.

**Comment by idgserpro** [comment]
Have you decided if https://github.com/buildout/buildout/pull/204 will be incorporated in this new release?

**Comment by reinout** [comment]
Well, I'm not the main decision maker here :-) I've reviewed a couple of other people's pull requests and merged them and I'm waiting for someone else to say something about the two I made.

Regarding #204: some version marker or date in the bootstrap is handy, I'm just not sure yet what to do there exactly.

**Comment by reinout** [comment]
Note: @idgserpro points at unicode problems that could do with a fix in a new release. #98, #148 and #152 .

**Comment by reinout** [comment]
@idgserpro, I've closed #204 as I've got a better (imho) fix in #248

**Comment by reinout** [comment]
I just merged #229 into master. Again: this needs a zc.recipe.egg release.

**Comment by reinout** [comment]
Ok, I've done some additional merging and shepherding. At the moment, only pull requests #248 and #250 need attention. 

#248: bootstrap version, some bootstrap fixes and the deletion of `develop_eggs/*` when buildout is bootstrapped. That last fix might be the difference between my company **dropping** buildout and **keeping** buildout. So I really really really want that one in.

#250: one of the main reasons for the new release. It seems good to merge.

There are some issues fixed in this release that seem worthy of a reasonably speedy release.

**Comment by reinout** [comment]
I've merged #250 as it seems save to do so. There's a report that it works.

So only #248 it left. Plus a release. I'm sending a mail to the mailinglist.

**Comment by reinout** [comment]
I just released zc.recipe.egg 2.0.2: https://pypi.python.org/pypi/zc.recipe.egg/2.0.2

Waiting for a final comment on #252 before releasing zc.buildout.

**Comment by reinout** [comment]
And... buildout has been released: https://pypi.python.org/pypi/zc.buildout/2.4.0

And the latest bootstrap.py is also online.

**Comment by idgserpro** [comment]
Downloaded new bootstrap-buildout.py file and used 2.4.0 release, to test https://github.com/buildout/buildout/issues/98 again. It works.

**Comment by aclark4life** [comment]
Thanks @reinout !
