### ISSUE TITLE
On windows, the initial hashbang line includes quotes around "python". Is that right?

### ISSUE THREAD

**Issue by reinout** [buildout/buildout#256]
I've tried fixing the winbot tests. There is one thing I'm not sure about whether it is something I need to compensate for or whether it is something that's wrong.

See http://winbot.zope.org/builders/zc_buildout_dev%20py_270_win32%20master/builds/1079/steps/test/logs/stdio

`src\zc\buildout\tests.py`, around line 2791. The test prints a bin script there. The hashbang line on windows looks like `#!"python"`, so with double quotes around the word `python`. The test code expects `python` without the double quotes.

Those double quotes, are they right? If so, I need to adjust the test.

**Comment by agroszer** [comment]
that's for spaces in filenames as I remember, see PR 270

**Comment by reinout** [comment]
Thanks for fixing it in #270!
