### ISSUE TITLE
Download config is broken with https://user:password@host:port/myconfig.cfg

### ISSUE THREAD

**Issue by projekt01** [buildout/buildout#257]
The latest changes in version 2.4.1 will break downloading a config file from a private pypi server.
```
bin/buildout -c https://user:password@pypi.myhost.com/myconfig.cfg
```
will end in:
```
  An internal error occurred due to a bug in either zc.buildout or in a recipe being used:
  Traceback (most recent call last):
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/buildout.py", line 1986, in main
      user_defaults, command, args)
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/buildout.py", line 231, in __init__
      data['buildout'].copy(), override, set()))
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/buildout.py", line 1574, in _open
      path, is_temp = download(filename)
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/download.py", line 117, in __call__
      local_path, is_temp = self.download(url, md5sum, path)
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/download.py", line 196, in download
      tmp_path, headers = urlretrieve(url, tmp_path)
    File "/xeebo/python27/lib/python2.7/site-packages/zc.buildout-2.4.1-py2.7.egg/zc/buildout/download.py", line 41, in urlretrieve
      url_obj = urllib2.urlopen(url)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 127, in urlopen
      return _opener.open(url, data, timeout)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 404, in open
      response = self._open(req, data)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 422, in _open
      '_open', req)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 382, in _call_chain
      result = func(*args)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 1222, in https_open
      return self.do_open(httplib.HTTPSConnection, req)
    File "/xeebo/python27/lib/python2.7/urllib2.py", line 1153, in do_open
      h = http_class(host, timeout=req.timeout) # will parse host:port
    File "/xeebo/python27/lib/python2.7/httplib.py", line 1186, in __init__
      source_address)
    File "/xeebo/python27/lib/python2.7/httplib.py", line 706, in __init__
      (self.host, self.port) = self._get_hostport(host, port)
    File "/xeebo/python27/lib/python2.7/httplib.py", line 748, in _get_hostport
      raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
  InvalidURL: nonnumeric port: 'password@pypi.myhost.com'
```

**Comment by reinout** [comment]
I see the same problem locally. The core problem is that `urllib2.urlopen()` (on python 2) and `urllib.request.urlretrieve()` (python 3) don't accept the username/password inside the URL.

See http://stackoverflow.com/questions/1906977/read-https-url-from-python .

**Comment by mauritsvanrees** [comment]
I can confirm. Note that the same syntax is working fine when used in the find-links option.

I tried zc.buildout 2.4.1 and 1.7.1 and saw the same in both versions, so it is not something recent.

**Comment by reinout** [comment]
I *do* think it is a recent change. If you this in python 2:

    import urllib, urllib2
    url = https://user:password@pypi.myhost.com/myconfig.cfg
    urllib.urlopen(url)  # Fails because the url goes nowhere, which is fine
    urllib2.urlopen(url)  # Gives the 'nonnumeric port' error.

And... we moved from urllib to urllib2 on 10 July: https://github.com/buildout/buildout/commit/9299c184af0baef02f41abd2b7a499e330451d15

That's on python 2, btw. I think it was already broken before on python 3.

It looks like we need to write a function that runs `urlsplit()` and strips out the username/password and adds basic auth and then feeds it to `urllib2.open()`. Because python cannot do a simple url like this itself. Which sounds weird.

**Comment by reinout** [comment]
Yep, broken on python 3:

    url = "https://user:password@pypi.myhost.com/myconfig.cfg"
    from urllib.request import urlretrieve
    urlretrieve(url)

I don't think this code was really changed by the 10 July commit.

**Comment by reinout** [comment]
I see some code in setuptools' `package_index.py` that uses `urlparse()` and `splituser()`. See the `open_with_auth()` function there.

**Comment by projekt01** [comment]
I can agree that before 2.4.1 zc.buildout was working fine. I was using 2.3.1 and was switching to 2.4.1 which is broken. Currently I'm using 2.4.0 which is working fine. I'm using python 2.7.7. Note that python 2.7.8 and 2.7.9 provides some backported code from python3 (urllib2/3 ?). I can't remember exactly the details but I switched back to python 2.7.7 because of some http(s) request issues. Probably something with SSL certificate verification. Sorry about this vague info, but what I like to say is, that the issue could depend on the different python version 2.7.7, 2.7.8 or 2.7.9.

**Comment by projekt01** [comment]
@reinout I've patched zc.buildout download.py and added authentication support like you suggested. It's a bit painfull to apply this patch for each server since we only use buildbot and zc.buildout in our release stack. Can you apply this changes and release them?

We changed the following code in download.py from:

    except ImportError:
        # Python 2
        from urlparse import urlparse

        import urllib2

        def urlretrieve(url, path):
            """Work around Python issue 24599
            """
            url_obj = urllib2.urlopen(url)
            with open(path, 'wb') as fp:
                fp.write(url_obj.read())
            return path, url_obj.info()

to:

    except ImportError:
        # Python 2
        import base64
        from urlparse import urlparse
        from urlparse import urlunparse
        import urllib2

        def urlretrieve(url, tmp):
        """Work around Python issue 24599 includig basic auth support
        """
            scheme, netloc, path, params, query, frag = urlparse(url)
            auth, host = urllib2.splituser(netloc)
            if auth:
                url = urlunparse((scheme, host, path, params, query, frag))
                req = urllib2.Request(url)
                base64string = base64.encodestring(auth)[:-1]
                basic = "Basic " + base64string
                req.add_header("Authorization", basic)
            else:
                req = urllib2.Request(url)
            url_obj = urllib2.urlopen(req)
            with open(tmp, 'wb') as fp:
                fp.write(url_obj.read())
            return tmp, url_obj.info()

**Comment by stefano-m** [comment]
@projekt01, thanks for your patch.

Probably, submitting a PR with your changes would be more effective as it enables a better code review experience and easier merge.

**Comment by stefano-m** [comment]
I am also wondering whether it would be more effective for buildout to use [requests](https://pypi.python.org/pypi/requests) rather than the core Python modules.

**Comment by freddrake** [comment]
It's valuable that buildout have as few dependencies as possible, even if those dependencies are better.

Buildout was designed to work with very little foundation since there's a goal to use it to build applications on top of "clean" Python installations, which won't have requests.

**Comment by stefano-m** [comment]
@freddrake I get that and having little or no dependencies is a great asset.

On the other hand Python's HTTP libraries don't have a great API while `requests` does (and in turn does not have any other dependencies), so it might be worth considering it. 

After all, buildout downloads, say, `zc.recipe.egg` anyway.

**Comment by mgedmin** [comment]
Ah, but how can buildout download requests if it uses requests to do the downloading?

**Comment by stefano-m** [comment]
@mgedmin, good point!

Maybe by vendoring ([that's what pip does](https://github.com/pypa/pip/tree/develop/pip/_vendor/requests)... even though I'm not a big fan of vendoring)?

**Comment by tseaver** [comment]
:-1:  to vendoring requests, which itself vendors a huge pile of stuff.

**Comment by jimfulton** [comment]
I don't see any problem depending on requests. The bootstrap script already uses setuptools to install buildout. It could install requests as well.

BTW, I'm thinking we should de-emphasize bootstrapping. It's a pain and not a significant part of buildout's value.

**Comment by do3cc** [comment]
these days I just pip install buildout in my virtualenv, works better than bootstrapping

**Comment by do3cc** [comment]
Even though I am wary about having a requests dependency, I remember customers that have been forced to switch to inofficial http pypi mirrors because urllib could not handle the https proxy. This will probably just work with requests

**Comment by stefano-m** [comment]
@jimfulton and other core buildout devs, would you then consider a PR that uses `requests` instead of the current implementation?

**Comment by reinout** [comment]
@stefano-m: @jimfulton said "yes" three days ago: "I don't see any problem depending on requests. The bootstrap script already uses setuptools to install buildout. It could install requests as well." See https://github.com/buildout/buildout/issues/257#issuecomment-160169552

So... yes, try it with requests. Note that you might have to look in zc.recipe.egg, too. Though I thought it imported download routines from buildout. (So watch out with renaming stuff :-) )

**Comment by reinout** [comment]
I've included the proposed patch from @projekt01 (as turned into a PR by @gyst, thanks) and released 2.5.1.

Can those affected by the bug check if it works for them, now? Please re-open the ticket if there's a problem :-)

**Comment by gyst** [comment]
Works For Me (TM), thanks @reinout!

**Comment by pandu** [comment]
pandu
