### ISSUE TITLE
setuptools 18.3.1 breaks with zc.buildout 2.4.3: "zipfile.BadZipfile: File is not a zip file"

### ISSUE THREAD

**Issue by tisto** [buildout/buildout#262]
Running "python bootstrap.py" with setuptools 18.3.1 and zc.buildout fails with this error trace:

```
$ python bootstrap.py 
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.zip
Extracting in /tmp/tmpkmgxk8
Traceback (most recent call last):
  File "bootstrap.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

Running "python bootstrap.py --setuptools-version=18.2" works fine.

I'm not sure if this is a buildout or setuptools issue.

**Comment by reinout** [comment]
I just ran a random bootstrap and saw the same error message.

Note: a quick `wget https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.zip` gives me a 404. So it seems something bigger is wrong.

**Comment by reinout** [comment]
If I look at https://pypi.python.org/simple/setuptools/, most releases have both a .zip and a .tar.gz.

18.3.1 only has the .tar.gz.

**Comment by reinout** [comment]
Ok, problem found. Our `bootstrap.py` downloads https://bootstrap.pypa.io/ez_setup.py and runs it.

That `ez_setup.py`, inside `download_setuptools()` is hardcoded to download the zip version. So it is an upstream problem that we cannot really do anything about except opening issues there.

**Comment by reinout** [comment]
Filed a bug with "blocker" status here: https://bitbucket.org/pypa/setuptools/issues/427/the-1831-release-misses-the-zip-version-so

"Blocker" status seems justified if all buildout bootstraps are now broken.

**Comment by pbauer** [comment]
Workaround: 
First get the newest bootstrap.py:
```bash
wget http://downloads.buildout.org/2/bootstrap.py
```
Then pinn the setuptools-version when running bootstrap:
```bash
./bin/python bootstrap.py --setuptools-version=18.3
```

**Comment by reinout** [comment]
18.3.1 was released quickly after 18.3, so presumably there's an error in there. So the originally mentioned workaround to use 18.2 is better.

(You're completely right that you *do* need the most recent bootstrap :-) )

**Comment by pbauer** [comment]
@reinout updated :-)

**Comment by reinout** [comment]
It is now fixed, a setuptools zipfile was uploaded.

See https://bitbucket.org/pypa/setuptools/issues/427/the-1831-release-misses-the-zip-version-so#comment-21585192

**Comment by davilima6** [comment]
This seems to happen with v20.10.0 and v20.10.1:

* https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.0.zip
* https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
