### ISSUE TITLE
bump zope.interface versions because it does not support py3.3

### ISSUE THREAD

**Issue by agroszer** [buildout/buildout#271]
should not be a biggie? objections?

**Comment by reinout** [comment]
Buildout doesn't contain or depend on zope.interface, so I think you've added the ticket in the wrong spot :-)

**Comment by agroszer** [comment]
but why is then this here?

https://github.com/buildout/buildout/blob/master/buildout.cfg#L7

Also, dev.py installs zope.interface

**Comment by mgedmin** [comment]
zope.testrunner depends on zope.interface.

I've no idea why we're pinning specific versions instead of using the latest release.  The pins showed up in https://github.com/buildout/buildout/commit/b9138c32c398eeddd20d080cd05ac63af0cce13a with no no reason given for them.

**Comment by mgedmin** [comment]
See also: https://github.com/buildout/buildout/commit/1204aa0598123a4183481bff45c9a8a9d3b4e626

(I wish @agroszer would be a bit more specific, e.g. a traceback of "here's how zc.buildout's tests fail currently on python 3.3 because zope.interface is too old" would make it clearer what's going on.)

**Comment by agroszer** [comment]
It does not fail, just with some luck compiles the C extensions, because 4.0.1 has no binaries for py 3.3

**Comment by reinout** [comment]
I pinned everything to the latest version in #272

@mgedmin: I'm leaning towards pinning them instead of using the lastest release. Buildout tests are hard enough to get right without having to debug possible changes in zope.testing or so.

**Comment by reinout** [comment]
Ok, version is bumped. Closing the issue. Hopefully winbot likes me now.
