### ISSUE TITLE
How to compile gevent1.0.2 in buildout with c99?

### ISSUE THREAD

**Issue by guochunyang** [buildout/buildout#281]
Since xcode upgrading to 7.1, gevent can't buildout successfully.
The author of gevent suggest to use -std=c99

**Comment by mgedmin** [comment]
Can you give us a small buildout.cfg that reproduces the error you're seeing?

**Comment by guochunyang** [comment]
```
[buildout]
develop = .
newest = false
extends = versions.cfg
show-picked-versions = true
update-versions-file = versions.cfg
relative-path = true
parts = app

[app]
recipe = zc.recipe.egg
interpreter = python
eggs = AccountStatus
       ipython
       gunicorn

```

**Comment by reinout** [comment]
Gevent is not a direct dependency of gunicorn, if I remember correctly. See http://docs.gunicorn.org/en/latest/install.html . I've got three questions:

- Is gevent a dependency in your own `setup.py`?

- Can you give us the error you're seeing?

- And you give us the page where the `-std=c99` is mentioned?

**Comment by guochunyang** [comment]
@reinout  I am so sorry that I have't delete some content from buildout.cfg.

You can refer to:  [https://github.com/NixOS/nixpkgs/issues/8569](https://github.com/NixOS/nixpkgs/issues/8569) and [https://github.com/gevent/gevent/issues/656](https://github.com/gevent/gevent/issues/656)

**Comment by mgedmin** [comment]
Judging from https://github.com/gevent/gevent/issues/656#issuecomment-142813358 you can use the following workaround:

```ini
[app]
recipe = zc.recipe.egg
environment = c99-env
...

[c99-env]
# https://github.com/gevent/gevent/issues/656
CFLAGS = -std=c99
```

**Comment by reinout** [comment]
@mgedmin I was just ready googling for that solution :-)

One extra note in case you get an error: you might have to add `:custom` after the recipe name like this:

    [app]
    recipe = zc.recipe.egg:custom

Oh, and don't forget to explicitly list `gevent` as the first of the eggs in that part.

I'm not too familiar with all the zc.recipe.egg compiler options, though.

**Comment by guochunyang** [comment]
I run `CFLAGS='-std=c99' buildout`, and it worked.
