### ISSUE TITLE
Custom Index ignored

### ISSUE THREAD

**Issue by rdab** [buildout/buildout#290]
Hello:
I'm having an issue while setting up my environment with a custom `index` when installing `PasteScript`. Buildout attempts to install it from pypi while every other package is retrieved successfully from the custom `index`.

Below is the `buildout.cfg` I'm using:
```
[buildout]

index = http://10.10.10.10:8080/
include-site-packages = false
# allow-hosts = 10.10.10.10:8080/
newest = false
find-links = http://10.10.10.10:8080
install-from-cache = false

develop = 
... 

parts =
...
```
Relevant system packages:
```
$ pip list
setuptools (20.2.2)
zc.buildout (2.5.0)
...
```
### Another paths
* Uncommenting `allow-hosts` didn't do any better. Buildout doesn't look for it. (Is this the way to configure `allow-hosts` with IPs???)
* Declaring `PasteDeploy` before `PasteScript` was futile as well. Buildout install PasteDeploy correctly in the eggs folder, however `PasteScript` looks for it at pypi again.

Any ideas what I'm doing wrong?
Thanks in advance.

**Comment by mgedmin** [comment]
This is probably related to `setup_requires`, which means buildout doesn't get a chance to do anything; it's setuptools itself that's trying to fetch extra stuff during the execution of some package's `setup.py`.

I don't quite understand what specific package causes this in your case, nor which of the two named packages is the one that setuptools tries to download off PyPI, so I'll limit my comment to generalities:

Making sure that all packages listed in `setup_requires` are already installed and on the Python path is a good way to prevent setuptools from trying to download them from PyPI.  One way would be to wrap your buildout in a virtualenv and then pip install -i http://your/index PasteWhichever into it.

**Comment by rdab** [comment]
Thanks for your reply @mgedmin and I'm sorry for my english.

I'm trying to install `PasteScript`, which require `PasteDeploy`. If I do `pip install -i http://my-index PasteScript` it succesfully install `PasteScript` and its dependencies:  
```
....
Installing collected packages: Paste, PasteDeploy, PasteScript
  Running setup.py install for Paste
  Running setup.py install for PasteScript
Successfully installed Paste PasteDeploy PasteScript
```
I don't like this approach, because if I have to use `pip` to install my project dependencies, what is the point of using Buildout then.

Now, I've tried to specify those dependencies before `PasteScript` in the `buildout.cfg`, this way buildout should install them first and when the time comes for `PasteScript` there is no need to fetch them again. Something like this:
*This time with the `use-dependency-links = false`*
```
...
use-dependency-links = false

[my_part] 
recipe = zc.recipe.egg:scripts
eggs =
	Paste
	PasteDeploy
	PasteScript
```
But still looks for pypi...
```
developer@t1-dev-env:~/build_test$ bin/buildout -v
Installing 'zc.recipe.egg'.
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python" "-c" "import sys; sys.path[0:0] = ['/usr/local/lib/python2.7/dist-packages']; from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/developer/build_test/eggs/tmpeE3f7I" "-q" "/tmp/tmp1QDAojget_dist/zc.recipe.egg-2.0.3.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

Got zc.recipe.egg 2.0.3.
Picked: zc.recipe.egg = 2.0.3
Unused options for buildout: 'include-site-packages'.
Installing my_part.
Installing 'Paste', 'PasteDeploy', 'PasteScript'.
We have no distributions for Paste that satisfies 'Paste==1.7.5.1'.
Getting distribution for 'Paste==1.7.5.1'.
Running easy_install:
"/usr/bin/python" "-c" "import sys; sys.path[0:0] = ['/usr/local/lib/python2.7/dist-packages']; from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/developer/build_test/eggs/tmp3ABKdB" "-q" "/tmp/tmp29ELBWget_dist/Paste-1.7.5.1.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
Got Paste 1.7.5.1.
We have a develop egg: setuptools 20.2.2
We have no distributions for PasteDeploy that satisfies 'PasteDeploy==1.3.3'.
Getting distribution for 'PasteDeploy==1.3.3'.
Running easy_install:
"/usr/bin/python" "-c" "import sys; sys.path[0:0] = ['/usr/local/lib/python2.7/dist-packages']; from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/developer/build_test/eggs/tmpCVTC8X" "-q" "/tmp/tmp_dQauDget_dist/PasteDeploy-1.3.3.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

warning: no files found matching 'docs/*.html'
warning: no previously-included files found matching 'docs/rebuild'
Got PasteDeploy 1.3.3.
We have no distributions for PasteScript that satisfies 'PasteScript>=2.0'.
Getting distribution for 'PasteScript>=2.0'.
Running easy_install:
"/usr/bin/python" "-c" "import sys; sys.path[0:0] = ['/usr/local/lib/python2.7/dist-packages']; from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/developer/build_test/eggs/tmprKP2FA" "-q" "/tmp/tmpJJm6SMget_dist/PasteScript-2.0.2.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

Warning: no news for this version found
Download error on https://pypi.python.org/simple/PasteDeploy/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'PasteDeploy' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or download links found for PasteDeploy
error: Setup script exited with error: Could not find suitable distribution for Requirement.parse('PasteDeploy')
An error occurred when trying to install PasteScript 2.0.2. Look above this message for any errors that were output by easy_install.
While:
  Installing my_part.
  Getting distribution for 'PasteScript>=2.0'.
Error: Couldn't install: PasteScript 2.0.2
```

I suppose I should contact `PasteScript` developers as well.

**Comment by mgedmin** [comment]
I'm afraid I don't know how to make it work with just zc.buildout, since this is setuptools code executed in a separate process that's doing the PyPI fetching.

You could try asking for advice on the [distutils-sig@python.org mailing list](https://mail.python.org/mailman/listinfo/distutils-sig).

**Comment by rdab** [comment]
Ok, thanks you @mgedmin.

**Comment by rdab** [comment]
Finally I found a workaround for this situation in pip's documentation pages while evaluating @mgedmin proposal. For future reference here is a briefing note:

As @mgedmin suggested, this issue is related to the `setup_requires` argument and because it is a setuptools parameter, pip has even less to do about it. It's clearly stated at [pip's docs](https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires).

So, the solution is to define a system or personal `distutils` configuration to override how the dependencies are located. The details at the python [docs](https://docs.python.org/2/install/index.html#location-and-names-of-config-files).
