### ISSUE TITLE
booststrap-buildout is not compatible with the new links from pypi 

### ISSUE THREAD

**Issue by tiagofrepereira2012** [buildout/buildout#292]
Hey,

The version 20.10.1 of setuptools was just released on pypi.
When you try to bootstrap something I get the following error

```
python bootstrap-buildout.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
Extracting in /var/folders/s7/64dky7391z99w2vzp50lzgjc0000gq/T/tmprqhYfJ
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 64, in _build_egg
  File "/Users/tiagodefreitaspereira/Documents/envs/miniconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 103, in archive_context
  File "<string>", line 87, in __new__
  File "/Users/tiagodefreitaspereira/Documents/envs/miniconda2/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/Users/tiagodefreitaspereira/Documents/envs/miniconda2/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

The thing is the link https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip does not exist. The correct is this one https://pypi.python.org/packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip#md5=5e236ca1a0faca5b609eb57b0dcb4184

I have seen since last week that pypi changed the way of provide the download links.
What should I do to make it work with zc.buildout (for the time being I pined the setuptools version with the previous one using --setuptools-version)?

Thanks

**Comment by jimfulton** [comment]
Yup. It's hosed.

**Comment by agb80** [comment]
For now we are installing buildout from pip instead of using the boostrap file

**Comment by tiagofrepereira2012** [comment]
Ok, so how I works?

Thanks

**Comment by reinout** [comment]
Run "pip install buildout". Either for a local user install or globally. Or in a virtualenv. Then simply call `buildout` in the directory with your buildout config. Buildout will then install itself locally with the correct version.

Note that it also works to use another buildout's `bin/buildout`. So `../some-other-project/bin/buildout` also works to set you up.

**Comment by jimfulton** [comment]
I've submitted a PR for setuptools that should fix this.

**Comment by tiagofrepereira2012** [comment]
Ok, thanks :-)

It is working now. Shall I close this one?

**Comment by idgserpro** [comment]
@tiagofrepereira2012 yes. Check https://github.com/pypa/setuptools/issues/557.

**Comment by tiagofrepereira2012** [comment]
Great, thanks :-)
