### ISSUE TITLE
Bootstrap fails with setuptools v20.10.1

### ISSUE THREAD

**Issue by hvelarde** [buildout/buildout#293]
Buildout rises `zipfile.BadZipfile: File is not a zip file` at bootstrap time.

See: https://travis-ci.org/simplesconsultoria/sc.embedder/jobs/125597044

Latest version of **bootstrap.py** is being used.

This seems to be related with #262.

**Comment by agb80** [comment]
Same problem here

**Comment by idgserpro** [comment]
The discussion is being done in https://github.com/pypa/setuptools/issues/557 as well.

**Comment by BetaGrumm** [comment]
Yep. Same here.

**Comment by idgserpro** [comment]
Folks, issue solved.

**Comment by hvelarde** [comment]
@idgserpro awesome!
