### ISSUE TITLE
setuptools version 24

### ISSUE THREAD

**Issue by mileo** [buildout/buildout#301]
Hi, i'm using buildout in ubuntu 14.04 server and desktop. 

I can only run bootstrap-buildout.py with setuptools version 24.

> Traceback (most recent call last):
>   File "setup.py", line 21, in <module>
>     exec(init_file.read(), command_ns)
>   File "<string>", line 11, in <module>
>   File "/tmp/tmpsOrMPd/setuptools-24.0.0/setuptools/__init__.py", line 14, in <module>
>     from setuptools.extension import Extension
>   File "/tmp/tmpsOrMPd/setuptools-24.0.0/setuptools/extension.py", line 11, in <module>
>     from . import msvc
>   File "/tmp/tmpsOrMPd/setuptools-24.0.0/setuptools/msvc.py", line 244, in <module>
>     class PlatformInfo:
>   File "/tmp/tmpsOrMPd/setuptools-24.0.0/setuptools/msvc.py", line 253, in PlatformInfo
>     current_cpu = safe_env['processor_architecture'].lower()
>   File "/opt/product/sandbox/lib/python2.7/UserDict.py", line 23, in __getitem__
>     raise KeyError(key)
> KeyError: 'processor_architecture'
> /tmp/bootstrap-Ti50Ip/setuptools-24.0.0-py2.7.egg
> Traceback (most recent call last):
>   File "bootstrap.py", line 117, in <module>
>     ez['use_setuptools'](**setup_args)
>   File "<string>", line 178, in use_setuptools
>   File "<string>", line 129, in _do_download
>   File "<string>", line 75, in _build_egg
> IOError: Could not build the egg.
>

EX:

bootstrap-buildout.py --setuptools-version=23.0.0

**Comment by mauritsvanrees** [comment]
Setuptools 24.0.1 was released to address this.

**Comment by gotcha** [comment]
Can this issue be closed then ?

**Comment by reinout** [comment]
I think so. If not, it can always be re-opened :-)
