### ISSUE TITLE
Could buildout work if setuptools required pip to install?

### ISSUE THREAD

**Issue by jaraco** [buildout/buildout#306]
In pypa/setuptools#581, I've started the discussion about Setuptools wanting to drop support for installing itself. My biggest concern with this change is I understand that buildout relies heavily on Setuptools (even internals) and if Setuptools couldn't install itself, it could dramatically impact buildout.

Of course, I'd like to test this possibility and shake out some of the issues, but first I'd like to hear from the buildout project maintainers if this idea is remotely viable and what hurdles would have to be cleared or prerequisites met. What would it mean for buildout if setuptools (and its dependencies) could only be installed by pip?

**Comment by jimfulton** [comment]
Thanks for asking!  And thanks for keeping setuptools going this far.

We've resigned ourselves to giving up on the bootstrapping process for a while now, although I still like it because I remain a bit fanatical about "clean python" installs. :)

Also, buildout will use setuptools if setuptools is already installed.

Please just do what you need to to and keep us informed.

**Comment by tseaver** [comment]
@jaraco If we were to move to the model you describe, would you be exposing a library API for pip?  I've always thought that was off the table.  Shelling out to the `pip` command to get things done seems less than ideal from the perspective of buildout.

**Comment by jimfulton** [comment]
Hm, I interpreted @jaraco's question as suggesting that setuptools was dropping ez_setup but that setuptools could still be used to install other packages.

**Comment by jaraco** [comment]
Yes, at this stage, I'm not suggesting the removal of easy_install or its API, with the one caveat that you can no longer `easy_install -U setuptools` (or the equivalent). Well, I guess you could, but you'll run into problems because setuptools will have been installed by pip as a non-egg and setuptools no longer effectively upgrades over non-egg installations. This restriction would apply to any dependencies of setuptools also (currently packaging, pyparsing, six, and appdirs). But for every other package in the environment, `easy_install` will remain an option as it does today.

I'm even thinking for compatibility I'll try to keep ez_setup's command-line interface (shelling out to pip or invoking pip natively) to enact the recommended bootstrapping steps. I haven't yet attempted an implementation, which may lead me away from that approach.

> Shelling out to the pip command to get things done seems less than ideal from the perspective of buildout.

I've found this approach to be a non-issue in nearly every environment where I've tried it. Is there a feature unique to buildout that would make shelling out particularly problemmatic (or just inelegant)?

**Comment by jaraco** [comment]
I've rolled a new version of ez_setup, which can be found in the [bootstrap-581 branch](/pypa/setuptools/tree/bootstrap-581] and referenced directly [from this link](https://raw.githubusercontent.com/pypa/setuptools/bootstrap-581/ez_setup.py).

In reviewing the buildout bootstrap code, it appears that buildout primarily uses `ez_setup.use_setuptools(version=)` and maybe `(version=, to_dir=)`. This new bootstrap script (a) has an implicit requirement on pip and (b) ignores the `to_dir` parameter to `use_setuptools` (posting a warning). It additionally (c) no longer attempts to update in place an installation of setuptools but will still fail loudly if the specified version isn't satisfied.

Will this bootstrap script work for buildout? Any other comments or concerns?

**Comment by lukasgraf** [comment]
> Any other comments or concerns?

@jaraco un-vendoring `six` in pypa/setuptools#933 might cause some issues. I'm getting

```
Error: The requirement ('six>=1.10.0') is not allowed by your [versions] constraint (1.8.0)
```

since today when running a Plone buildout, which is somewhat unsurprising:

Someone correct me if I'm wrong, but as far as I know `six` has some forwards- as well as backwards-incompatibilites. Which is why most projects or libraries that require it do so with very explicit version constraints, often for both min and max versions. Given that, and a large enough dependency graph in your project, it's only a matter of time until you get conflicting version constraints.

For that reason, I think `six` should only ever be vendorized, not depended upon, otherwise things are bound to break at some point. I'm not sure whether that really was the author's intention, but the sentence

> It is contained in only one Python file, so it can be easily copied into your project.

 leads me to believe it might have been.

**Comment by jaraco** [comment]
> Someone correct me if I'm wrong, but as far as I know six has some forwards- as well as backwards-incompatibilites.

The versioning scheme of six provides at least a suggestion that each release has been intended to be backward-compatible. I tried using GitHub to do the diff, but six is missing the release tags. Looking at [the diff on Bitbucket](https://bitbucket.org/gutworth/six/compare/1.10.0..1.8.0#diff), however, the changes between 1.8.0 and 1.10.0 appear to be largely additive and stabilizing. Reading [the changelog](https://github.com/benjaminp/six/blob/master/CHANGES), there's no declared backward-incompatibilities.

> it's only a matter of time until you get conflicting version constraints ... six should only ever be vendorized

I fail to see how six is a special case here. Yes, it's special in how easy it is to vendorize, but any of the other dependencies that setuptools has or elects to have later could additionally conflict with those of a given package. Another installation might have a requirement on packaging or pyparsing that conflicts. Would that justify again that setuptools should vendor those packages? Very quickly we head down the slippery slope that every package should always vendor everything, which is both impractical and messy.

Fortunately, the functionality on which our environments rely is being stripped out of Setuptools, which means that fewer and fewer environments are going to require Setuptools for anything but building applications, meaning you could potentially use a different environment for invoking Setuptools than you do for running your target application, and thus avoiding any conflicts.

You're right that six itself was written to be easily vendored and as a special case, six could easily be vendored in Setuptools, but I immediately foresee a problem when pkg_resources is extracted into its own package (#863) and now six will get vendored into two packages, perhaps diverging.

I would very much prefer to rely on the first-class tooling (i.e. pip, install_requires, virtualenv, rwt, etc) for requiring, incorporating, and isolating packages and let the applications use vendoring if their application requires an older version than the minimum required by Setuptools.

`easy_install` actually has [tooling to address this specific need](https://python-packaging-user-guide.readthedocs.io/multi_version_install/#multi-version-installs), but that functionality is not something that pip supports, so is effectively deprecated.

> six should only ever be vendorized

In that case, why not vendorize it in your environment and call it good?

**Comment by lukasgraf** [comment]
Thanks for your quick response.

> Looking at the diff on Bitbucket, however, the changes between 1.8.0 and 1.10.0 appear to be largely additive and stabilizing. Reading the changelog, there's no declared backward-incompatibilities.

You're right, even going further back in the changelog, it appears changes should be backward-compatible, or at least are intended to be.

> I fail to see how six is a special case here.

My reasoning was based on the assumption that newer releases of `six` haven't always been backward-compatible. If that's not the case (or could be considered a bug in `six` if there were instances of that), then there's no issue here, and there shouldn't be a library needing a version constraint for a maximum version of `six`.

> Very quickly we head down the slippery slope that every package should always vendor everything, which is both impractical and messy.

Agreed, I certainly didn't mean to advocate that.

>[...] but I immediately foresee a problem when pkg_resources is extracted into its own package (#863) and now six will get vendored into two packages, perhaps diverging.

Good point, I see how that could get messy.

> [...] and let the applications use vendoring if their application requires an older version than the minimum required by Setuptools.
>
> In that case, why not vendorize it in your environment and call it good?

Fair point 😉 

From what I can tell there actually shouldn't be much need to do so. I searched for `setup.py` version constraints limiting `six` to a maximum version, but honestly, I could only find ones that require a minimum version. The issues I'm remembering here might have much more to do with the fact that in the Plone ecoysystem pins exact versions through its KGS.

**Comment by jugmac00** [comment]
As far as I understand, we do not self bootstrap any more, but we recommend `virtualenv` and `pip`, see https://github.com/buildout/buildout/pull/555/files 

Imho this issue can be closed.
