### ISSUE TITLE
Alternating between pypy and cpython is painful when there are extensions. 

### ISSUE THREAD

**Issue by jimfulton** [buildout/buildout#322]
Because the Python platform isn't in the egg name.

Yet another reason to user virtualenv/pip (for everything but recipes).

**Comment by jamadden** [comment]
The same pain can arise when alternating between wide and narrow unicode builds of CPython 2. Not that I do that very often, but it does happen.

**Comment by jimfulton** [comment]
Fix released in 2.7.0
