### ISSUE TITLE
Force install egg

### ISSUE THREAD

**Issue by imanhodjaev** [buildout/buildout#328]
Hi,

I have the following `buildout.cfg`

```
[buildout]
include-site-packages = false
versions = versions

parts =
    makedirs

eggs =
    six

[versions]
six = 1.10.0

[makedirs]
recipe = z3c.recipe.mkdir
paths = ${buildout:directory}/var
```

When I call `bin/buildout` I expect to see six in the eggs folder at the end but `buildout` doesn't do it.

What is wrong with this, how to force buildout to put egg into eggs folder?

I tried to add custom egg definition and include it in `parts` but it didn't work too.

Thanks.

**Comment by jamadden** [comment]
buildout won't do anything unless there is a part that tells it. You don't have a part specified that will install eggs. You need to add something like this:
```
[python]
recipe = zc.recipe.egg
eggs = ${buildout:eggs}
```

and add that part to the `parts` line in the `[buildout]` section.

**Comment by imanhodjaev** [comment]
Hi @jamadden,
Even if I edit `buildout.cfg` like


```
[buildout]
include-site-packages = false
versions = versions

parts =
    makedirs
    super_part

eggs =
    six

[versions]
six = 1.10.0

[makedirs]
recipe = z3c.recipe.mkdir
paths = ${buildout:directory}/var

[super_part]
recipe = zc.recipe.egg
eggs = ${buildout:eggs}
```

there is no egg called six in eggs folder

```
(projects) ttt|⇒ ll eggs
total 8,0K
drwxrwxr-x 4 sultan sultan 4,0K Feb  1 18:50 z3c.recipe.mkdir-0.6-py2.7.egg
drwxrwxr-x 4 sultan sultan 4,0K Feb  1 18:56 zc.recipe.egg-2.0.3-py2.7.egg
```

**Comment by jamadden** [comment]
Then I suspect you have 'six' already installed in your Python installation. Try a different egg.

Buildout 2.x pays no attention to 'include-site-packages'. That was a (broken) feature of buildout 1. From the documentation:

> Buildout no-longer tries to provide full or partial isolation from system Python installations. If you want isolation, use buildout with virtualenv, or use a clean build of Python to begin with.
>
> Providing isolation was a noble goal, but it's implementation complicated buildout's implementation too much.

**Comment by imanhodjaev** [comment]
@jamadden the problem is in easy_install bundled with buildout, so when I uninstall six and the call `python bootstrap.py` I have the following exception

```
(projects) ttt|⇒ python bootstrap-buildout.py
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpR9wPdC
Now working in /tmp/tmpR9wPdC/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-kF5AJC
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-kF5AJC/setuptools-33.1.1-py2.7.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 200, in <module>
    import zc.buildout.buildout
  File "/home/sultan/Envs/projects/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/home/sultan/Envs/projects/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 896, in <module>
    check_picked=False))
  File "/home/sultan/Envs/projects/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 893, in install
    return installer.install(specs, working_set)
  File "/home/sultan/Envs/projects/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 692, in install
    for_buildout_run=for_buildout_run):
  File "/home/sultan/Envs/projects/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 492, in _get_dist
    % requirement)
zc.buildout.UserError: We don't have a distribution for six>=1.6.0
and can't install one in offline (no-install) mode.
```

**Comment by jamadden** [comment]
I don't understand what you're saying the problem is. As of recent setuptools releases, six is now a requirement of setuptools. If you break those requirements by uninstalling six, leaving your environment in an unknown state, you can expect unknown and broken things to happen.

**Comment by imanhodjaev** [comment]
But I can not understand why buildout doesn't bundle six in `eggs` folder.

**Comment by imanhodjaev** [comment]
@jamadden can you please check this too if you have some spare time?

**Comment by jamadden** [comment]
If an egg (a dependency) is already installed in the environment, buildout will not try to install it. Your scripts and code will have access to the version found in the environment.

**Comment by imanhodjaev** [comment]
@jamadden I tried all options to force it to bundle, my particular case is that I use Docker to build packages and some time ago it just stopped working because of the problem I described.

**Comment by jimfulton** [comment]
Buildout doesn't bundle anything.

You either install buildout using pip, which installs it's dependencies,

Or you install it via the bootstrapping process, which also installs it's dependencies.

If you want to run buildout in offline mode, **you** have to have it and its dependencies downloaded already.

**Comment by jimfulton** [comment]
My guess is that you updates setuptools in your container, but didn't update buildout.

You need buildout 2.7.1 to work with setuptools >= 34

**Comment by imanhodjaev** [comment]
Buildout breaks its own goals of creating isolated builds if despite explicit configuration it skips downloading dependency.
@jimfulton Yes recently I updated setuptools though decided to downgrade it again and pin version to the one before the six was added as a dependency.

**Comment by jimfulton** [comment]
It isn't a goal of buildout (anymore) to create isolated environments.  Python makes that too hard without a sledge hammer like virtualenv.

It is a goal of buildout not to modify its environment. I think it achieves that goal pretty well. <shrug>

**Comment by imanhodjaev** [comment]
@jimfulton I am sorry if I confused you. I meant isolated builds not environments.

**Comment by imanhodjaev** [comment]
@jimfulton why did you close the issue? It is in fact an issue.

**Comment by jimfulton** [comment]
We can't fix user error.

You broke buildout's environment because you changed a dependency underneath it.

If you want to consider it a bug, fine. It was fixed by buildout 2.7.1.

BTW, before reporting a problem, you should generally check to see if the problem exists in the current release.

**Comment by imanhodjaev** [comment]
@jimfulton yes the problems exists in the latest release of buildout.

**Comment by jimfulton** [comment]
No, it doesn't.

I'm not sure we agree on what the problem is however.

AFAICT, the problem is that you updated setuptools and that broke buildout. A newer version of buildout wouldn't have been broken by that.

If that's not the problem, I suggest trying to state your problem more clearly.

**Comment by imanhodjaev** [comment]
@jimfulton I am agree this might due to misleading report from my part.

All I want to have is
1. Define package in versions
2. Add package to eggs list
3. See package's egg downloaded and extracted `into` eggs folder

The problem here is if `six` is already in `site-packages` then then buildout doesn't add egg to eggs folder.

**Comment by jimfulton** [comment]
Then use a cleaner Python.

If you want buildout to install **all** distributions, then you need to have a Python install that doesn't have anything in site-packages.

As Jason pointed out, buildout won't install distributions in eggs if they're already in the environment.

**Comment by leorochael** [comment]
>  Then use a cleaner Python.

For example, by using virtualenv

> As Jason pointed out, buildout won't install distributions in eggs if they're already in the environment.

And that's a feature, not a bug

**Comment by imanhodjaev** [comment]
@jimfulton good, thank you.

**Comment by alexsv** [comment]
@jimfulton why isn't it an option to update https://bootstrap.pypa.io/ez_setup.py and install six as a requirement for a setuptools?

**Comment by leorochael** [comment]
@alexsv, `six` will be installed during the bootstrapping process, but only if it's not already in the environment, which is what this issue is about.

**Comment by jimfulton** [comment]
On Thu, Feb 2, 2017 at 4:44 AM, Alex <notifications@github.com> wrote:

> @jimfulton <https://github.com/jimfulton> why isn't it an option to
> update https://bootstrap.pypa.io/ez_setup.py and install six as a
> requirement for a setuptools?
>
It's not necessary. Bootstrapping isn't the issue here.  The current
version of ez_setup.py installs an older version of setuptools that doesn't
require six.When buildout is bootstrapped, it installs this older version
of setuptools. When buildout is run next, it see a new version of
setuptools and installs it and it's dependencies.

**Comment by jimfulton** [comment]
On Thu, Feb 2, 2017 at 7:11 AM, Leonardo Rochael Almeida <
notifications@github.com> wrote:

> @alexsv <https://github.com/alexsv>, six will be installed during the
> bootstrapping process,
>
No, because it isn't needed then because ez_setup installs an older
setuptools.

but only if it's not already in the environment, which is what this issue
> is about.
>

It was never really clear what this issue was about. :)  But I'm pretty
sure it wasn't about bootstrapping.

It appears that at some point, the poster updated setuptools using pip
without updating buildout, which broke buildout. Pip is all about updating
individual snowflakes, which is one of the reasons I think it's stupid. :)

But ultimately, it seems the poster (wisely) wanted buildout  to control
everything, which requires a clean Python without anything in site packages.

**Comment by imanhodjaev** [comment]
@jimfulton as every other "poster" I expect buildout to bundle package I set in eggs folder.
@leorochael @jimfulton do you think there should be an option for it?

**Comment by jimfulton** [comment]
OK, I give up. I can't get through to you @imanhodjaev . I'm done with this issue.

**Comment by leorochael** [comment]
> @leorochael @jimfulton do you think there should be an option for it?

No, as mentioned several times, it's out of the scope of buildout to isolate itself from the Python enviroment that is running it.
