### ISSUE TITLE
Where are the canonical docs?

### ISSUE THREAD

**Issue by kalafut** [buildout/buildout#329]
Hi,

I'm fairly new to buildout, though the company I started with has used it for a while.  I was trying to improve build times and came across a blog post discussing settings like `eggs-directory`, `download-cache`, etc.  They seem to work, but I can't find any published docs discussing them.  The buildout.org website references version 1.2.1, but Github's version is in the 2.7 range. I did find docs in the repo referencing this option (https://github.com/buildout/buildout/blob/master/src/zc/buildout/downloadcache.txt), but nothing published. Where should I be looking for the latest docs (in general, not just these options)?

Thanks.

**Comment by gotcha** [comment]
AFAIK, the most complete source of information is the package page on PyPI:
https://pypi.python.org/pypi/zc.buildout/2.7.1

**Comment by jimfulton** [comment]
This is a great question. :/  @gotcha's answer is, sadly the best.

Buildout's docs were part of a failed experiment to use doctests as docs. Sorry. My bad.

(I have a strong itch to rewrite the docs from scratch.  I'm unsure whether the itch will get strong enough for me to scratch it.)

Please feel free to post questions to this tracker or to the distutils-sig mailing list.
