### ISSUE TITLE
how to remove [site|dist]-packages in created scripts

### ISSUE THREAD

**Issue by encolpe** [buildout/buildout#341]
In our project we're not allowed to use virtualenv or other python wrapping tools. Then we are using buildout with a KGS and `allow-picked-versions` set to False.
Running buildout neither it fails when a bad egg versions is in _/usr/lib/python2.7/dist-packages_ nor it getting the correct version from pypi.

Is there an option to ignore completely _site-packages_ and _dist-packages_?

**Comment by freddrake** [comment]
At Zope, we used a completely separate Python implementation that didn't include the system vendor's [site|dist]-packages at all.

I don't know if that's an option in your environment.

**Comment by jimfulton** [comment]
Nope. It's too hard. This was tried several years ago and it made the code unmaintainable.

I suggest setting your pins to match your Python environment (the one apparently imposed on you from above).

**Comment by encolpe** [comment]
I will try wih pyenv or lxc.
Thanks.
