### ISSUE TITLE
wheel_to_egg hook lays the wheel and the egg in the download cache at the same time.

### ISSUE THREAD

**Issue by leorochael** [buildout/buildout#345]
In case the download cache is configured, the `wheel_to_egg` function gets a `tmp` that **is** the download cache.

The result is that the download cache will have the egg AND the wheel at the same time. Since the index doesn't see the generated egg in the download cache, only the original `wheel`, this egg is only taking space and will be rewriten whenever the original wheel is needed.

Humpty will gladly do it for you, so you'll never notice the overwriting, but this bombed on me trying to replace `humpty` with `wheel install`, with an exception like:

    ValueError: Wheel file zest/releaser/tests/gitsvn.txt would overwrite /path/to/buildout/downloads/dist/zest.releaser-6.9-py2.7.egg/zest/releaser/tests/gitsvn.txt. Use force if this is intended

An actual, separate, temporary directory needs to be used in this case.

**Comment by jimfulton** [comment]
The index *does* see the egg, it just doesn't consider it more desireable.  A simple change should be to change the precedence of wheels to 2 rather than 3 in buildout.wheel.

**Comment by leorochael** [comment]
In setuptools, once we move the wheel support over there, I was hoping to create a new precedence `4` for wheels, as I think in general people will prefer wheels over sdists or eggs...

In any case, I consider the egg generated from the wheel to be a mere transformation artifact, like the temporary directories where sdists are unpacked to run `setup.py bdist_egg`.

IMHO, the place to put the egg generated by wheel should be the egg directory, not the download cache.

**Comment by jimfulton** [comment]
I was just suggesting a simpler fix, because there's lots to do. If you want change the code to use a separate temp dir, that's OK with me. Of course, you didn't say this had to happen now.

BTW, a related non-uncommon and frustrating failure is that if the download is only partially successful you end up with a poisoned download cache and you have to manually remove the partially-downloaded item, usually after much hair pulling to figure out WTF. We should probably be downloading to a separate temp dir as well. Something to think about if someone decided to refactor this code.

**Comment by leorochael** [comment]
> I was just suggesting a simpler fix, because there's lots to do.

Right, thanks.

> If you want change the code to use a separate temp dir, that's OK with me. Of course, you didn't say this had to happen now.

True. For now [I'm working around it](https://github.com/buildout/buildout.wheel/pull/9/files#diff-12ac8087746afce36875e42c887fd7c8R24).

**Comment by leorochael** [comment]
Another complicating factor: simultandeous use of a central download cache by different buildouts could cause the same converted egg to be written by different processes.

The only minimally safe way to use the `tmp` directory is by creating another `tempdir.mkdtemp` file inside.

**Comment by jimfulton** [comment]
Good point.

**Comment by leorochael** [comment]
Closed by #352, where the `wheel_to_egg` hook, now deprecated but still available, unpacks into a safe temp directory that's cleaned up after use, instead of in the download directory.
