### ISSUE TITLE
AttributeError: 'module' object has no attribute '_by_version_descending' on 2.9.0

### ISSUE THREAD

**Issue by mauritsvanrees** [buildout/buildout#375]
I just saw this [Travis error on a Plone package](https://travis-ci.org/collective/collective.catalogcleanup/jobs/208286558):

```
While:
  Installing.
  Checking for upgrades.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/buildout.py", line 1982, in main
    getattr(buildout, command)(args)
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/buildout.py", line 517, in install
    self._maybe_upgrade()
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/buildout.py", line 953, in _maybe_upgrade
    allow_hosts = self._allow_hosts
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    check_picked=check_picked)
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/easy_install.py", line 265, in __init__
    self._env = self._make_env()
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/easy_install.py", line 274, in _make_env
    full_path = self._get_dest_dist_paths() + self._path
  File "/home/travis/build/collective/collective.catalogcleanup/eggs/zc.buildout-2.9.0-py2.7.egg/zc/buildout/easy_install.py", line 293, in _get_dest_dist_paths
    return pkg_resources._by_version_descending(set(eggs + dists))
AttributeError: 'module' object has no attribute '_by_version_descending'
```

It fails in code that was introduced in the fresh `zc.buildout` 2.9.0.
The buildout works fine locally.
I haven't dived into it yet and I gotta run now.

**Comment by jimfulton** [comment]
What version of setuptools is being used?

**Comment by jimfulton** [comment]
I suspect we need to add a minimum setuptools version.

**Comment by jimfulton** [comment]
It looks like we now depend on setuptools >=28.8.0

**Comment by jimfulton** [comment]
That buildout pins buildout to 1.7.1 and setuptools to 20.1.1.

**Comment by hvelarde** [comment]
I'm facing the same issue; you can find answers to your questions here:

https://travis-ci.org/collective/collective.newsticker/jobs/208297713

it's weird because zc.buildout is pinned to 1.7.1.

**Comment by jimfulton** [comment]
I bet that the travis Python has a version of setuptools earlier than 28.8.

**Comment by jimfulton** [comment]
Can someone try adding:

    pip install setuptools -U

to one of these travis.yml configs before running buildout and try again?

**Comment by leorochael** [comment]
> Can someone try adding:
> 
>     pip install setuptools -U
> 
> to one of these travis.yml configs before running buildout and try again?

To avoid a [potential world of pain](https://github.com/pypa/setuptools/issues/970), I suggest making that:

    pip install setuptools=33.1.1

**Comment by jimfulton** [comment]
I think you meant:

    pip install setuptools==33.1.1

**Comment by leorochael** [comment]
> I think you meant:
> 
>     pip install setuptools==33.1.1

Yes, and with a `-U` as well. I just updated the original comment.

It's possible that `_by_version_descending()` is not strictly necessary. I've used it only to preserve the sorting of evaluated dists when changing from:

 - `pkg_resources.Environment([eggs_directory])`, which scans eggs inside `egg_directory` automatically

to

- `pkg_resources.Environment(glob.glob(os.path.join(eggs_directory, "*.egg")))`

But I never understood why `Environment` sorted the paths it crawled in each directory that way to begin with, considering that, while classifying each located dist per project_name, it will sort again the different dists of each project according to version. I was just trying to preserve the original behavior as much as possible.

Buildout tests pass anyway if I replace `_by_version_descending()` with either `sorted()` or `list(reversed(sorted()))` or simply `list()` (not that I think buildout tests specifically verify the intrincacies of version sorting, but...).

@jimfulton, should I remove the `_by_version_descending()` call?

**Comment by jimfulton** [comment]
sure

**Comment by jimfulton** [comment]
Thanks

**Comment by hvelarde** [comment]
bootstraping is done using `setuptools=33.1.1` as you can see here:

https://travis-ci.org/collective/collective.newsticker/jobs/208297713#L186

so that's doesn't seem to be the problem.

**Comment by jimfulton** [comment]
@hvelarde adding the pip command we suggested made it work (or at least get past that point):
https://travis-ci.org/jimfulton/collective.newsticker/builds/208357528

Because it was using Python's setuptools, not anything controlled by buildout.

**Comment by mauritsvanrees** [comment]
The new buildout release works. Thanks!

**Comment by jimfulton** [comment]
I was pleasantly surprised the fix was that easy. :)

**Comment by leorochael** [comment]
> I was pleasantly surprised the fix was that easy. :)

I'm still waiting for the other shoe to drop whereby buildout is selecting the wrong version of something in a corner case involving system/virtualenv installed packages where it used to select the right version before, just because the sorting is different...

[As I mentioned before](https://github.com/buildout/buildout/issues/375#issuecomment-284516057) it shouldn't happen because, but it's hard to be completely sure.

If something like that happens, I suggest just we copy the code of `_by_version_descending()`, which will give buildout a direct dependency on `packaging`, or we reimplement it by sorting the paths according the result of `pkg_resources.parse_version()`.

Just leaving the info here in case we  need to revisit this.
