### ISSUE TITLE
Having trouble including package_data with my package

### ISSUE THREAD

**Issue by mtdeguzis** [buildout/buildout#388]
I have a setup.py like:

```
#!/usr/bin/env python
from setuptools import setup, find_packages
import os

setup(
    name='some-package',
    version='0.1',
    package_dir={'': 'src'},
    packages=find_packages('src'),
    include_package_data=True,
)
```

and a MANIFEST.in file like:

```
include env.ini
```

However, the env.ini file is nowhere to be found in buildout/. I am using this as a develop egg right now. I don't see the file in develop-eggs, parts, or src etc... 

Given the old setup tools that has to be pinned, is there any way to make this work? I want to distribute this file with my package. I cannot include my repo here, as it is a private repo, but it is structured like this:
```
opstools/
  module1.py
  module2.py
  __init__.py
  env.ini
.gitignore
README.md
setup.py
MANIFEST.in
```

Files:

* [buildout.cfg](https://gist.github.com/mtdeguzis/a8c22c95f434d5faecc4588c4f824335)

**Comment by enkidulan** [comment]
@mtdeguzis not sure what you meant by `env.ini file is nowhere to be found in buildout`, could you clarify that? But I'm guessing that you just have wrong expectations. Thing is that packages listed in `develop` section are installing in `develop mode` check [answer about difference between packages installed in develop and non-develop mode](https://stackoverflow.com/a/19048754).
In case if you want to install this package in non-develop mode just add path to it to `find-links` option (see docs  at https://pypi.python.org/pypi/zc.buildout/1.6.3):

    [buildout]
    ...
    find-links =
        /some/otherpath
        /some/path/someegg-1.0.0-py2.3.egg

The other thing is that including data into python package distribution is sometimes quite tricky, check out [answer on how to do it](https://stackoverflow.com/a/1857436)

**Comment by enkidulan** [comment]
@mtdeguzis that kind of questions would be better to ask on stackoverflow

**Comment by mdeguzis** [comment]
Thanks, I'll look at those links soon. I've been up and down stackoverflow already. I suspect t it's due to develop use. Problem is, our repo is private,so I'll need to get I ur service  user in GitHub and are an SSH key.

**Comment by mtdeguzis** [comment]
I guess I was expecting my buildout dir to contain env.ini after I ran it against buildout.cfg that checks for setup.py.

**Comment by jimfulton** [comment]
On Mon, May 22, 2017 at 11:07 AM, Michael T. DeGuzis <
notifications@github.com> wrote:

> I have a setup.py like:
>
> #!/usr/bin/env python
> from setuptools import setup, find_packages
> import os
>
> setup(
>     name='some-package',
>     version='0.1',
>     package_dir={'': 'src'},
>     packages=find_packages('src'),
>     include_package_data=True,
> )
>
> and a MANIFEST.in file like:
>
> include env.ini
>
> However, the env.ini file is nowhere to be found in buildout/. I am using
> this as a develop egg right now. I don't see the file in develop-eggs,
> parts, or src etc...
>
Buildout had nothing to do with the MANIFEST.in file.  It sounds like like
you expect Buildout to generate env.ini, but maybe I'm misunderstanding.

Given the old setup tools that has to be pinned, is there any way to make
> this work? I want to distribute this file with my package. I cannot include
> my repo here, as it is a private repo, but it is structured like this:
>
> opstools/
>   module1.py
>   module2.py
>   __init__.py
>   env.ini
> .gitignore
> README.md
> setup.py
>
> Files:
>
>    - buildout.cf
>    <https://gist.github.com/mtdeguzis/a8c22c95f434d5faecc4588c4f824335>
>    -
>
>
MANIFEST.in is used to control what files are included in a distribution
that you generate using setup.py. Doesn't have anything to do with buildout.

I'm 94% sure we don't understand your question.

**Comment by mtdeguzis** [comment]
I have a file env.ini that I wanted to include in the buildout folder that is produced when I run buildout. I understand now that buildout / python that produce a develop egg only makes links and does run setup.py (which imports my modules/functions), but extraneous files are not included. I switch the develop line to use the sources section and my GitHub target (after including SSH keys in my GitHub profile since it's private) and the file was present in the src/ directory of buildout. Just seems that using develop ignores inclusion of things like that, or (which is more likely), I don't understand how to reference files beyond the egg-link

**Comment by jimfulton** [comment]
On Mon, May 22, 2017 at 1:08 PM, Michael T. DeGuzis <
notifications@github.com> wrote:

> I have a file env.ini that I wanted to include in the buildout folder that
> is produced when I run buildout.
>
What do you mean by "produced when I run buildout"? Is it generated by a
recipe?




> I understand now that buildout / python that produce a develop egg only
> makes links and does run setup.py (which imports my modules/functions),
>
You aren't understanding correctly. :) Buildout *does* run setup scripts
using the ``develop`` distutils command.

but extraneous files are not included.
>
Buildout doesn't do anything. It *just* runs the setupscript.

I switch the develop line to use the sources section and my GitHub target
> (after including SSH keys in my GitHub profile since it's private) and the
> file was present in the src/ directory of buildout. Just seems that using
> develop ignores inclusion of things like that, or (which is more likely), I
> don't understand how to reference files beyond the egg-link
>
When you use develop, buildout uses the setuptools/distutils develop
command to run your setup script.  It passes the destination install
directory. The end result is that the source directory specified in
setup.py (usually relative to the directory containing the setup script) is
added to the path.

**Comment by mtdeguzis** [comment]
Not a buildout issue, but maybe I just don't get how to get over the hurdle of egg-link (the "symlink" to the modules/package) when using develop.  When not using develop, this works fine:

```
config = ConfigParser.RawConfigParser()
configfile = 'buildout/src/my_package/env.ini'
```

**Comment by jimfulton** [comment]
On Mon, May 22, 2017 at 1:22 PM, Michael T. DeGuzis <
notifications@github.com> wrote:

> Not a buildout issue, but maybe I just don't get how to get over the
> hurdle of egg-link (the "symlink" to the modules/package) when using
> develop. When not using develop, this works fine:
>
> config = ConfigParser.RawConfigParser()
> configfile = 'buildout/src/my_package/env.ini'
>
> It would help us help you if you took a step back and told us at a higher
level what you were trying to accomplish.

**Comment by mtdeguzis** [comment]
Get to my config file if using develop eggs or not using develop eggs (github in sources, not using develop section).

I worked this out, which handles nicely in my script:

```
# Load config file
config = ConfigParser.RawConfigParser()
# Handle develop egg use and packaged use here
if args.develop:
    logging.warning("Using opstools develop egg")
    configfile = str(os.environ['HOME']) + '/python-opstools/opstools/hdp-env.ini'
else:
    logging.info("Using opstools packaged version")
    configfile = 'buildout/src/opstools/hdp-env.ini'

# Ensure file is loaded
if not config.read(configfile):
    logging.error("Configuration file " + configfile + " could not be loaded!")
    sys.exit("Configuration file load error")
```

This way I can test with develop and roll out a packaged version with a simple flag.

**Comment by enkidulan** [comment]
@mtdeguzis solution for your issue is `__file__` magic method, just put into any `.py` file that is at same level as `hdp-env.ini` folowing:

    CONFIG_FILE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'hdp-env.ini')
    def get_config(configfile=CONFIG_FILE_PATH):
          config = ConfigParser.RawConfigParser()
          if not config.read(configfile):
                logging.error("Configuration file " + configfile + " could not be loaded!")
                sys.exit("Configuration file load error")   # ???: why not to raise an exception
          return config

**Comment by jimfulton** [comment]
Are you trying to simply access a (non-python) file that's in your package?

if so, then the standard way to do that is to access it relative to an importable file.

So:

    import opstools
    import os

    with open(os.path.join(os.path.dirname(opstools.__file__), 'env.ini') as f
        ... do things with the optn file

``optstools.__file__`` is the path of ``optstools.___init__.pyc``.  You need to use ``dirname`` to get the directory and then you can use ``join`` to get the path of ``env.ini``.
