### ISSUE TITLE
Allow users to specify resulting folder name

### ISSUE THREAD

**Issue by mtdeguzis** [buildout/buildout#394]
It would be nice to be able to specify the folder name after  `bin/buildout -c /folder/buildout.cfg` is ran. Right now, I switch git branches in my repo to use develop eggs and push this to buildout-testing, but when I use that folder, I get buildout-testing/buildout/ and the rest of the directories. I'd like to be able to specify the folder, so I can get

```
buildout-testing
  bin
  develop-eggs
  parts
  src
```

**Comment by gotcha** [comment]
I am not sure I understand what you mean.
However, I guess mr.developer extension might help you. 
https://pypi.python.org/pypi/mr.developer

**Comment by mtdeguzis** [comment]
When buildout is done bootstrapping based on the buildout.cfg, it produces a buildout folder, am I wrong and that is mr. developer?

```
[...]
Got psutil 5.2.2.
Getting distribution for 'requests-kerberos'.
zip_safe flag not set; analyzing archive contents...
Got requests-kerberos 0.11.0.
Getting distribution for 'urllib3'.
warning: no previously-included files matching '*' found under directory 'docs/_build'
zip_safe flag not set; analyzing archive contents...
urllib3.packages.six: module references __path__
Got urllib3 1.21.1.
Getting distribution for 'pykerberos<2.0.0,>=1.1.8'.
zip_safe flag not set; analyzing archive contents...
Got pykerberos 1.1.14.
Generated script '/home/user/audit-tools/buildout/bin/nosetests'.
Generated script '/home/user/audit-tools/buildout/bin/nosetests-2.7'.
Generated script '/home/user/audit-tools/buildout/bin/pep8'.
Generated interpreter '/home/user/audit-tools/buildout/bin/python'.
Installing scripts.
Generated script '/home/user/audit-tools/buildout/bin/nosetests'.
Generated script '/home/user/audit-tools/buildout/bin/nosetests-2.7'.
Installing test.
[...]
```

**Comment by gotcha** [comment]
You will need to check how you bootstrap buildout. (No, it is not mr.developer)

**Comment by mtdeguzis** [comment]
I just use the boostrap that is defined in your docs:

**Comment by gotcha** [comment]
If you want help, you will need to be more precise.

**Comment by mtdeguzis** [comment]
I don't know how to be any more clean.. but ok..

```
bin/buildout -c buildout.cfg
```

With a flag, from:
```
Generated script '/home/user/audit-tools/buildout/bin/nosetests'.
Generated script '/home/user/audit-tools/buildout/bin/nosetests-2.7'.
Generated script '/home/user/audit-tools/buildout/bin/pep8'.
Generated interpreter '/home/user/audit-tools/buildout/bin/python'
```

To (say, -name 'buildout-testing')
```
Generated script '/home/user/audit-tools/buildout-testin/bin/nosetests'.
Generated script '/home/user/audit-tools/buildout-testing/bin/nosetests-2.7'.
Generated script '/home/user/audit-tools/buildou-ttesting/bin/pep8'.
Generated interpreter '/home/user/audit-tools/buildout-testing/bin/python'
```

I don't know how to be more clear by describing a resultant folder like the above, and showing you the docs of exactly how I am doing this via bootstrap...

buildout.cfg: https://gist.github.com/mtdeguzis/e2d70c27acf2658746e9ceb9131cd794

**Comment by gotcha** [comment]
This is actually more precise.
How were created the`/home/user/audit-tools` and `/home/user/audit-tools/buildout` directories ?

**Comment by mtdeguzis** [comment]
mkdir -p /home/user/audit-tools

When bin/buidout -c buildout.cfg is ran, it just creates buildout/ inside that directory above. I understand renaming is trivial, but for automated processes, it would be nice to specify the name.

**Comment by jimfulton** [comment]
On Thu, May 25, 2017 at 4:46 PM, Michael T. DeGuzis <
notifications@github.com> wrote:

> It would be nice to be able to specify the folder name after bin/buildout
> -c /folder/buildout.cfg is ran.
>
What folder name?

The buildout directory? By default the buildout directory is the directory
containing the configuration file.

If you want a different buildout directory, you can specify:

  directory=SOME_ABSOLUTE_PATH

on the command line.

**Comment by mtdeguzis** [comment]
That is what I needed. Sorry for bothering.
