### ISSUE TITLE
Add coverage support to zc.buildout.testing

### ISSUE THREAD

**Issue by jamadden** [buildout/buildout#397]
Because zc.buildout.testing encourages running buildout in subprocesses in a temporary directory, there are a few boilerplate steps that have to be taken in order to accurately measure coverage across all the test cases:

1. Export `COVERAGE_PROCESS_START=/path/to/.coveragerc`. It needs to specify `parallel=True`.
2. Normalize `COVERAGE_PROCESS_START` to have an absolute path since we'll be working in a temporary directory.
2. Arrange for the generated `bin/buildout` to invoke `import coverage; coverage.process_startup()` at startup. 
3. Before destroying the temporary directory, copy `.coverage.*` back to the location holding the `.coveragerc`.

zc.buildout.testing provides setup and tear down functions that would be ideal places to do steps 2-4, meaning that for recipes to get coverage (if they use this test pattern) they would only need to write a `.coveragerc` and export the variable. (Or I suppose buildout could look for a .coveragerc in the current directory and automatically export that variable...but users may not always want coverage, so it seems like checking for the presence of this variable is a good way to gate the feature.)

I already have an implementation of these steps in [zc.recipe.cmmi#2](https://github.com/zopefoundation/zc.recipe.cmmi/pull/2/). 

I would be happy to extract them as a PR to move to buildout proper. Is there any interest in seeing this done?

It looks like many of buildout's own tests are also based on this test pattern, so this could facilitate getting coverage reports enabled for buildout too.

**Comment by icemac** [comment]
I'd like to have this feature in buildout as testing with subprocesses is not so easy and there is no need to invent the correct procedure over and over again in the recipes.
