### ISSUE TITLE
Use local tar.gz as "release" source code instead of downloading from Git or using develop eggs?

### ISSUE THREAD

**Issue by mtdeguzis** [buildout/buildout#401]
We have a Docker image that runs buildout on a buildout.cfg setup that typically fetches code over SSH from github (it is a private repo). Since buildout cannot handle prompting the user for username/password like GitHub does, ssh was the only was and has worked well. 

Since the docker build process runs as root, I do not want to add a pub key for root on GitHub of course. Yes, I could use a develop egg, but I want the source locked in place with the code in buildout/src, not the symlink-like nature of a develop egg.

Can a local tar.gz be used as a source instead of relying on a develop egg approach?

**Comment by jimfulton** [comment]
You can use a local source release by naming it in find-links.

Jim

**Comment by mtdeguzis** [comment]
Thank you. Is there more documentation on the structure of buildout.cfg like this? I know the docs have some examples, but maybe more detailed info?
