### ISSUE TITLE
Version pinning is ignored for sections

### ISSUE THREAD

**Issue by dz0ny** [buildout/buildout#403]
For example, if we specify:

```ini
[environment]
recipe = collective.recipe.environment
versions = versions

[versions]
collective.recipe.environment = 0.2.0
```

a version will not be pinned to ```0.2.0``` but instead, the last one in pypa registry will be used.

**Comment by jimfulton** [comment]
Right, this is not a buildout feature (although it has been proposed).

**Comment by leorochael** [comment]
And just to be clear, even though it has been proposed, it will never be a feature of buildout itself, but it can be a feature of a buildout recipe.

(The thing gets muddled by the fact that `zc.recipe.egg` is the recipe that is extended by all other recipes that respect `[versions]`, and it lives in the same repository as buildout, but for anyone wondering where the change to implement this should go, it should go into `zc.recipe.egg`).
