### ISSUE TITLE
zc.recipe.egg 2.0.4 seems to break collective.recipe.omelette

### ISSUE THREAD

**Issue by papachoco** [buildout/buildout#406]
Hello,

After upgrading to 2.0.4 from 2.0.3, the installation of omelette (collective.recipe.omelette 0.16) within buildout breaks w/ the exception below. Rolling back to 2.0.3 fixed the problem

Carlos

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/collective.recipe.omelette-0.16-py2.7.egg/collective/recipe/omelette/__init__.py", line 103, in install
    for line in dist._get_metadata('namespace_packages.txt'):
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 1458, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 1818, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 1698, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 1637, in load
    path = os.path.normpath(path)
  File "/Users/csanchez/VirtualEnvs/nti.dataserver-buildout/bin/../lib/python2.7/posixpath.py", line 335, in normpath

**Comment by papachoco** [comment]
cc @leorochael

**Comment by leorochael** [comment]
@papachoco, can you please provide us with a minimal example of a breaking buildout?

**Comment by rafaelbco** [comment]
I tested and it worked for me. Can be an specific condition. 

Relevant Versions:
zc.recipe.egg = 2.0.4
zc.buildout = 2.9.4
collective.recipe.omelette = 0.16
setuptools = 36.2.0

**Comment by papachoco** [comment]
I am running setuptools  33.1.1  (before six and pyparsing requirements)

**Comment by leorochael** [comment]
@papachoco, what exactly is your buildout configuration? Can you give us a minimal failing example?

Also, your traceback seems incomplete. There isn't even the actual exception that was raised.

**Comment by papachoco** [comment]
I am attaching a small sample that reproduces the problem. 
python bootstrap.py
./bin/buildout -c python.cfg

I am running on a virtual environment whose setuptools is 33.1.1

[example.zip](https://github.com/buildout/buildout/files/1232643/example.zip)

**Comment by rafaelbco** [comment]
Could not reproduce the bug. Here's the shell script I used to run the test:
```
#!/bin/bash
set -x
cd /tmp
rm -rf test_example
mkdir test_example
cd test_example
~/trt3/trt3plone/python_buildout/python-2.7/bin/python -V
~/trt3/trt3plone/python_buildout/python-2.7/bin/virtualenv --version
~/trt3/trt3plone/python_buildout/python-2.7/bin/virtualenv ve
./ve/bin/pip install setuptools==33.1.1
wget --quiet https://github.com/buildout/buildout/files/1232643/example.zip
unzip example.zip
cd example
../ve/bin/python bootstrap.py
bin/buildout -c python.cfg
ls parts/omelette
```

And here's the output:

```
+ cd /tmp
+ rm -rf test_example
+ mkdir test_example
+ cd test_example
+ /home/rafaelbc/trt3/trt3plone/python_buildout/python-2.7/bin/python -V
Python 2.7.12
+ /home/rafaelbc/trt3/trt3plone/python_buildout/python-2.7/bin/virtualenv --version
15.0.2
+ /home/rafaelbc/trt3/trt3plone/python_buildout/python-2.7/bin/virtualenv ve
New python executable in /tmp/test_example/ve/bin/python2.7
Also creating executable in /tmp/test_example/ve/bin/python
Installing setuptools, pip, wheel...done.
+ ./ve/bin/pip install setuptools==33.1.1
Collecting setuptools==33.1.1
  Using cached setuptools-33.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.7
    Uninstalling setuptools-36.2.7:
      Successfully uninstalled setuptools-36.2.7
Successfully installed setuptools-33.1.1
+ wget --quiet https://github.com/buildout/buildout/files/1232643/example.zip
+ unzip example.zip
Archive:  example.zip
   creating: example/
  inflating: example/bootstrap.py    
  inflating: example/buildout.cfg    
  inflating: example/python.cfg      
  inflating: example/recipes.cfg     
  inflating: example/versions.cfg    
+ cd example
+ ../ve/bin/python bootstrap.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Setting socket time out to 3 seconds.
Creating directory '/tmp/test_example/example/bin'.
Creating directory '/tmp/test_example/example/parts'.
Creating directory '/tmp/test_example/example/develop-eggs'.
Generated script '/tmp/test_example/example/bin/buildout'.
+ bin/buildout -c python.cfg
Setting socket time out to 3 seconds.
mr.developer: Creating missing sources dir /tmp/test_example/example/sources.
Installing _mr.developer.
Generated script '/tmp/test_example/example/bin/develop'.
Installing eggs.
Generated script '/tmp/test_example/example/bin/pip'.
Generated script '/tmp/test_example/example/bin/pip3.5'.
Generated script '/tmp/test_example/example/bin/pip3'.
Generated script '/tmp/test_example/example/bin/flake8'.
Generated script '/tmp/test_example/example/bin/pycodestyle'.
Generated script '/tmp/test_example/example/bin/pyflakes'.
Generated interpreter '/tmp/test_example/example/bin/python'.
Installing checkversions.
Generated script '/tmp/test_example/example/bin/checkversions'.
Installing omelette.
+ ls parts/omelette
backports	 elpy  flake8	    mccabe.py  pycodestyle.py
configparser.py  enum  importmagic  pip        pyflakes
```

**Comment by papachoco** [comment]
Hmm this may be an MacOSX problem. I am using python 2.7.13 (macports, /opt/local/Library/Frameworks/Python.framework/Versions/2.7) b/c I can reproduce it easily.

**Comment by jamadden** [comment]
I am also using Python 2.7.13 from MacPorts on OS X. I can the script and *did not* reproduce an error:
```
+ cd /tmp
+ rm -rf test_example
+ mkdir test_example
+ cd test_example
/tmp/test_example
+ python -V
Python 2.7.13
+ virtualenv --version
15.1.0
+ virtualenv ve
New pypy executable in /private/tmp/test_example/ve/bin/pypy
Installing setuptools, pip, wheel...done.
+ ./ve/bin/pip install setuptools==33.1.1
Collecting setuptools==33.1.1
  Downloading setuptools-33.1.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 2.1MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.7
    Uninstalling setuptools-36.2.7:
      Successfully uninstalled setuptools-36.2.7
Successfully installed setuptools-33.1.1
+ wget --quiet https://github.com/buildout/buildout/files/1232643/example.zip
+ unzip example.zip
Archive:  example.zip
   creating: example/
  inflating: example/bootstrap.py
  inflating: example/buildout.cfg
  inflating: example/python.cfg
  inflating: example/recipes.cfg
  inflating: example/versions.cfg
+ cd example
/tmp/test_example/example
+ ../ve/bin/python bootstrap.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Creating directory '/private/tmp/test_example/example/bin'.
Creating directory '/private/tmp/test_example/example/parts'.
Creating directory '/private/tmp/test_example/example/develop-eggs'.
Generated script '/private/tmp/test_example/example/bin/buildout'.
+ bin/buildout -c python.cfg
Getting distribution for 'mr.developer==1.31'.
Got mr.developer 1.31.
mr.developer: Creating missing sources dir /private/tmp/test_example/example/sources.
Getting distribution for 'zc.recipe.egg==2.0.4'.
Got zc.recipe.egg 2.0.4.
Getting distribution for 'collective.recipe.omelette==0.16'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got collective.recipe.omelette 0.16.
Installing _mr.developer.
Generated script '/private/tmp/test_example/example/bin/develop'.
Installing eggs.
Getting distribution for 'elpy==1.16.0'.
zip_safe flag not set; analyzing archive contents...
elpy.pydocutils: module references __path__
Got elpy 1.16.0.
Getting distribution for 'importmagic==0.1.7'.
zip_safe flag not set; analyzing archive contents...
importmagic.conftest: module references __file__
importmagic.symbols: module references __file__
importmagic.symbols: module references __path__
Got importmagic 0.1.7.
Getting distribution for 'flake8==3.4.1'.
zip_safe flag not set; analyzing archive contents...

Installed /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/easy_install-O2ZtiT/flake8-3.4.1/.eggs/pytest_runner-2.11.1-py2.7.egg
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'docs/build/'
zip_safe flag not set; analyzing archive contents...
Got flake8 3.4.1.
Getting distribution for 'enum34==1.1.6'.
zip_safe flag not set; analyzing archive contents...
Got enum34 1.1.6.
Getting distribution for 'configparser==3.5.0'.
Got configparser 3.5.0.
Getting distribution for 'mccabe==0.6.1'.
zip_safe flag not set; analyzing archive contents...

Installed /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/easy_install-dNRhmT/mccabe-0.6.1/.eggs/pytest_runner-2.11.1-py2.7.egg
Got mccabe 0.6.1.
Getting distribution for 'pycodestyle==2.3.1'.
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'testsuite'
warning: no previously-included files matching '*.pyo' found under directory 'testsuite'
no previously-included directories found matching 'docs/_build'
Got pycodestyle 2.3.1.
Getting distribution for 'pyflakes==1.5.0'.
zip_safe flag not set; analyzing archive contents...
pyflakes.checker: module references __file__
pyflakes.checker: module references __path__
pyflakes.test.test_api: module references __file__
pyflakes.test.test_undefined_names: module references __file__
pyflakes.test.test_undefined_names: module references __path__
Got pyflakes 1.5.0.
Generated script '/private/tmp/test_example/example/bin/pip'.
Generated script '/private/tmp/test_example/example/bin/pip3'.
Generated script '/private/tmp/test_example/example/bin/pip3.5'.
Generated script '/private/tmp/test_example/example/bin/flake8'.
Generated script '/private/tmp/test_example/example/bin/pycodestyle'.
Generated script '/private/tmp/test_example/example/bin/pyflakes'.
Generated interpreter '/private/tmp/test_example/example/bin/python'.
Installing checkversions.
Getting distribution for 'z3c.checkversions[buildout]==0.4.2'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
Got z3c.checkversions 0.4.2.
Generated script '/private/tmp/test_example/example/bin/checkversions'.
Installing omelette.
+ ls parts/omelette
backports       configparser.py elpy            enum            flake8          importmagic     mccabe.py       pip             pycodestyle.py  pyflakes
```

**Comment by rafaelbco** [comment]
@papachoco Would you please send the full traceback? As @leorochael said before, the one you sent does not include the exception that was raised.

**Comment by papachoco** [comment]
Sorry guys, I think this was my issue. I recreated my virtualenv and I cannot longer reproduce the problem. Thanks for all the help

**Comment by leorochael** [comment]
@papachoco no problem!

**Comment by papachoco** [comment]
Guys,

I am afraid we are still having the issue .. I am no longer the only one which was having this issue when it comes to installing collective.recipe.omelette. I hope this stack trace helps

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zc/recipe/egg/egg.py", line 229, in install
    relative_paths=self._relative_paths,
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1115, in scripts
    for name in pkg_resources.get_entry_map(dist, 'console_scripts'):
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 566, in get_entry_map
    return get_distribution(dist).get_entry_map(group)
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2639, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in parse_map
    for group, lines in data:
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2967, in split_sections
    for line in yield_lines(s):
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in yield_lines
    for ss in strs:
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1458, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1818, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1698, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1637, in load
    path = os.path.normpath(path)
  File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/bin/../lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jamadden** [comment]
It looks like something is being treated as a zip, but which it really isn't. (I wonder if this could be related to the perennial problem of the name of `zc.recipe.egg`.)

In the lines
```
File "/Users/cutz/VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/pkg_resources/init.py", line 1458, in has_metadata
return self.egg_info and self._has(self._fn(self.egg_info, name))
```

can you get the values of `self.egg_info`, `name`, and the return value of `self.fn()`?

This is only happening with 2.0.4, not 2.0.3, so I'm wondering if something in our internal cache is actually being mutated unexpectedly by the time this part finally gets installed. Can you modify your copy of `zc.recipe.egg` to skip the caching and return a fresh working set every time and see if that solves the problem?

**Comment by jamadden** [comment]
@papachoco and @cutz if you can follow up with the information from the previous comment, I've opened a new issue #415 to track this. It's been seen with different recipes on a different platform too (#414).
