### ISSUE TITLE
Is it possible to have section:option=value in bin/buildout for multiple values?

### ISSUE THREAD

**Issue by idgserpro** [buildout/buildout#409]
http://docs.buildout.org/en/latest/reference.html

> Assignments take the form `section:option=value` and override (or augment) options in configuration files. For example, to pin a version of ZEO you could use `versions:ZEO=4.3.1`. The section defaults to the buildout section. So, for example: parts=test sets the buildout section parts option.

Doing `bin/buildout buildout:eggs+=myegg` works flawlessly, but what if I need more values? Is it supported? Doing `bin/buildout buildout:eggs+=myegg buildout:eggs+=myegg2` for example only the first one is added.

**Comment by leorochael** [comment]
I guess you could do something like [this answer](https://stackoverflow.com/a/38642354/1273938) and literally pass linebreaks as part of one of the parameters.

But considering that buildout goes out of it's way to support line editing in option values, with `-=` being able to match individual lines, I guess your attempt to have multiple `+=` in the command line working would be a nice addition to buildout functionality.

Patches accepted!

**Comment by idgserpro** [comment]
The linebreak worked!

```
bin/buildout 'buildout:eggs+=myegg<Enter>
> myegg2'
```

Is a Contributor's Agreement for zopefoundation needed for PR's in buildout? We're using a corporate account. This linebreak would be a nice addition to the docs, but don't know how it would handle in windows.

Anyways, we don't know if we'll be able to this this PR, this needs to be really well thought to avoid regression bugs.

I think this issue can be closed, any changes in docs or code can be directly addressed in a PR mentioning here.
