### ISSUE TITLE
Using YAML as default configuration file format

### ISSUE THREAD

**Issue by lck** [buildout/buildout#412]
with support for converting buildout files in INI format to YAML format

**Comment by jimfulton** [comment]
Unlikely, sorry.

**Comment by lck** [comment]
Hi Jim, I could work on this but I'm not sure if there is no technical barrier, for example some specific YAML formatting issue, that makes it not possible (or impractical) to convert from INI to YAML format. Thanks

**Comment by jimfulton** [comment]
The technical issue is that the yaml and ini data models are quite different.  Yaml is more or less equivalent to JSON, with values being strings, numbers arrays and mappings, and so on recursively. (The types allowed are probably richer, but I'll assume the same as JSON for the sake of argument.)

INI, OTOH is a mapping from strings to mappings from strings to strings.  There are lots of data structures that can be expressed in YAML that aren't compatible with buildout's option database.

That leaves aside the question of whether YAML would be an improvement in the first place, which is debatable.

**Comment by leorochael** [comment]
I guess I'll just close this for now.
