### ISSUE TITLE
Option "update-versions-file" override conditional "[versions]" section

### ISSUE THREAD

**Issue by Tuoris** [buildout/buildout#413]
Running `./buildout` with following `./buildout.cfg`

```
[buildout]
extends = versions.cfg
show-picked-versions = true
update-versions-file = versions.cfg
parts = geojson

[geojson]
recipe = zc.recipe.egg
eggs = geojson
```
and `./versions.cfg` configuration files

```
[versions]
geojson =

[versions:windows]
geojson = 2.0.0
```
on non-windows systems appends to `[versions:windows]` section this lines

```
# Added by buildout at 2017-08-30 15:52:55.400110
geojson = 2.1.0
...
```
If this version of `./versions.cfg` will be shared then conditional versioning **breaks**.

Shouldn't `_print_picked_versions` function update only specific section of `[version]` section?

**Comment by jimfulton** [comment]
Arguably yes, but the implementation is naive/simple and only appends to the file.  To insert at the correct location would require a far more complex implementation.

**Comment by leorochael** [comment]
As a workaround, I recommend you separate your windows versions in another extends file:

```
[buildout]
extends =
    versions.cfg
    versions-windows.cfg
show-picked-versions = true
update-versions-file = versions.cfg
parts = geojson

(...)
```
