### ISSUE TITLE
What is blessed/official documentation/website?

### ISSUE THREAD

**Issue by soxofaan** [buildout/buildout#418]
Hi,

When one is looking for buildout documentation, http://www.buildout.org/ is the top google hit. 
To be honest, I always feel lost there because there is no consistent overall structure and navigation I can't get my head around.

By accident, at the bottom of the github page, I found http://docs.buildout.org/ , which looks like a lot better and more consistent.

Which one is nowadays the "blessed" documentation for buildout? 
I guess it's the latter, but if that is the case, it should at least be more prominently linked from  http://www.buildout.org/

**Comment by jimfulton** [comment]
Sorry, www.buildout.org *was* pointing to docs, but we use zoneedit and zoneedit is awful and sometimes reverts changes.  I'll fix this, but in the meantime, please use docs.

**Comment by soxofaan** [comment]
@jimfulton http://www.buildout.org/ still looks like the old site
 
<img width="860" alt="screen shot 2017-11-13 at 17 40 51" src="https://user-images.githubusercontent.com/44946/32737256-e59e0c74-c899-11e7-89a8-53e39b8ed103.png">

**Comment by jimfulton** [comment]
Yeah. I thought the issue was with zoneedit, but it has the right information.  I suspect this is a read-the-docs issue.  If anyone who maintains the old site is watching, could you please remove the www definition?

I'll try to run this down this weekend.

**Comment by soxofaan** [comment]
maybe reopen this ticket for higher visibility? (I don't think I can do that)

**Comment by tseaver** [comment]
```bash
$ host www.buildout.org
www.buildout.org is an alias for buildout-docs.readthedocs.org.
buildout-docs.readthedocs.org has address 162.209.114.75
...
```

Looking at the [RTFD project page for buildout](https://readthedocs.org/projects/buildout/), it appears that @hannosch and @aclark4life are the owners.

**Comment by aclark4life** [comment]
@tseaver You want me to add someone as a maintainer here, perhaps? Not sure what else I can do to help …

<img width="1440" alt="screenshot 2017-11-16 13 27 31" src="https://user-images.githubusercontent.com/72164/32908581-edd80482-cad1-11e7-9d92-dc14a010da53.png">

**Comment by tseaver** [comment]
@aclark4life I'd suggest @jimfulton (`j1m` is his RTD handle).

**Comment by aclark4life** [comment]
@tseaver Roger that, done.

<img width="1440" alt="screenshot 2017-11-16 14 10 29" src="https://user-images.githubusercontent.com/72164/32910700-f2fa1d00-cad7-11e7-97fe-d1cc2b58f93d.png">

**Comment by jimfulton** [comment]
Yay! Fixed (modulo cache).

Thanks @aclark4life.

I wonder if we want to advertise the old site under a different name or link to it from the new site,

**Comment by soxofaan** [comment]
confirmed, works for me know. Thanks

**Comment by jimfulton** [comment]
Thanks for nagging us about this!!!
