### ISSUE TITLE
VersionConflict with globally installed packages

### ISSUE THREAD

**Issue by prsephton** [buildout/buildout#423]
The following relates to buildout 2.9.5

If there is a package installed globally, eg. zope.interface 4.1.1  in /usr/lib/python2.7/dist-packages, and buildout tries to install a lower version, eg. zope.interface==3.7.0, then buildout fails with a VersionConflict.  Re-running buildout directly afterwards succeeds, as the 3.7.0 egg is installed before failure.

    File "/home/paul/git/grokproject/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/easy_install.py", line 714, in install
      for dist in self._get_dist(req, ws):
    File "/home/paul/git/grokproject/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/easy_install.py", line 570, in _get_dist
      dist = self._env.best_match(requirement, ws)
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1111, in best_match
    dist = working_set.find(req)
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 715, in find
    raise VersionConflict(dist, req)

Virtualenv does not help in resolving this, even with the --no-site-packages.

Buildout no longer has a -s flag to ignore site-packages.

I would expect buildout to ignore the conflict and continue, in fact not report a conflict at all, as the potential conflict is directly resolved by the action of installing the egg.

**Comment by Cykooz** [comment]
I get this error only when buildout installs extensions and their dependencies. This error does not happen when installing recipes and other packages.

**Comment by Cykooz** [comment]
https://github.com/buildout/buildout/blob/7c52083d029794e0759aff95261d9476756f295e/src/zc/buildout/buildout.py#L1158-L1163

When I deleted line 1160, the error was gone.
