### ISSUE TITLE
Error: Wheels are not supported with setuptools 38.2.0

### ISSUE THREAD

**Issue by mgedmin** [buildout/buildout#425]
Yesterday setuptools 38.2.0 came out with this interesting new feature:

- pypa/setuptools#1200: easy_install now support installing from wheels: they will be installed as standalone unzipped eggs.

Since then all my Jenkins jobs that run `bin/buildout` started failing with the following error

```
Getting distribution for 'zope.testrunner==4.7.0'.
Using unpack_wheel() shim over the deprecated wheel_to_egg() hook.
Please update your wheel extension implementation for one that installs a .whl
handler in zc.buildout.easy_install.UNPACKERS
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zope.testrunner==4.7.0'.
Error: Wheels are not supported
```

Note: I'm not using buildout.wheel, and I've pinned the versions of every dependency and recipe, except for setuptools.

**Comment by reinout** [comment]
I have the same issue on jenkins (also no buildout.wheel). I haven't been able yet to get it to fail locally.

**Comment by reinout** [comment]
Setuptools suddenly unexpectedly downloads a .whl as it now supports that. Buildout sees it and wants to use some wheel-installer. Which isn't there. So it fails with the "Wheels are not supported" error message.

**Comment by reinout** [comment]
I did a quick test by hacking a local copy of buildout and changing this in `easy_install.py`:

    UNPACKERS = {
        '.egg': unpack_egg,
        '.whl': unpack_egg,  # was: unpack_wheel
    }

So now setuptools gets to install the wheel it downloaded in the first place.

**Looks like it works like a charm**. Quick test with numpy works, too.

**Comment by mgedmin** [comment]
To get it to fail locally, run `bin/buildout buildout:eggs-directory=/tmp/new-empty-eggs-dir buildout:download-cache=`.

**Comment by leorochael** [comment]
If we could feature-detect if setuptools supports wheel, we could switch at import time which `unpack_x` function to use for wheels.

**Comment by reinout** [comment]
I think I've found the easiest solution with #428

By default, the `unpack_wheel()` refuses to work, printing "wheels are not supported".
The new default is to let setuptools handle it.
The new default will only fire if a wheel is actually downloaded, which only happens when there's a new setuptools.

So.... ought to work!

**Comment by davisd50** [comment]
pinning the version of setuptools seemed to do the trick for me....buildout.cfg:

[buildout]
... # Other options in the buildout section omitted
versions = versions

[versions]
setuptools = 38.1.0

**Comment by davisd50** [comment]
I might mention, I also had to use the following to above config:

When creating a virtualenv:
  virtualenv --no-setuptools myenv
  . myenv/bin/activate
  pip install setuptools="38.1.0"

My build started working then.
