### ISSUE TITLE
Order of paths in scripts (eg. paster) is arbitrary

### ISSUE THREAD

**Issue by prsephton** [buildout/buildout#429]
There seems to be no consistency to the paths generated by zc.recipe.egg between different machines.  

This is not generally a problem, except for /usr/lib/python2.7/dist-packages; when it arbitrarily appears further up in the list, there is a potential for conflicts with system packages being preferred and detected before buildout eggs. 

Manually editing the bin/paster script and moving the system path to the bottom ignores system packages in favor of buildout eggs.

It is confusing, since a buildout that works perfectly on one machine fails on another for no apparent reason.

**Comment by jamadden** [comment]
This is not a buildout issue. `/usr/whatever/dist-packages` is part of the system installation, and buildout explicitly does not attempt to provide isolation from that. Quoth the docs:

> Buildout no-longer tries to provide full or partial isolation from system Python installations. If you want isolation, use buildout with virtualenv, or use a clean build of Python to begin with.

> Providing isolation was a noble goal, but it's implementation complicated buildout's implementation too much.

**Comment by leorochael** [comment]
Even if Buildout (or, more specifically, `zc.recipe.egg`) does not attempt to isolate itself from system Python packages, it's generally understood that buildout (`zc.recipe.egg`) should place it's own packages before the system.

If this is not happening in a specific situation, it would be nice to have a reproducible case that we could fix.

**Comment by prsephton** [comment]
@leorochael thats precisely what I meant.  I am not after isolation, but rather some consistency.  I don't think the situation is specific.  In my buildout.cfg, I am using the zc.recipe.egg 3 times, and in each instance the order of eggs in the path is different, and the system path is somewhere in the middle.  The application egg is always correctly inserted at the start of the list.

The order also varies dependent on the machine where I am running buildout.

I'm not really conversant with the code, but it seems that the paths are kept in a dict which is then converted to a list using l = list(d.values()).  I don't know if it applies, but the list which would be returned would not be in a deterministic order.  Perhaps its something like that.

**Comment by jimfulton** [comment]
I've been meaning to work on this for some time. :/

There's another issue somewhere that proposes sorting egg paths (regular and link) first.  While not a silver bullet, I think that would avoid a lot of common stumbles.

**Comment by Cykooz** [comment]
I've made sorting of paths and could create pull request if my solution is good enough.

https://github.com/buildout/buildout/compare/master...Cykooz:master

**Comment by leorochael** [comment]
Hi Cykooz, you can always create the PR, even if you're not sure your solution is good enough. It's easier to comment on an actual PR than a potential one.

Worse that can happen is that we comment on it and close it.

(Actually the worse that can happen is if we lack time to actually review and let a PR languish, but we try to avoid that...).

As for your proposed changes, I see you try to sort the paths on the `WorkingSet` after it's been created, it could be a nice solution, but if we could find a way to create the `WorkingSet` already sorted, that'd be better.

In your proposal, the working set is sorted [immediately after calling](https://github.com/Cykooz/buildout/blob/314fb0bee94029cc7163d24060844c1cdfdf1b18/zc.recipe.egg_/src/zc/recipe/egg/egg.py#L163) either `zc.buildout.easy_install.install()` or `zc.buildout.easy_install.working_set()`, depending on whether `offline` is off or on.

In the offline case, `zc.buildout.easy_install.working_set()` will itself [call ``zc.buildout.easy_install.install()` later](https://github.com/Cykooz/buildout/blob/314fb0bee94029cc7163d24060844c1cdfdf1b18/src/zc/buildout/easy_install.py#L1076).

Now if `zc.buildout.easy_install.install()` could do the ordering itself, that would be best.

For that to work, we need to pass the options `develop-eggs-directory` and `eggs-directory` into `zc.buildout.easy_install.install()` (and in the `offline` case pass it thru `zc.buildout.easy_install.working_set()`).

If we do that, it might be easier to just pass the whole of buildout options into `easy_install()` and then we could move the `offline` logic out of `zc.recipe.egg` and into `easy_install()` itself, making it easier to deprecate (or conflate the semantics with `install-from-cache`) later on.

What do you think, @jimfulton?

**Comment by leorochael** [comment]
@prsephton, can you give us a minimal example that demonstrates this? I.e. a minimal buildout.cfg and a set of commands to build it in a specific environment that results in an unexpected path order that could be verified by manually inspecting the generated scritps in the buildout `bin/`

**Comment by prsephton** [comment]
@leorochael I could do so, but this is not reproducible between machines, so whatever I come up with is meaningless.  IOW different machines have different results (which is sort of the core of the problem).  Chances are whatever tests you run will be fine.  This does not however mean that the general public out there are experiencing what you do.

I have a machine at work which works flawlessly, as it does not even include the system Python path at all!

Regards

**Comment by prsephton** [comment]
@leorochael @jimfulton Hi!

I have some interesting info to report, which confirms that my initial understanding of this issue was rather incomplete.   This may indeed have to do with system isolation, which buildout no longer tries to manage (as initially commented by @jamadden.)

Nevertheless, what is described below severely restricts the usefulness of buildout as a method for deployment, as its behaviour is non-deterministic, and depends entirely on a specific system Python state.

I have narrowed things down (at least in my case) to a difference in buildout's behaviour depending on whether or not six is installed as a system package.  Without six installed at system level, I can do:

    paul@paul-vbox ~/workspace/partybuilder $ uname -a
    Linux paul-vbox 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    paul@paul-vbox ~/workspace/partybuilder $ 

Run buildout...
 
    paul@paul-vbox ~/workspace/partybuilder $ bin/buildout
    Develop: '/home/paul/workspace/partybuilder/.'
    Uninstalling test.
    Uninstalling i18n.
    Unused options for buildout: 'sources'.
    Updating app.
    Generated script '/home/paul/workspace/partybuilder/bin/paster'.
    Updating console.
    Generated script '/home/paul/workspace/partybuilder/bin/python-console'.
    Updating daemon.
    Updating paster_ini_debug.
    Updating paster_ini_deploy.
    Installing i18n.
    i18n: setting up i18n tools
    Generated script '/home/paul/workspace/partybuilder/bin/i18nextract'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18nmergeall'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18nstats'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18ncompile'.
    Updating mkdirs.
    Updating site_zcml.
    Installing test.
    Generated script '/home/paul/workspace/partybuilder/bin/test'.
    Updating zope_conf_debug.
    Updating zope_conf_deploy.
    Updating zpasswd.
    Generated script '/home/paul/workspace/partybuilder/bin/zpasswd'.
    Updating interactive_debugger.
    Generated script '/home/paul/workspace/partybuilder/bin/interactive_debugger'.

Copy away working configuration

    paul@paul-vbox ~/workspace/partybuilder $ cp bin/paster p.workin

Test working config

    paul@paul-vbox ~/workspace/partybuilder $ bin/paster serve parts/etc/deploy.ini Starting server in PID 31091.
    serving on http://127.0.0.1:8085
    ^Cpaul@paul-vbox ~/workspace/partybuilder $

So lets install six as a system package:

    paul@paul-vbox ~/workspace/partybuilder $ sudo apt-get install python-six
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following NEW packages will be installed:
      python-six
    0 upgraded, 1 newly installed, 0 to remove and 722 not upgraded.
    Need to get 0 B/10.9 kB of archives.
    After this operation, 54.3 kB of additional disk space will be used.
    Selecting previously unselected package python-six.
    (Reading database ... 207662 files and directories currently installed.)
    Preparing to unpack .../python-six_1.10.0-3_all.deb ...
    Unpacking python-six (1.10.0-3) ...
    Setting up python-six (1.10.0-3) ...
    paul@paul-vbox ~/workspace/partybuilder $ 

So does the config still work?

    paul@paul-vbox ~/workspace/partybuilder $ bin/paster serve parts/etc/deploy.ini Starting server in PID 31193.
    serving on http://127.0.0.1:8085
    ^Cpaul@paul-vbox ~/workspace/partybuilder $

Yes, things work with six installed both at system level and as an egg.  What versions of six are installed as an egg and at system level?

    paul@paul-vbox ~/workspace/partybuilder $ ls -ld /usr/lib/python2.7/dist-packages/six-*  ~/.buildout/eggs/six-*
    drwxr-xr-x 3 paul paul 4096 Sep 10  2016 /home/paul/.buildout/eggs/six-1.10.0-py2.7.egg
    drwxr-xr-x 2 root root 4096 Dec  3 10:04 /usr/lib/python2.7/dist-packages/six-1.10.0.egg-info
    paul@paul-vbox ~/workspace/partybuilder $ 

Exactly the same version at six-1.10.0.

Now lets run buildout again to demonstrate the problem:

    paul@paul-vbox ~/workspace/partybuilder $ bin/buildout
    Develop: '/home/paul/workspace/partybuilder/.'
    Uninstalling test.
    Uninstalling i18n.
    Unused options for buildout: 'sources'.
    Updating app.
    Generated script '/home/paul/workspace/partybuilder/bin/paster'.
    Updating console.
    Generated script '/home/paul/workspace/partybuilder/bin/python-console'.
    Updating daemon.
    Updating paster_ini_debug.
    Updating paster_ini_deploy.
    Installing i18n.
    i18n: setting up i18n tools
    Generated script '/home/paul/workspace/partybuilder/bin/i18nextract'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18nmergeall'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18nstats'.
    Generated script '/home/paul/workspace/partybuilder/bin/i18ncompile'.
    Updating mkdirs.
    Updating site_zcml.
    Installing test.
    Generated script '/home/paul/workspace/partybuilder/bin/test'.
    Updating zope_conf_debug.
    Updating zope_conf_deploy.
    Updating zpasswd.
    Generated script '/home/paul/workspace/partybuilder/bin/zpasswd'.
    Updating interactive_debugger.
    Generated script '/home/paul/workspace/partybuilder/bin/interactive_debugger'.

Now running paster fails.    I include the stack trace below for reference, but I am not expecting an analysis of it.  What is pertinent here, is how an existing install of the exact same version of six at system level can cause this sort of breakage.  Please refer to continuing comments below the stack trace.

    paul@paul-vbox ~/workspace/partybuilder $  bin/paster serve parts/etc/deploy.ini Traceback (most recent call last):
      File "bin/paster", line 115, in <module>
        sys.exit(paste.script.command.run())
      File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
        invoke(command, command_name, options, args[1:])
      File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
        exit_code = runner.run(args)
      File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
        result = self.command()
      File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 284, in command
        relative_to=base, global_conf=vars)
      File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 329, in loadapp
        **kw)
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 203, in loadapp
        return loadobj(APP, uri, name=name, **kw)
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 224, in loadobj
        return context.create()
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 617, in create
        return self.object_type.invoke(self)
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 163, in invoke
        app = context.app_context.create()
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 617, in create
        return self.object_type.invoke(self)
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/loadwsgi.py", line 109, in invoke
        return fix_call(context.object, context.global_conf, **context.local_conf)
      File "/home/paul/.buildout/eggs/PasteDeploy-1.3.4-py2.7.egg/paste/deploy/util/fixtypeerror.py", line 57, in fix_call
        val = callable(*args, **kw)
      File "/home/paul/.buildout/eggs/grokcore.startup-1.2-py2.7.egg/grokcore/startup/startup.py", line 14, in application_factory
        return zope.app.wsgi.getWSGIApplication(zope_conf)
      File "/home/paul/.buildout/eggs/zope.app.wsgi-3.13.0-py2.7.egg/zope/app/wsgi/__init__.py", line 162, in getWSGIApplication
        db = config(configfile, schemafile, features)
      File "/home/paul/.buildout/eggs/zope.app.wsgi-3.13.0-py2.7.egg/zope/app/wsgi/__init__.py", line 150, in config
        appsetup.config(options.site_definition, features=features)
      File "/home/paul/.buildout/eggs/zope.app.appsetup-3.15.0-py2.7.egg/zope/app/appsetup/appsetup.py", line 111, in config
        context = xmlconfig.file(file, context=context, execute=execute)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
        include(context, name, package)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
        self._parser.Parse(data, isFinal)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
        self._parser.Parse(data, isFinal)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
      File "/home/paul/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/paul/.buildout/eggs/z3c.autoinclude-0.3.3-py2.7.egg/z3c/autoinclude/zcml.py", line 51, in includeDependenciesDirective
        info = DependencyFinder(dist).includableInfo(['configure.zcml', 'meta.zcml'])
      File "/home/paul/.buildout/eggs/z3c.autoinclude-0.3.3-py2.7.egg/z3c/autoinclude/dependency.py", line 24, in includableInfo
        module = resolve(dotted_name)
      File "/home/paul/.buildout/eggs/zope.dottedname-3.4.6-py2.7.egg/zope/dottedname/resolve.py", line 32, in resolve
        found = __import__(used)
      File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 39, in <module>
        raise ImportError(_static_binding_error)
    zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/paul/workspace/partybuilder/parts/etc/site.zcml", line 4.2-4.36
        ZopeXMLConfigurationError: File "/home/paul/workspace/partybuilder/src/partybuilder/configure.zcml", line 4.2-4.37
        ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
    paul@paul-vbox ~/workspace/partybuilder $ 

Remember how we saved away a working copy of the paster script that Buildout generated previously? Well, lets compare that one to the script that was generated most recently:

    paul@paul-vbox ~/workspace/partybuilder $ diff p.workin bin/paster
    13c13
    <   '/home/paul/.buildout/eggs/six-1.10.0-py2.7.egg',
    ---
    >   '/usr/lib/python2.7/dist-packages',
    paul@paul-vbox ~/workspace/partybuilder $ 

So, there's just one line different.  Clearly Buildout detected the system installation of six, and simply inserted a path to where six was installed, namely dist-packages.  The flaw in this behaviour is that the system path inserted here precedes any other paths, and any dependencies six may have are satisfied by system eggs which may conflict with those buildout has installed.

If the above logic is correct, then copying the original paster script back should correct the problem.

    paul@paul-vbox ~/workspace/partybuilder $ mv p.workin bin/paster 
    paul@paul-vbox ~/workspace/partybuilder $ bin/paster serve parts/etc/deploy.ini Starting server in PID 31257.
    serving on http://127.0.0.1:8085
    ^Cpaul@paul-vbox ~/workspace/partybuilder $ 

While I realise that the decision was made some time ago for Buildout not to try to do isolation from system eggs, leaving that aspect to virtualenv (which IMHO does not do isolation properly either BTW), this issue could have been solved simply by installing six as an egg and pointing to that in the path instead of the one in the system path.

This would probably have happened if a version of six was specified in buildout.cfg different from the version installed in the system eggs location.   It's not really about isolating buildout from system packages, its about generating a consistent set of scripts from your buildout.cfg where content of those scripts do not depend on system Python installation state.

However, since one cannot predict in advance the state of a users system Python installation, Buildout is not as useful as it might have otherwise been for reliable deployment of Python eggs.

One can hardly specify **"apt-get remove python-six"** as a prerequisite for your own buildout based installation.   Think of how many other Python applications that would break!

**Comment by reinout** [comment]
@prsephton, I wonder if it is a specific problem with six. Or rather, with the two or three external libraries that setuptools depends on. At one time, they were "vendored in", later they were kept as dependencies and later vendored in again.

**Comment by prsephton** [comment]
@reinout Good question.  

It is possible.

However, the problem seems more to do with identical versions for six being installed by buildout and in the system eggs directory (dist-packages).  

In such a case Buildout does not bother with installing the egg as its already installed as a system package.  Builldout also inserts a path to the system package at this point, but this insertion means that _all_ of the installed system packages suddenly take precedence over any subsequent buildout-installed eggs, regardless of version.

The version of six on my work machine, where the failure does not occur, is six v1.8.0.  The buildout version being installed there is 1.11.0.  Buildout does not even look at the dist-packages version, and everything just works quite swimmingly.

Lets see if I can describe things graphically:

![issue-1](https://user-images.githubusercontent.com/1478492/33540883-9c6ec560-d8d5-11e7-896f-dc7793fcca34.png)

Assume the system has Package-a,b and c installed as indicated.   Buildout.cfg is configured to use Package-p and q.  Package-p has Package-b-1.5 as a dependency, and Package-q uses Package-c-2.5.

Buildout (recipe.egg) will produce a path as shown.  Since Package-b-1.5 is already installed, Buildout inserts the system egg path instead of a specific path to Package-b.  When the app is run, Package-c-2.0 is found instead of Package-c-2.5 because it appears earlier in the path.

If Package-b-1.5 is not installed at system level, we have the following scenario instead:


![issue-2](https://user-images.githubusercontent.com/1478492/33541122-93a83b0e-d8d6-11e7-961c-06b0e02258b2.png)
