### ISSUE TITLE
zc.recipe.eggs does not include setuptools nor zc.buildout on scripts in python 3.5 and above

### ISSUE THREAD

**Issue by gforcada** [buildout/buildout#434]
While working on refactoring z3c.dependencychecker I came across the following traceback:

```
Traceback (most recent call last):
  File "bin/code-analysis", line 16, in <module>
    import plone.recipe.codeanalysis
  File "/home/gil/.buildout/eggs/plone.recipe.codeanalysis-2.2-py3.6.egg/plone/recipe/codeanalysis/__init__.py", line 15, in <module>
    import zc.buildout
ModuleNotFoundError: No module named 'zc.buildout'
```

``bin/code-analysis`` is a buildout recipe (plone.recipe.codeanalysis) to run some QA tools on a given source distribution. It works fine and dandy up until 3.4, but somehow, the very same versions of packages fail on 3.5 and 3.6

One can see that clearly in this pull request against plone.recipe.codeanalysis itself: https://travis-ci.org/plone/plone.recipe.codeanalysis/builds/318349388

Python 2.7 and 3.4 do work as expected, but 3.5 and 3.6 fail with that traceback.

One can easily understand why it fails as the ``sys.path[:] = `` does not contain zc.buildout nor setuptools.

**Why?** That's a good question I have no idea how to answer 😞 any hints?

**Comment by mgedmin** [comment]
I've noticed a certain something in Python 3.5 that causes problems for (old setuptools-style) namespace packages.  These problems went away when we started explicitly upgrading old versions of pip/setuptools that CI images (can't remember if Travis or Appveyor) were providing by default.

AFAICT you are installing zc.buildout using pip, and you are using the latest version of pip.  Maybe try pip install -U setuptools?

**Comment by gforcada** [comment]
I do have latest setuptools as well, to reproduce:

```
mkdir /tmp/test_error
cd /tmp/test_error
python3.6 -m venv
. bin/activate
pip install -U pip setuptools zc.buildout
*add buildout.cfg, see below*
buildout
bin/code-analysis <-- this fails with the traceback shown on the first message
```

buildout.cfg
```
[buildout]
parts =
    code-analysis
show-picked-versions = true

[code-analysis]
recipe = plone.recipe.codeanalysis
directory = ${buildout:directory}
```

**Comment by reinout** [comment]
I'm getting something even more creative:

    $ buildout
    Creating directory '/private/tmp/probleem/parts'.
    Creating directory '/private/tmp/probleem/develop-eggs'.
    Getting distribution for 'plone.recipe.codeanalysis'.
    Traceback (most recent call last):
      File "/private/tmp/probleem/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/private/tmp/probleem/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/private/tmp/probleem/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/private/tmp/probleem/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/dl/wpghhqhj2bs9bcnn213f1nqw0000gn/T/easy_install-1dbkrdze/plone.recipe.codeanalysis-2.2/setup.py", line 19, in <module>
      File "/var/folders/dl/wpghhqhj2bs9bcnn213f1nqw0000gn/T/easy_install-1dbkrdze/plone.recipe.codeanalysis-2.2/setup.py", line 12, in read
      File "/usr/local/bin/../Cellar/python3/3.6.3/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)

**Comment by reinout** [comment]
Ah, the error (the cause of the traceback I'm getting) is in the `setup.py` of plone.recipe.codeanalysis. It reads `CONTRIBUTORS.rst` without any encoding stuff. And there's a non-ascii contributor in there.

**Comment by hvelarde** [comment]
I'm the one to blame ;)

**Comment by gforcada** [comment]
I'm a bit at a loss here, I've been trying to debug it, but I have no clue, so far, of what could be the problem ☹️

Comparing python 2.7 and 3.6 outputs does not really help unfortunately.

**Comment by reinout** [comment]
I wonder if there's some similarity somewhere to #410.

**Comment by gp54321** [comment]
I am not sure if I am beating a dead horse there are sooo many issues with this namespace loading.
What I have seen while trying out Plone for Python 3: import failure while launching waitress for zc.buildout. Zc.buildout was installed in dist-packages while other parts of the virtual zc package were in the Plone tree (eggs or src). I deleted all the old style namespace linking (__init__py with one or 3 lines) in the zc packages (4 of them). After this and without changing anything else zc.buildout imported fine. My interpretation: Python 3 compatibility for old style namespaces is one-way; when you have started to migrate you have to migrate each and every part of your package to the new-style else you risk strange problems.

**Comment by petschki** [comment]
for me, in python 3.7 the code-analysis problem is gone ... allthough 3.6 still failing ... see https://travis-ci.org/plone/plone.app.blocks/builds/490072439

**Comment by gforcada** [comment]
I hope 🍀 that since then it has being fixed or worked around 🤞🏾
