### ISSUE TITLE
put back is_distribute for backwards-compatibility?

### ISSUE THREAD

**Issue by petri** [buildout/buildout#44]
Currently, at least the buildout-versions extension fails with zc.buildout master because of removed zc.buildout.easy_install.is_distribute that was still there in at least zc.buildout 2.0.0a1, defined thus in easy_install.py:

```
is_distribute = (
    pkg_resources.Requirement.parse('setuptools').key=='distribute')

```

Just reporting this - I don't have sufficient knowledge of packaging and zc.buildout internals to understand what should be considered part of the external API etc. Should is_distribute be put back to zc.buildout or should I file an issue on buildout-versions instead?

**Comment by reinout** [comment]
The buildout-versions functionality has been included in buildout for quite some time, so I'm closing this issue.
