### ISSUE TITLE
Buildout is broken when using allow-hosts setting: index is at pypi.org now

### ISSUE THREAD

**Issue by kiorky** [buildout/buildout#448]
Is that related to pypi infra changes but it seems that any buildout config is broken right now

```
Installing 'plone.versioncheck', 'mr.developer'.
We have no distributions for plone.versioncheck that satisfies 'plone.versioncheck==1.6.5'.
Couldn't find index page for 'plone.versioncheck' (maybe misspelled?)
Getting distribution for 'plone.versioncheck==1.6.5'.
Couldn't find index page for 'plone.versioncheck' (maybe misspelled?)
While:
  Installing.
  Loading extensions.
  Getting distribution for 'plone.versioncheck==1.6.5'.
Error: Couldn't find a distribution for 'plone.versioncheck==1.6.5'.
```

**Comment by ale-rt** [comment]
I had this and if I think I fixed it by adding:
```
allow-hosts +=                                                                                                                                                                                                                               
    * 
```

Probably
```
allow-hosts +=                                                                                                                                                                                                                               
    *.pypi.org
    *.pythonhosted.org
```
is enough.

See also this post by @icemac https://blog.gocept.com/2018/04/17/allow-hosts-in-buildout-considered-harmful/

**Comment by ale-rt** [comment]
Oh, and I just noticed this one #447

**Comment by kiorky** [comment]
yep my local fix was similar
```diff
diff --git a/etc/base.cfg b/etc/base.cfg
index a530f60..5d31556 100755
--- a/etc/base.cfg
+++ b/etc/base.cfg
@@ -13,6 +13,9 @@ find-links =
     http://pypi.python.org/simple/ZODB4
 allow-hosts =
      *localhost*
+     *pythonhosted.org*
+     *pypi.org*
+     *pypi.python.org*
      *willowrise.org*
      *plone.org*
      *zope.org*

```

**Comment by reinout** [comment]
I thought briefly about adding some detection for this setting in buildout, so that we can print a warning.
But.... that doesn't help as you need to get a new release to get the warning :-)

So.... Let's hope the two issues and the blog post helps people fix their setting.

**Comment by reinout** [comment]
I've made the title a bit more descriptive.

**Comment by pnicolli** [comment]
@ale-rt I agree with the security issue of the trailing `*`. I used your suggestion with a small fix, I needed to remove the dot preceding `pypi.org`, which led to the following addition to my buildout config.

```
allow-hosts +=                                                                                                                                                                                                                               
    *pypi.org
    *.pythonhosted.org
```

Thanks everyone for posting all the solutions and ideas :)

**Comment by mgedmin** [comment]
A minimal allow-hosts that works is

```
allow-hosts =
    pypi.org
    files.pythonhosted.org
```

Both of these entries are required.

(If you happen to use `zc.buildout` older than 2.11.3, then you also need to have `pypi.python.org` in allow-hosts, or you'll have a bad time.)

**Comment by mgedmin** [comment]
I'm going to close this issue since the default `allow-hosts` setting in zc.buildout allows downloads from the new PyPI, and we already have #447 about zc.buildout not informing users when their custom `allow-hosts` break all PyPI downloads.
