### ISSUE TITLE
Unable to "extend" versions using the arrow syntax

### ISSUE THREAD

**Issue by andrewebdev** [buildout/buildout#449]
I have a use case where in my project where I have a development config that requires a couple of extra packages for use only in development. This is what I then attempted.

    [buildout]
    extends = buildout.cfg
    parts +=
        install-dev
        build-env
        deploy
        provision
        cypress
        edit-vault

    eggs += some-package

    [versions]
    <= base-versions
    some-package = x.x.x

And then my standard `buildout.cfg` would look something like this:

    [buildout]
    ... bunch of stuff ...

    [base-versions]
    ... Lots of pinned versions ...

Unfortunately this does not seem to work. Only `some-package` version is pinned, but it never uses versions extended from `base-versions`.

I suspect that this might be _somewhat_ related to #338

**Comment by reinout** [comment]
Buildout has a setting `versions` (with as default value `versions`) that it takes the versions from.

So if your main `buildout.cfg` has no `[versions]` part (but a `[base-versions]` one) I expect there to be no pinning there.

Your link to #338 might be why extending the versions list doesn't work. But.... there is an easy solution: just name both version parts `[versions]`. Your development versions list will automatically extend the one in your main `buildout.cfg`.

Zope/plone used to have a "KGS" (know good set) buildout with just a `[versions]` part. You could extend that KGS buildout in your own and add your own versions in your own `[versions]` part.

Does that work for you?

**Comment by gotcha** [comment]
Seems a pretty good answer.
