### ISSUE TITLE
UnknownExtra: html5lib 0.9999999 has no such extra feature 'datrie'

### ISSUE THREAD

**Issue by papachoco** [buildout/buildout#457]
Hello,

I am getting the following error while installing eggs

UnknownExtra: html5lib 0.9999999 has no such extra feature 'datrie'

I am using two libraries nti.contentfragments which has in its setpy.py/install_requires
[
'setuptools',
'html5lib[datrie]', # > 1.0.1
...

and google tensorflow which has a hard requirement for 
html5lib = 0.9999999

I am pinning html5lib to 0.9999999 in my version.cfg; however; instead of getting a warning 
(i.e. html5lib 10.9999999 does not provide the extra 'datrie') like when installing a package in pip, I get the exception mentioned above.

Thanks

Carlos

**Comment by reinout** [comment]
Then setuptools (which buildout uses under the hood) is more strict than pip. There's nothing buildout itself can do about that.

Regarding your error: apparently nti.contentfragments really needs that "datrie" extra. According to the comment it needs version 1.0.1, though it doesn't specify it explicitly (which it should have).

Tensorflow explicitly requiring a specific version (0.9999999): that's something that is discouraged strongly when packaging a library. You run into problems like this, that way.

It sounds like you have to do some by-hand hacky modifications to one of the packages...

**Comment by jamadden** [comment]
There are two things that make me think that there is work for buildout to do here.

First, pip gets around this issue. It simply issues a warning:
```console
]$ pip install html5lib[foobar]
Collecting html5lib[foobar]
  html5lib 1.0.1 does not provide the extra 'foobar'
Collecting webencodings (from html5lib[foobar])
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-1.0.1 webencodings-0.5.1
```

As pip is de-facto what we're compared to, I think users will expect that behaviour (I also think that's the most reasonable behaviour). [pip had to do work](https://github.com/pypa/pip/pull/2142) to turn that into a warning. I *suspect* buildout can do the same in `easy_install`.

Second, buildout itself throws an exception and reports this as a bug in itself:
```
Installing eggs.
While:
Installing eggs.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
...
File "//eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 925, in install
return installer.install(specs, working_set)
File "//eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 736, in install
extra_requirements = dist.requires(req.extras)[::-1]
File "//eggs/setuptools-39.2.0-py2.7.egg/pkg_resources/init.py", line 2615, in requires
"%s has no such extra feature %r" % (self, ext)
UnknownExtra: html5lib 0.9999999 has no such extra feature 'datrie'
```

At a minimum, I think buildout should handle this error better by not throwing it to the user and reporting it as a bug.

I can take a look at easy_install.

**Comment by reinout** [comment]
Sounds like a try/except can "fix" it, yes.

What I find weird is that pip treats it as something that's only worth a warning. A requirement is a requirement, so it is something I really need. So if I require a non-existing package in my `setup.py`, pip will stop with an error; but if I require a package's non-existing extras, pip thinks I'm not really serious about my requirement and only emits a short warning.... :-)

Weird. Anyway, pip does it, so I'm fine with doing it too :-)

**Comment by jimfulton** [comment]
On Fri, Jun 29, 2018 at 6:29 AM, Jason Madden <notifications@github.com>
wrote:

> There are two things that make me think that there is work for buildout to
> do here.
>
> First, pip gets around this issue. It simply issues a warning:
>
> ]$ pip install html5lib[foobar]Collecting html5lib[foobar]  html5lib 1.0.1 does not provide the extra 'foobar'Collecting webencodings (from html5lib[foobar])Installing collected packages: webencodings, html5libSuccessfully installed html5lib-1.0.1 webencodings-0.5.1
>
> Pip is aimed at a different audience, who don't care about predictability.

I've been at a company the last year who doesn't use buildout and dealing
with pip fails is a constant source of irritation.  Rebuilding virtualenvs
or hand-editing .pth files is part of my routine. :(


> As pip is de-facto
>
As is the meme that Python packaging is a mess.

> what we're compared to,
>
This is like comparing databases without considering use cases...

> I think users will expect that behaviour (I also think that's the most
> reasonable behaviour). pip had to do work
> <https://github.com/pypa/pip/pull/2142> to turn that into a warning. I
> *suspect* buildout can do the same in easy_install.
>
Second, buildout itself throws an exception and reports this as a bug in
> itself:
>

Yup. Good point.


> Installing eggs.
> While:
> Installing eggs.
>
> An internal error occurred due to a bug in either zc.buildout or in a
> recipe being used:
> Traceback (most recent call last):
> ...
> File "//eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 925, in install
> return installer.install(specs, working_set)
> File "//eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 736, in install
> extra_requirements = dist.requires(req.extras)[::-1]
> File "//eggs/setuptools-39.2.0-py2.7.egg/pkg_resources/init.py", line 2615, in requires
> "%s has no such extra feature %r" % (self, ext)
> UnknownExtra: html5lib 0.9999999 has no such extra feature 'datrie'
>
> At a minimum, I think buildout should handle this error better by not
> throwing it to the user and reporting it as a bug.
>
> I can take a look at easy_install.
>

Agreed. A better way to handle this is to report this as a user error
hinting at the issue, if possible.

I'm very much against swallowing this error with a warning.

I'd be OK with haveing a --force(-abandon-all-hope ;-]) option to to go
ahead.

**Comment by jimfulton** [comment]
On Fri, Jun 29, 2018 at 6:43 AM, Reinout van Rees <notifications@github.com>
wrote:

> Sounds like a try/except can "fix" it, yes.
>
No

> What I find weird is that pip treats it as something that's only worth a
> warning. A requirement is a requirement, so it is something I really need.
> So if I require a non-existing package in my setup.py, pip will stop with
> an error; but if I require a package's non-existing extras, pip thinks I'm
> not really serious about my requirement and only emits a short warning....
> :-)
>
Pip really doesn't care, do u?


> Weird. Anyway, pip does it, so I'm fine with doing it too :-)
>
I'm very much not.

**Comment by reinout** [comment]
I find it weird, too. So it is OK for me for buildout to be sensibly strict about this.

So: instead of the traceback, we should catch it and print it as a proper error and stop execution.

**Comment by jimfulton** [comment]
On Fri, Jun 29, 2018 at 8:29 AM, Reinout van Rees <notifications@github.com>
wrote:

> I find it weird, too. So it is OK for me for buildout to be sensibly
> strict about this.
>
> So: instead of the traceback, we should catch it and print it as a proper
> error and stop execution.
>

Yup. and perhaps a --force option.

**Comment by jamadden** [comment]
We happened to own the one dependency that was using an unknown extra, so we were able to resolve the situation quickly, so I don't have a dog in this fight anymore (for the moment). 

FWIW, [pipenv](https://docs.pipenv.org) plays in the same "repeatable installation" space as buildout, and it doesn't even warn about unknown extras, as far as I can see.

Most package maintainers are not going to test with buildout, they'll test with pip and related tools. So they'll come to the conclusion that adding and removing extras is no big deal and a minor point release might remove an extra (for any number of reasons: maybe it's obsolete, maybe they decided to make the dependencies "hard", etc). A buildout user won't be able to use that point release. If the dependency chain to get there is long, or is introduced by a new necessary library, resolving the situation can be quite painful and require releases of multiple projects and a lot of time. Or:

> Yup. and perhaps a --force option.

That would solve the problem. I imagine our deployment system would probably be updated to just always add such an argument.

I haven't done anything with buildout's argument parsing/handling before that I recall. That might take me awhile.

**Comment by jimfulton** [comment]
On Fri, Jun 29, 2018 at 9:01 AM, Jason Madden <notifications@github.com>
wrote:
...

> FWIW, pipenv <https://docs.pipenv.org> plays in the same "repeatable
> installation" space as buildout, and it doesn't even warn about unknown
> extras, as far as I can see.
>

Why am I not surprised? :)


> Most package maintainers are not going to test with buildout, they'll test
> with pip and related tools. So they'll come to the conclusion that adding
> and removing extras is no big deal and a minor point release might remove
> an extra (for any number of reasons: maybe it's obsolete, maybe they
> decided to make the dependencies "hard", etc). A buildout user won't be
> able to use that point release.
>
Good, because if the extra was needed, the package will likely be broken.



> If the dependency chain to get there is long, or is introduced by a new
> necessary library, resolving the situation can be quite painful and require
> releases of multiple projects and a lot of time. Or:
>
> Yup. and perhaps a --force option.
>
> It works so well when installing linux packages. 0.5 ;-)

> That would solve the problem. I imagine our deployment system would
> probably be updated to just always add such an argument.
>
There's a sucker born everyday. :)  Seriously, there's a lot of bad
software in the world.


> I haven't done anything with buildout's argument parsing/handling before
> that I recall. That might take me awhile.
>
Thanks for volunteering!

**Comment by jamadden** [comment]
The other arguments that get passed to `easy_install.install` come from the buildout configuration (e.g., 'allow-hosts'). It makes sense to me that 'allow-unknown-extras' would also be configured that way. 

Does that make sense?

**Comment by jimfulton** [comment]
On Fri, Jun 29, 2018 at 10:00 AM, Jason Madden <notifications@github.com>
wrote:

> The other arguments that get passed to easy_install.install come from the
> buildout configuration (e.g., 'allow-hosts'). It makes sense to me that
> 'allow-unknown-extras' would also be configured that way.
>
> Does that make sense?
>

Yup.
