### ISSUE TITLE
Is multithreaded download with zc.recipe.egg?

### ISSUE THREAD

**Issue by mnjagadeesh** [buildout/buildout#463]
Curious to know if we multithreaded download with zc.recipe.egg? I have a local index server and downloading about 400 eggs. It is a sequential download now. I am thinking to speed up download process with multithreading.

Thanks

**Comment by reinout** [comment]
I think that will be hard. A download is always followed by an install, so you'd have to make the whole install procedure multithreaded, too.
I think that makes buildout much to complicated (if it is even possible, installing dependencies is by nature a sequential operation).

**Comment by mnjagadeesh** [comment]
@reinout Thank you for quick reply. It helps. Is it possible to download eggs in cache/ folder and use zc.recipe.egg to install them?

**Comment by reinout** [comment]
You can specify a cache for eggs and one for downloads: http://www.buildout.org/en/latest/topics/optimizing.html

Everything in the download cache are just files. So yes, you could place files in there yourself.

**Comment by mnjagadeesh** [comment]
@reinout Thanks much.
