### ISSUE TITLE
Tutorial should mention the config file name

### ISSUE THREAD

**Issue by kaiw** [buildout/buildout#464]
While the tutorial goes through constructing a config file, it doesn't actually tell you what that config file is supposed to be named until you get half way through. The first time `buildout.cfg` is mentioned is when version controlling the file is discussed.

It would be really nice if the filename was mentioned at the top where the minimal configuration was first described.

**Comment by jimfulton** [comment]
Ha!  Good idea!

**Comment by gotcha** [comment]
@kaiw Is 1a55f2a enough ?

**Comment by kaiw** [comment]
Yes, thanks! That would have been super helpful when I was first reading this.
