### ISSUE TITLE
Warnings about deprecated 'U' mode on Python 3.7

### ISSUE THREAD

**Issue by icemac** [buildout/buildout#466]
When installing a package on Python 3.7 using buildout a warning is emitted that the `'U'` mode of the `open` command is deprecated.

I think this warning originates from [zc/buildout/easy_install.py#L1519](https://github.com/buildout/buildout/blob/master/src/zc/buildout/easy_install.py#L1519).

**Comment by icemac** [comment]
The same line of code also causes zopefoundation/Zope#415.

**Comment by reinout** [comment]
2.13.2 ought to have your fix in it :-)
