### ISSUE TITLE
filename length issue

### ISSUE THREAD

**Issue by mnjagadeesh** [buildout/buildout#468]
Hi,

one of the egg has length filename. if absolute path is included then it has more than 256 char length which python does not support. Because of this issue, egg download fails. It is throwing IO error. Any solution to this? OR I have to use custom egg with path maped to drive letter?

We are using windows 2012R2 OS.

Thanks in advance.

**Comment by tomgross** [comment]
This is a Windows problem. See https://docs.microsoft.com/de-ch/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation not a Python or buildout one.
