### ISSUE TITLE
bin/buildout picking eggs from 3.5 rather than 3.6

### ISSUE THREAD

**Issue by sandroden** [buildout/buildout#469]
Hi,

I have a eggs-directory unique in  the system (it has eggs fro all python versions). It has been this why for years now. It happens several times with python3.6 that buildout picks eggs for python 3.5. It happens when it picks *manylynux.*.ovo versions, es.:

```
lxml-4.1.1-cp36-cp36m-manylinux1_x86_64.ovo 
lxml-4.2.1-cp35-cp35m-manylinux1_x86_64.ovo
```

Is it a bug? Can I fix it with some configuration or I need to separate the eggs-directory?

sandro

**Comment by leorochael** [comment]
If you mention `.ovo` packages it means you're using the `buildout.wheel` extension.

These days, buildout (with a recent setuptools) knows how to handle wheels directly without that extension.

Try removing it and see if it helps.

**Comment by gotcha** [comment]
@sandroden Do you still have the issue with recent `zc.buildout`?
