### ISSUE TITLE
How can I print all eggs from all parts and all versions that were used?

### ISSUE THREAD

**Issue by idgserpro** [buildout/buildout#479]
I was using buildout annotate for some pinned versions like it's said in a related issue https://github.com/buildout/buildout/issues/320. 

But I realized that in a [`pylint` part available in my configuration](https://github.com/plonegovbr/brasil.gov.portal/blob/ade3b19dbec4337ce927887267a9c1b26b2e443f/buildout.cfg#L56) that uses `recipe = zc.recipe.egg` with a bunch of dependencies itself (like six, astroid and such) aren't being outputted like I was expecting for a `bin/buildout annotate` command.

Is my assumption incorrect about how `bin/buildout annotate` should work or it is indeed a feasible feature request?

**Comment by mgedmin** [comment]
You can enable `show-picked-versions=true` to see what versions get picked for dependencies that do not have version pins.

(I would not expect `buildout annotate` to tell me about picked versions.)

**Comment by gotcha** [comment]
`buildout annotate` supports introspection of the buildout configuration... not of the resulting artefacts.

**Comment by idgserpro** [comment]
> annotate [sections]
> Display the buildout configuration options, including their values and where they came from. Try it!

> buildout annotate supports introspection of the buildout configuration... not of the resulting artefacts.

I agree. The documentation is explicit. If I add the versions from `show-picked-versions=true` output I'm can pick it and add to my cfg files, or use the [`update-versions-file` option](http://www.buildout.org/en/latest/getting-started.html#pinned-versions) `bin/buildout annotate` to write them for me.

Thank you all for the fast feedback. I'm closing this issue.
