### ISSUE TITLE
SSL-Certificate is not valid for documentation 

### ISSUE THREAD

**Issue by sallner** [buildout/buildout#489]
`docs.buildout.org/en/latest/`
is not reachable via HTTPS as the certificate is only valid for *readthedocs*

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for docs.buildout.org. The certificate is only valid for the following names: *.readthedocs.io, readthedocs.io

Is there an easy way to deploy a Let's Encrypt certificate for these kinds of scenarios? Is the documentation actually hosted at RTD?

**Comment by mgedmin** [comment]
According to https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl, SSL should work once the people in control of the buildout.org domain and readthedocs account do the following two things:

1. change the DNS record so docs.buildout.org is a CNAME for readthedocs.io. (currently it's a CNAME for buildout-docs.readthedocs.io.)
2. re-request a certificate by saving the domain in readthedocs project admin console (Domains -> Edit Domain -> Save)

An updated certificate should appear within an hour of step 2.

**Comment by jayvdb** [comment]
Note the same problem occurs for https://www.buildout.org

**Comment by reinout** [comment]
According to whois, it is registered at https://www.gandi.net/en
Anyone has an idea who registered it?

**Comment by gotcha** [comment]
Works for me today.
