### ISSUE TITLE
Need info

### ISSUE THREAD

**Issue by mnjagadeesh** [buildout/buildout#496]
over period of time eggs folder is increasing in size. Is there any technique to keep its size under control?

Thanks

**Comment by mgedmin** [comment]
You can periodically run `rm -rf eggs`.  (I had to do that in a cron script back when I was maintaining a buildbot for Zope 3.4)

It should be possible to write a script that removes old versions of each package in the eggs directory, leaving just the latest one.

**Comment by gotcha** [comment]
@mnjagadeesh 
One of the use case of buildout is reproducability: in other words, if your buildout is properly tuned, you can just delete your buildout directory, do a fresh checkout, then run buildout again. 

BEWARE: before deleting your buildout directory, make sure you are not storing user/application data somewhere in a file or a subdirectory inside that directory.

I hope this makes sense.

**Comment by mnjagadeesh** [comment]
Deleting eggs folder and rerun build out is good options for now. Thanks for the help
