### ISSUE TITLE
Python 3.9 requires fixes to stay compatible

### ISSUE THREAD

**Issue by ctheune** [buildout/buildout#497]
We include some smoke tests for managing buildouts in our batou test suite and enabling Python 3.9 caused some deprecations/removals to break:

Traceback (most recent call last):
279  File "/home/travis/build/flyingcircusio/batou/lib/python3.9/site-packages/zc/buildout/buildout.py", line 26, in <module>
280    from UserDict import DictMixin
281ModuleNotFoundError: No module named 'UserDict'

This would be more visible if #486 would also be picked up.

**Comment by icemac** [comment]
This was already fixed in #484 which I am going to release now.

**Comment by icemac** [comment]
Just released as https://pypi.org/project/zc.buildout/2.13.3/
