### ISSUE TITLE
3.0a1: IndexError (possible wheel regression)

### ISSUE THREAD

**Issue by jamadden** [buildout/buildout#507]
When installing numpy-1.16.5, instead of getting the pre-compiled wheel, zc.buildout 3.0a1 is installing from source (this may be a regression from before, I think 2.x was getting the binary wheel before). Numpy fails to compile with some random error:
```
      File "numpy/core/setup_common.py", line 251, in check_long_double_representation
        ltype = long_double_representation(pyod("_configtest"))
      File "numpy/core/setup_common.py", line 401, in long_double_representation
        raise ValueError("Could not lock sequences (%s)" % saw)
    ValueError: Could not lock sequences (None)
    ----------------------------------------
ERROR: Command errored out with exit status 1:
```

That then results in an IndexError from zc.buildout:
```
No .dist-info directory after installing //buildout-cache/dist/numpy-1.16.5.zip
While:
  Installing eggs.
  Getting distribution for 'numpy==1.16.5'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "//venv/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2182, in main
    getattr(buildout, command)(args)
  File "//venv/lib/python2.7/site-packages/zc/buildout/buildout.py", line 819, in install
    installed_files = self[part]._call(recipe.install)
  File "//venv/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1608, in _call
    return f()
  File "//venv/lib/python2.7/site-packages/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "//venv/lib/python2.7/site-packages/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "//venv/lib/python2.7/site-packages/zc/recipe/egg/egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "//venv/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 962, in install
    return installer.install(specs, working_set)
  File "//venv/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 735, in install
    for dist in self._get_dist(req, ws):
  File "//venv/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 579, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "//venv/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1866, in _move_to_eggs_dir_and_compile
    [tmp_loc] = call_pip_install(dist.location, tmp_dest)
  File "//venv/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1681, in call_pip_install
    ][0]
IndexError: list index out of range
```

**Comment by gotcha** [comment]
Thanks for testing so quickly. Which OS and Python version ? In case, it gets hard to reproduce.

**Comment by jamadden** [comment]
2.7.18 on macOS.

`pip` installing numpy before running the buildout let it continue (I think, I still haven't been able to get the whole thing to complete successfully, but it's failing on other parts unrelated to this change, I believe).

**Comment by gotcha** [comment]
Can you give more context ?
With the following simple buildout, I have no problem under 2.7.18, MacOS 10.13.6.

    [buildout]
    parts = numpy
    
    [versions]
    numpy = 1.16.5
    
    [numpy]
    recipe = zc.recipe.egg

**Comment by jamadden** [comment]
In verbose mode, I get this:
```
We have the distribution that satisfies 'pyjwt==1.7.1'.
Getting required 'psutil==5.7.0'
We have the distribution that satisfies 'psutil==5.7.0'.
Getting required 'premailer==3.6.2'
We have the distribution that satisfies 'premailer==3.6.2'.
Getting required 'numpy==1.16.5'
We have no distributions for numpy that satisfies 'numpy==1.16.5'.
pip._internal.index.package_finder: Link requires a different Python (2.7.18 not in: u'>=3.5'): https://files.pythonhosted.org/packages/6e/c5/3ab5a53c2c62602c87d4de2ed1acc038ca47b01368aa2c473bc92fe20ff6/numpy-1.17.0rc1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=1b46bbd810519dd3f75c7654346ef8cbc85164e9fbf263e6ab886a7b5414b4be (from https://pypi.org/simple/numpy/) (requires-python:>=3.5)
…
Many lines like that.
Getting distribution for 'numpy==1.16.5'.
Download cache has numpy 1.16.5 at: /Users/jmadden/Projects/buildout-cache/dist/numpy-1.16.5.zip
Running pip install:
"//bin/python" "-c" "import sys; sys.path[0:0] = []; from pip.__main__ import _main; _main()" "install" "--no-deps" "-t" "//buildout-eggs/cp27m/tmpqeTWKY" "-q" "/buildout-cache/dist/numpy-1.16.5.zip"
path=[]
```

So it seems its finding the source file in the local cache. Lets see what happens if I remove that...

**Comment by jamadden** [comment]
Sure enough, without having the cached sdist locally, the binary wheel is downloaded:
```
Getting distribution for 'numpy==1.16.5'.
Fetching numpy 1.16.5 from: https://files.pythonhosted.org/packages/51/67/8907005262f493e356195bcbd61b41988eecf63cb1d97ea2f6e55fe24205/numpy-1.16.5-cp27-cp27m-macosx_10_9_x86_64.whl#sha256=37fdd3bb05caaaacac58015cfa38e38b006ee9cef1eaacdb70bb68c16ac7db1d
Got numpy 1.16.5.
```

**Comment by gotcha** [comment]
I rephrase to ensure I understand. An older buildout version downloaded sdist and it got cached in the download cache. And 3.0 uses that cached distribution rather than getting a proper wheel that is actually available.

This leads to the following questions :
- Should wheels always be preferred ?
- Why does install from source fails for numpy ?

**Comment by jamadden** [comment]
> An older buildout version downloaded sdist and it got cached in the download cache. And 3.0 uses that cached distribution rather than getting a proper wheel that is actually available.

That seems to be what happened, yes. (I haven't run this particular buildout on this particular machine in a long time.)

> Should wheels always be preferred ?

I think so, yes. Regardless of local cache. That's what pip would do (in fact it only stores wheels in its local cache these days, IIRC, which probably side-steps a bunch of tricky issues). 

> Why does install from source fails for numpy ?

Numpy is notoriously hard to build correctly in my experience. Lots of third party libraries and compilers have to be available. I wasn't surprised it failed to build. What did surprise me was the resulting `IndexError`. That seems like it shouldn't happen.

**Comment by mgedmin** [comment]
Hello?  Is nobody paying attention to

> pip._internal.index.package_finder: Link requires a different Python (2.7.18 not in: u'>=3.5'): https://files.pythonhosted.org/packages/6e/c5/3ab5a53c2c62602c87d4de2ed1acc038ca47b01368aa2c473bc92fe20ff6/numpy-1.17.0rc1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=1b46bbd810519dd3f75c7654346ef8cbc85164e9fbf263e6ab886a7b5414b4be (from https://pypi.org/simple/numpy/) (requires-python:>=3.5)

?

I'm not surprised building numpy 1.16.5 on Python 2.7.18 fails, if numpy 1.16.5 requires-python: >= 3.5.

**Comment by jamadden** [comment]
> if numpy 1.16.5 requires-python: >= 3.5.

It [doesn't](https://pypi.org/project/numpy/1.16.5/). numpy 1.16.5 distributes many [binary wheels for Python 2.7](https://pypi.org/project/numpy/1.16.5/#files).

**Comment by gotcha** [comment]
I agree the IndexError should not happen. See #513 

I dug a bit more. If I run the following buildout with 2.13.3, it downloads a wheel: 
`numpy-1.16.5-cp27-cp27m-macosx_10_9_x86_64.whl` (@mgedmin) 

    [buildout]
    parts = numpy
    download-cache = download-cache
    
    [versions]
    numpy = 1.16.5

    [numpy]
    recipe = zc.recipe.egg

@jamadden Your issue seems to have a long history. I tend to close it. Opinion ?

**Comment by jamadden** [comment]
> Your issue seems to have a long history. I tend to close it.

#513 is a good, actionable issue about error handling and `IndexError`, so I'm fine with that superseding this.  

But what about sdist-in-cache-preferred-over-binary-wheel concern that was discovered during investigation of this? Are you suggesting that it's not likely to be a real problem and can be ignored? I…guess, maybe?

**Comment by gotcha** [comment]
If I download the sdist and put it into the download-cache besides the weel, the wheel is preferred.

If I remove the wheel from the download cache, the sdist is used and built properly on my machine by both 2.13 and 3.0.

IOW, I suggest that good error reporting should enable the user to find a fix in a case like yours. If we find it is not the case, let's reopen.

**Comment by gotcha** [comment]
@jamadden Would you mind trying #514 PR on that particular machine ? And telling me if the reporting seems good enough ?

**Comment by jamadden** [comment]
I'm having trouble duplicating the exact issue now, unfortunately. #514 seems like a good step to me.
