### ISSUE TITLE
Hide pip deprecation warning under 2.7

### ISSUE THREAD

**Issue by gotcha** [buildout/buildout#512]

**Comment by mgedmin** [comment]
Why?  2.7 is going away, it's good that the users get advance notice.

**Comment by jamadden** [comment]
Those still using 2.7 are probably well aware that it's a deprecated version. They'd have upgraded already if they could. The warning from pip about that is not helpful.

**Comment by gotcha** [comment]
And it is pretty noisy.

**Comment by mgedmin** [comment]
> And it is pretty noisy.

which provides motivation to upgrade sooner rather than only once things stop working entirely.

**Comment by gotcha** [comment]
When tackling this issue, I'll try to show the warning only once.
