### ISSUE TITLE
Use towncrier

### ISSUE THREAD

**Issue by gotcha** [buildout/buildout#519]
to avoid changelog conflicts when merging PRs

**Comment by jamadden** [comment]
I've just switched to towncrier for gevent. I like it, but it takes [some hooks](https://github.com/gevent/gevent/blob/6e274a5c3d24b893889d97e22408f5d99f75b92b/setup.cfg#L4-L10) to make it play well with zest.releaser. 

It now occurs to me I'm not sure how this package does releases...

**Comment by mgedmin** [comment]
I'm sure zest.releaser would be open to a PR for better towncrier integration out of the box?

**Comment by gotcha** [comment]
@jamadden Do you use zest releaser.towncrier ?

**Comment by gotcha** [comment]
Done in ff7b00c619ab6a95f3c66fec3968893090851dd6
