### ISSUE TITLE
'+=' syntax not working for buildout:extensions when setup in default.cfg

### ISSUE THREAD

**Issue by k-bu** [buildout/buildout#525]
Hi,

when I globally activate extension(s) in the ~/.buildout/default.cfg file like this:
```
[buildout]
extensions=some.extension.a
```

..but also use project specific extension(s) in some buildout.cfg files like this:
```
[buildout]
extensions+=some.extension.b
```

..then only some.extension.b gets loaded. Thus some.extension.a only gets loaded when buildout.cfg files do not contain any buildout:extensions values at all. Tested with zc.buildout 2.8.0 and 2.13.3. Is it a known restriction or maybe just an unknown bug and simple to fix?
Thanks a lot!

Best regards

**Comment by ale-rt** [comment]
Shouldn't it be:
```
[buildout]
extensions +=
    some.extension.b
```
>

**Comment by k-bu** [comment]
Sorry, I fixed the description.. I've tested with "extensions" not with "extension".

**Comment by k-bu** [comment]
PS: Just In case you meant the linebreak, I've also tested it like this right now:

```
[buildout]
extensions+=
    cs.recipe.cleanup
```

Still no success.

**Comment by ale-rt** [comment]
I believe you have to give more informations, the feature seems to work correctly for me:
```
[ale@emily test-extensions]$ cat base.cfg 
[buildout]
extensions =
    mr.developer
parts =
[ale@emily test-extensions]$ cat extends.cfg 
[buildout]
extends =
    base.cfg

extensions +=
    buildout.requirements

dump-requirements-file = requirements.txt
[ale@emily test-extensions]$ ./bin/buildout -c extends.cfg 
Updating _mr.developer.
*********************************************
Overwriting requirements.txt
*********************************************
```
Check what buildout annotate says, e.g.:
```
[ale@emily test-extensions]$ ./bin/buildout -c extends.cfg annotate |grep extensions= -A 1
extensions= mr.developer
buildout.requirements
```

**Comment by k-bu** [comment]
Thank you for the quick investigation!
I see, it indeed works when including other cfg files via extends.
I placed the full path to my default.cfg into the 'extends' of my buildout.cfg and it worked.
Thus the issue title still seems to be right, about the feature not working just with the default.cfg?

**Comment by gotcha** [comment]
I am not able to reproduce - here with `extends:base.cfg` but also works for me with the simple case :

    [build525]$ cat ~/.buildout/default.cfg
    [buildout]
    extensions = buildout.requirements
    dump-requirements-file = requirements.txt
    overwrite-requirements-file = true
    [build525]$ cat base.cfg
    [buildout]
    extensions += mr.developer
    [build525]$ cat buildout.cfg
    [buildout]
    extends = base.cfg
    parts =
    [build525]$ bin/buildout
    Installing _mr.developer.
    Generated script '/Users/gotcha/tmp/build525/bin/develop'.
    *********************************************
    Writing picked versions to requirements.txt
    *********************************************

**Comment by gotcha** [comment]
I added tests in https://github.com/buildout/buildout/tree/fix-525
They all pass on my machine. (I should have tried to reproduce first...)
Let's see if they also pass on CI

**Comment by k-bu** [comment]
Thank you too for the investigation. I just wanted to let you know, that I'm still confused why I also can't reproduce it like that right now.  And why Alessandro also could reproduce it on that day. I guess it's not because of solar storms.
Although I can still reproduce it right now in my buildout setup which is more complex. I'll report back once I find out the difference that seems to break it.

**Comment by k-bu** [comment]
OK, here's an example. You should be able to reproduce it like that:
```
[build525]$ cat ~/.buildout/default.cfg
[buildout]
extensions = buildout.requirements
dump-requirements-file = requirements.txt
overwrite-requirements-file = true
[build525]$ cat base.cfg
[buildout]
newest=false
[build525]$ cat buildout.cfg
[buildout]
extends = base.cfg
extensions += mr.developer
parts =
[build525]$ bin/buildout
```
I guess the point is, that the base.cfg eats up default extensions somehow, when it contains a [buildout] section. It doesn't happen, if it doesn't contain a [buildout] section.

**Comment by k-bu** [comment]
Thanks a lot for fixing this one. I see it went into master, so I guess there's no chance it'll be fixed for Buildout 2.x too?

**Comment by gotcha** [comment]
Running 2.x tests under CI is a nightmare. Reason why I am reluctant to try to backport.
I just cut a new 3.0 release. I think it would be worth testing it. https://pypi.org/project/zc.buildout/3.0.0b1/
