### ISSUE TITLE
Develop distribution: my.package 1.0.dev0 uses namespace packages but the distribution does not require setuptools.

### ISSUE THREAD

**Issue by idgserpro** [buildout/buildout#526]
If a development package uses namespace packages but doesn't depend on setuptools, I get this message:

```
Develop distribution: my.package 1.0.dev0 uses namespace packages but the distribution does not require setuptools.
```

This message is shown here:

https://github.com/buildout/buildout/blob/e3ee34e874c67fef221ae8eaa1569606cbcc0808/src/zc/buildout/easy_install.py#L641-L649

It seems that buildout inserts `setuptools` as a dependency, if it isn't a package dependency in install_requires.

This behavior is inserted in this commit https://github.com/buildout/buildout/commit/2bf8a93abee26587ea1464f5a93ca9f9eccab62a by @jimfulton 

It is a very old commit. Is this still necessary? I simply make a return in top of the `_maybe_add_setuptools` method and everything went well.

Here is an example of a package where this happens: https://github.com/collective/collective.recaptcha

**Comment by gotcha** [comment]
I think (but am not sure) that `setuptools` is still needed for namespace packages under Python 2.7.

**Comment by idgserpro** [comment]
Well, I ignored the `_maybe_add_setuptools` method and run the buildout and everything went well. This with Python 2.7.

I find it strange to have to declare setptools as dependence in the package, if I don't use it. setptools is a dependency on installation time. It already has to be available to be able to install. After that I don't need it anymore. Outside the Zope/Plone world hardly anyone declares setuptools in install_requires. See a discussion of this: https://github.com/jaraco/configparser/issues/39#issuecomment-480269192

**Comment by mgedmin** [comment]
FWIW `pip install` injects setuptools even if you don't ask for them.  I wonder if zc.buildout's recent switch on top of pip rather than easy_install makes the setuptools requirement no longer strictly necessary?

**Comment by gotcha** [comment]
@idgserpro can you try with buildout 3.0.0a2 to see if the issue is gone like @mgedmin suggests ?

**Comment by idgserpro** [comment]
@gotcha I tried with version 3.0.0a2 but got error #515.

**Comment by gotcha** [comment]
@idgserpro The fix for #515 will come soon in a new release. I'll let you know when released.

**Comment by idgserpro** [comment]
@gotcha I escaped error #515 by removing `mr.developer`. Even in version 3.0.0a2 I still receive the message from that issue.

**Comment by idgserpro** [comment]
@gotcha I think I understand now. Packages that use namespace need an `__init__.py` with:

```python
__import__('pkg_resources').declare_namespace(__name__)
```

So they need `pkg_resources` that is, `setuptools`. For example:

https://github.com/collective/collective.cover/blob/master/src/collective/__init__.py#L1

The warning then makes sense. I will close the issue.
