### ISSUE TITLE
Warning on Python 3.8 due to distutils import

### ISSUE THREAD

**Issue by dataflake** [buildout/buildout#529]
Any script built with `buildout` under Python 3.8 (und running the buildout itself as well) will generate a warning under Python 3.8 (tested with 3.8.4):

```
/my_buildout/lib/python3.8/site-packages/setuptools/distutils_patch.py:60: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
```

The warning results from an import in `easy_install.py` at https://github.com/buildout/buildout/blob/cb6620ea91e767ae83648a7c679bb83d1282e077/src/zc/buildout/easy_install.py#L29

**Comment by domdfcoding** [comment]
There are 4 locations in the code where distutils gets imported, and a further three in the tests. 

Setuptools has (or is about to) adopted distutils, and most of distutils functionality should be available through setuptools. I couldn't find a mapping of distutils functions to their setuptools equivalents however, so ¯\_(ツ)_/¯ I wouldn't know where to start.

Another potential issue is that buildout supports `setuptools>=8.0`, so switching to setuptools would require some sort of shim when importing to support older versions.

An interim solution would be to import setuptools early in buildout's initialisation process, perhaps in `__init__.py`. That way setuptools has been loaded by the Python interpreter before distutils gets imported, allowing the patch to be applied.

**Comment by gotcha** [comment]
I tried to reproduce.

- Built a python 3.8 `virtualenv-15.1.0`. Which installed `setuptools-54.1.1 wheel-0.36.2 pip-21.0.1`.
- Then pip installed `zc.buildout==3.0.0b1`.
- And ran `buildout` with the following `buildout.cfg`.

    [buildout]
    parts=checkversions
    
    [checkversions]
    recipe=zc.recipe.egg
    eggs=z3c.checkversions[buildout]

  I got no warnings.

- Ran the generated script and got no warnings either.

Did I misunderstand the issue ? Or did it go away with recent `setuptools` ?

**Comment by dataflake** [comment]
I just retried the same with release versions: zc.buildout 2.13.4 and `setuptools<52` to avoid the current incompatibilities with zc.buildout. The error has indeed gone away. The file mentioned in the traceback, `lib/python3.8/site-packages/setuptools/distutils_patch.py`, doesn't even exist in the installed setuptools version anymore, which in my case was 47.1.0.
