### ISSUE TITLE
buildout organization management

### ISSUE THREAD

**Issue by gotcha** [buildout/buildout#537]
In the context of #444 and https://community.plone.org/t/buildout-project-and-the-plone-foundation/12917, I checked who is currently in charge of the buildout organization.

I found that there are currently three owners: @jimfulton @hannosch and @reinout 

AFAIK, none of them still really uses buildout.

I mentioned this when I contacted @jimfulton. He answered that it might be better to pass the keys to people maintaining the tool. 

More, I would suggest to include some of the users of the tool. 

This issue to check if @icemac and @mgedmin would agree to become owners besides me.

I think it would be nice to also include @mauritsvanrees for the Plone Foundation and @jamadden who relies on buildout for his work around ZODB. @mauritsvanrees and @jamadden, would you be willing to both apply to the buildout organization and to become owner along the people above that would accept.

If you, reader, think of any other dev that might be a useful add to the team, feel free to suggest.

**Comment by jamadden** [comment]
I, and my group, are highly dependent on buildout, so I'd be happy to continue contributing.

**Comment by mauritsvanrees** [comment]
I would like to be a part of this too. I have hardly contributed any code to Buildout, but with Plone I *am* a heavy user since years.

**Comment by mgedmin** [comment]
I can be a backup owner if you still need one, but I only have one app that still uses buildout in production, and it's in deep maintenance mode.

**Comment by icemac** [comment]
My company uses buildout for nearly all projects, so we heavily depend on it. I agree to become an owner.

**Comment by gotcha** [comment]
@jimfulton gave owner role to @jamadden and me.

@icemac, I did the same with you.

@mauritsvanrees I invited you with the same role.

**Comment by gotcha** [comment]
We have a new set of owners.
