### ISSUE TITLE
setuptools 52.0.0 breaks buildout 2.13.3 installs

### ISSUE THREAD

**Issue by icemac** [buildout/buildout#543]
In https://github.com/pypa/setuptools/commit/2885ca26494e6f555fae85f8f9983c2361c93829 `setuptools.command.easy_install.main` was removed.
It seems to be needed for a successful installation using buildout 2.13.3, so CI of various packages breaks, e. g.

* https://gitlab.com/gocept/union.cms/products.orderedbtreefolder/-/jobs/998458181
* https://github.com/zopefoundation/Products.ZCatalog/runs/1801048436

**Comment by icemac** [comment]
It seems that `setuptools` dropped `easy_install` in favor of using `pip`. (See https://github.com/pypa/setuptools/pull/2544)
Installing wheels does not seem to have this problem, so only packages without a wheel (like `zc.recipe.egg`) seem to be affected.

**Comment by icemac** [comment]
Maybe it's time to depreciate `zc.buildout 2.x` and get version 3 final. What is still open to call a next release of version 3 a final one?

**Comment by icemac** [comment]
cc @gotcha

**Comment by jugmac00** [comment]
> Maybe it's time to deprecate `zc.buildout 2.x` and get version 3 final. What is still open to call a next release of version 3 a final one?

Given the dropped support of `easy_install`, pushing a version 3 release is the only way forward - imho.

**Comment by jugmac00** [comment]
Fixed by #549

**Comment by icemac** [comment]
Hm, should we create a new release now or is there something else to do on the `2.x` branch?

**Comment by jugmac00** [comment]
> Hm, should we create a new release now or is there something else to do on the `2.x` branch?

Yes, please! see #551
