### ISSUE TITLE
bootstrap process is broken for Python 2.7

### ISSUE THREAD

**Issue by jugmac00** [buildout/buildout#546]
The problem seems to be that when you download https://bootstrap.pypa.io/get-pip.py and run `python2.7 get-pip.py`, this results in

```
python ~/Downloads/get-pip.py 
Traceback (most recent call last):
  File "/home/jugmac00/Downloads/get-pip.py", line 24244, in <module>
    main()
  File "/home/jugmac00/Downloads/get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/jugmac00/Downloads/get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpApPNaE/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

_Originally posted by @jugmac00 in https://github.com/buildout/buildout/issues/545#issuecomment-780755469_

**Comment by jugmac00** [comment]
So, when you currently use `get-pip.py` you get a file with the following comment at the top

> This is a base85 encoding of a zip file, this zip file contains an entire copy of pip (version 21.0.1).

pip 21 dropped Python 2 support.

The problem is in `dev.py` 

```
if subprocess.call([sys.executable, get_pip]):
```

This needs an additional argument `"pip < 21.0"`, at least for Python 2.7, see
https://github.com/pypa/get-pip#usage

I'll create another PR tomorrow to fix this unrelated problem.

**Comment by mgedmin** [comment]
I think people who still use 2.7 are supposed to use `https://bootstrap.pypa.io/2.7/get-pip.py`.

I see a subdirectory for every EOLd Python version at https://bootstrap.pypa.io/, and I suspect similar problems exist for e.g. Python 3.5.

I wonder if it might be a good idea to try urlopen('https://bootstrap.pypa.io/%d.%d' % sys.version_info[:2]) and fall back to the top-level get-pip.py if the first request returns a 404.

**Comment by wesleybl** [comment]
Maybe an install_requires based on python version:

**Comment by wesleybl** [comment]
> Maybe an install_requires based on python version

Ops. virtualenv already installs pip <21 if you're using Python 2. So I don't think that's necessary.
