### ISSUE TITLE
create development roadmap and clean up stale branches

### ISSUE THREAD

**Issue by jugmac00** [buildout/buildout#548]
As a drive-by contributor, I had no chance to figure out on my own where I should contribute code changes to.

There is neither a little paragraph in the developers.txt which describes the current two development lines (master + 2.x), nor does it help the occasional contributor that there are almost 30 branches in this repo.

Also, the last release of version 3 alpha was almost a year ago. What is the status? Should we try to promote the alpha release e.g. to the Plone community, so we get more feedback about possible edge cases?

It would be awesome to have a clear guideline where the development here is headed to.

Also, @icemac suggested that there should be a CONTRIBUTING.md in https://community.plone.org/t/buildout-project-and-the-plone-foundation/12917/6 - would be an awesome idea!

**Comment by gotcha** [comment]
PR welcome for both expanding `developers.txt` and a `CONTRIBUTING.md`.

I have cut a new 3.0 release. https://pypi.org/project/zc.buildout/3.0.0b1/

I do think that it is very usable. And yes the Plone community could be helpful in testing it.
