### ISSUE TITLE
buildout 3.x: requirements with extras fail with version constraints

### ISSUE THREAD

**Issue by fschulze** [buildout/buildout#550]
This cfg fails to install with zc.buildout 3.x but works with 2.x:

```
[buildout]
parts = checkversions

[checkversions]
recipe = zc.recipe.egg
eggs = z3c.checkversions [buildout]
```

I think [``_constrained_requirement``](https://github.com/buildout/buildout/blob/master/src/zc/buildout/easy_install.py#L1620) needs to remove the extra part before calling ``pkg_resources.Requirement.parse``.
Currently the ``requirement`` passed in is ``Requirement.parse('zc.buildout; extra == "buildout"')`` with no ``specs`` and then it just bolts on the constraint ``>=3.0.0a2`` which results in the string ``'zc.buildout; extra == "buildout" >=3.0.0a2'`` to be passed to ``pkg_resources.Requirement.parse``.

Looking a bit further, this might work as a fix: ``pkg_resources.Requirement.parse(requirement.name + ' ' + constraint)``, but I'm not sure if ``requirement`` is always a ``Requirement`` object.

Besides this issue I can report that a fairly complex buildout config works just fine with buildout 3.x. It has custom buildout extensions and lots of other non standard things going on.

**Comment by fschulze** [comment]
Fix confirmed. The buildout works with current git checkout.

**Comment by gotcha** [comment]
Released in https://pypi.org/project/zc.buildout/3.0.0b1/
