### ISSUE TITLE
new 2.13 release

### ISSUE THREAD

**Issue by jugmac00** [buildout/buildout#551]
After fixing #549 a new release would be very welcome.

For the upcoming tox4 release in May 2021, I am currently running tox on all Zope and Plone repositories ( https://github.com/zopefoundation/meta/issues/66 ).

One of the reasons for a failure on tox4 is, that tox4 will do isolated builds by default, which basically means, it uses virtualenv and thus a too new setuptools version will be pulled in, leading to a broken tox run.

This could be fixed in each of the affected repos, or much more preferable by using the to be released zc.buildout 2.13 version.

**Comment by icemac** [comment]
Starting to cut a release now.

**Comment by icemac** [comment]
See #552 which tries to fix the tests on GHA.

**Comment by jugmac00** [comment]
Hi @icemac 

I am sorry you have so much trouble to cut a release.

I thought you just need to build and upload a new package.

My - not very relevant take on this - get this release out, so we do not have breakages all over the ecosystem because of the missing upper restriction of the `setuptools` version, and then put all focus on the `buildout` version 3 development.

**Comment by gotcha** [comment]
Repeating what I wrote on #552 
 
Is it absolutely needed to have passing CI for a new 2.13 release ? IIRC, fixing `dev.py` for master took me a lot of time last spring. A middle ground could be to cut a 2.13.4b1 beta release before a final 2.13.4. This way, people could test the new `setuptools` pinning without breaking all setups.

BTW, I have just cut a new release for 3.0: https://pypi.org/project/zc.buildout/3.0.0b1/ We could encourage people to test 3.0.0b1 at the same time. We might realize there is no need for 2.13 anymore.

**Comment by icemac** [comment]
@gotcha Thank you for working on `buildout 3`!

Meanwhile I just released https://pypi.org/project/zc.buildout/2.13.4/.
