### ISSUE TITLE
pip 21.1 breaks buildout 3.x

### ISSUE THREAD

**Issue by fschulze** [buildout/buildout#567]
The current ``_pip_install_cmd = 'from pip.__main__ import _main; _main()'`` breaks with pip 21.1.
Can this just be changed to ``'-m', 'pip'`` in ``call_pip_install`` instead? Should be more future proof.

**Comment by gotcha** [comment]
I do not fully understand the reason for (and the consequences of) fiddling with the path in 
`import sys; sys.path[0:0] = %r; ' % path`.

Reason why I am uneasy to go directly to `'-m', 'pip'`.

I plan to :
1) fix the imports to keep the current way working in a new release
2) explore the simple `'-m', 'pip'` later

**Comment by icemac** [comment]
@gotcha I think this is solved in b3, right?

**Comment by gotcha** [comment]
@icemac Yup, forgot to close, thx
