### ISSUE TITLE
Explore simplifying pip integration

### ISSUE THREAD

**Issue by gotcha** [buildout/buildout#569]
See #567 

Using `python -m pip` would make for a more robust integration.

Nevertheless, current code fiddles with `sys.path`. It needs to be checked if this is still needed.

**Comment by goschtl** [comment]
Hey gotcha,

any news on this.?

Christian

**Comment by gotcha** [comment]
@goschtl I did not tackle this until now.

**Comment by gotcha** [comment]
Fixed in #596
