### ISSUE TITLE
Homepage link on pypi.org is broken

### ISSUE THREAD

**Issue by odelaere** [buildout/buildout#583]
Hello,
The homepage link on pypi links to [http://buildout.org](http://buildout.org).
Which is unreachable
![Screenshot from 2021-10-15 10-10-37](https://user-images.githubusercontent.com/23073839/137454353-fab0ed17-2634-4aa0-878f-9bea1eb13058.png)

**Comment by dataflake** [comment]
The configuration on our own server is now in place and as soon as the DNS changes have propagated you will get redirected to www.buildout.org. I noticed another breakage in the RTD config: Even though my redirects use HTTPS, RTD redirects internally to HTTP again. Can't fix that myself.
