### ISSUE TITLE
ERROR: Package 'collective-jsonmigrator' requires a different Python: 3.8.10 not in '==2.7,>=3.7'

### ISSUE THREAD

**Issue by gbastien** [buildout/buildout#608]
Hi @gotcha 

here is an error I get when using zc.buildout 3.0.0rc3 while trying to install collective.jsonmigrator

So the problem is either in https://github.com/collective/collective.jsonmigrator/blob/master/setup.py where ``python_requires="==2.7, >=3.7"`` or in the way it is managed by zc.buildout?

Another thing is that the error message appears when asking for a fixed version, but if you do not pin a version, you have following message:
```
Getting distribution for 'transmogrify.dexterity==2.0.0'.
While:
  Installing instance1.
  Getting distribution for 'transmogrify.dexterity==2.0.0'.
Error: Couldn't find a distribution for 'transmogrify.dexterity==2.0.0'.
```
It would be great to have a message specifying that the version exists but is not python compatible.

See you!
Gauthier

**Comment by mauritsvanrees** [comment]
This python_requires condition is wrong and can never be true. It cannot be installed by any pip version.
