### ISSUE TITLE
Where does `buildout.exe` come from?

### ISSUE THREAD

**Issue by me-kell** [buildout/buildout#611]
Where does `buildout.exe` come from?

What is the origin of this file? Where is the source code? How it is compiled?

**Comment by me-kell** [comment]
Buildout in Windows comes with a `buildout.exe` file.

This file is also referred in https://github.com/buildout/buildout/blob/297aaa0512fd056ebd2a31521e5200e9bed43b28/src/zc/buildout/buildout.py#L1038.

I'd like to know: What is the origin of this file? Where is the source code? How it is compiled?

**Comment by gotcha** [comment]
I do not use Windows.

My guess is that ``buildout.exe`` is the result of the installation by ``pip`` because of the entry point found at https://github.com/buildout/buildout/blob/b5fc31fd63497dc536594ae8e1304f7a7345fd9e/setup.py#L28

**Comment by me-kell** [comment]
From [Setuptools documentation](https://setuptools.pypa.io/en/latest/setuptools.html#automatic-script-creation):
Automatically generate wrapper scripts or Windows (console and GUI) .exe files for any number of “main” functions in your project. (Note: this is not a py2exe replacement; the .exe files rely on the local Python installation.)
