### ISSUE TITLE
distutils-sig has closed

### ISSUE THREAD

**Issue by pradyunsg** [buildout/buildout#612]
Hiya! 👋🏽 

The documentation for this project still lists distutils-sig as a place to reach out at, to ask about buildout. That mailing list has been sunset and, thus, that link should either be removed or updated to a relevant location for buildout. :)

**Comment by gotcha** [comment]
Thanks for pointing this.

Removed in https://github.com/buildout/buildout/commit/b5fc31fd63497dc536594ae8e1304f7a7345fd9e
