### ISSUE TITLE
gh-actions are run twice for PRs

### ISSUE THREAD

**Issue by mauritsvanrees** [buildout/buildout#617]
When you create a PR for the master branch, over 80 gh-actions are run. This contains duplicates.
I tried fixing this along the lines of how it is done in the [`zopefoundation` repos](https://github.com/zopefoundation/meta/issues/145#issuecomment-1127295753) but I got this error:

> The workflow is not valid. `.github/workflows/debian-sys.yml` (Line: 13, Col: 9): Unexpected symbol: '"pull_request"'. Located at position 22 within expression: `github.event_name != "pull_request" || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name`

**Comment by mgedmin** [comment]
IIRC the GHA expression language is very strict and wants string literals to only use single quotes.  This is what the working expression used for zopefoundation packages looks like:
https://github.com/zopefoundation/meta/blob/9c24f7380973de989c5132ec9f28fa71f1397f20/config/c-code/tests.yml.j2#L93
```
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
```

**Comment by mauritsvanrees** [comment]
@mgedmin Thanks, it seems I copied an older version of that line.
I have created PR #619.

**Comment by mauritsvanrees** [comment]
PR was merged.
