### ISSUE TITLE
Bootstrap.py unable to install zc.buildout

### ISSUE THREAD

**Issue by christophercalm** [buildout/buildout#632]
I am taking over an old repository that uses buildout and I'm running into problems with the boostrap.py. This is the output that I am getting when I run `python bootstrap.py`

` python bootstrap.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpdfh3o6hw
Now working in /tmp/tmpdfh3o6hw/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-07jp69pk
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-07jp69pk/setuptools-33.1.1-py3.6.egg
Couldn't find index page for 'zc.buildout' (maybe misspelled?)
Traceback (most recent call last):
  File "bootstrap.py", line 199, in <module>
    ws.require(requirement)
  File "/tmp/bootstrap-07jp69pk/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 963, in require
  File "/tmp/bootstrap-07jp69pk/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'zc.buildout' distribution was not found and is required by the application`

Is this because of a problem with it being an old version? I notice that the link in the bootstrap.py no longer resolves. (http://downloads.buildout.org/

Attached are the configuration files. 
[buildout.cfg.txt](https://github.com/buildout/buildout/files/11837365/buildout.cfg.txt)
[dev.cfg.txt](https://github.com/buildout/buildout/files/11837366/dev.cfg.txt)
[versions.cfg.txt](https://github.com/buildout/buildout/files/11837367/versions.cfg.txt)
[bootstrap.py.txt](https://github.com/buildout/buildout/files/11837368/bootstrap.py.txt)

**Comment by davisagli** [comment]
These day's I'd suggest installing zc.buildout into a virtualenv using pip, rather than using the bootstrap script.

**Comment by gotcha** [comment]
as proposed by @davisagli :
```
$ virtualenv .
$ bin/pip install zc.buildout==3.0.1
```

Good luck

**Comment by idgserpro** [comment]
@christophercalm if you're using a really old installation with python 2, you need to create a python 2 virtualenv.

With [`pipx`](https://pypa.github.io/pipx/), install `virtualenv`. Then, a new virtualenv with your python 2 location (virtualenv has a `-p` parameter to specify specific pythons. Example: `virtualenv . -p <python_location>`), and _then_ run `bin/pip install zc.buildout==3.0.1 && bin/buildout`.

If you do not have a python2 available, you can install the last python 2 released (2.7.18) using [`pyenv`](https://github.com/pyenv/pyenv). Avoid earlier versions (< 2.7.13) or you'll have problems to compile ssl modules.
