### ISSUE TITLE
Variable defined with initial += is undefined and .installed.cfg corrupted

### ISSUE THREAD

**Issue by distributist** [buildout/buildout#641]
A variable which is initially defined with += will end up with the variable undefined, or missing the initial definition. This is most likely to happen in complex buildouts with multiple overrides.

Such a case will corrupt .installed.cfg by adding an unparsable line "var + = base0" to the end of the offending part:
```
[base1]
__buildout_installed__ = 
__buildout_signature__ = wheel-339de3cbbb8d2a18c6d8133fb43aa777 zc.buildout-1a1dfc3477a86238088ba01adcf15436 pip-339de3cbbb8d2a18c6d8133fb43aa777 setuptools-339de3cbbb8d2a18c6d8133fb43aa777
recipe = zc.buildout:debug
var + = base0
```

**Comment by mauritsvanrees** [comment]
The fix is in release [3.1.1](https://pypi.org/project/zc.buildout/3.1.1/).
