### ISSUE TITLE
ImportError: cannot import name 'packaging' from 'pkg_resources' with setuptools 70

### ISSUE THREAD

**Issue by specialunderwear** [buildout/buildout#648]
With setuptools 70 buildout will have an importerror in easy_install like this:

```
Traceback (most recent call last):
  File "/bin/buildout", line 5, in <module>
    from zc.buildout.buildout import main
  File "/lib/python3.10/site-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 28, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/lib/python3.10/site-packages/pkg_resources/__init__.py)
```

**Comment by icemac** [comment]
@specialunderwear Thank you for this bugreport. For now please pin `setuptools` to a version smaller than `70` until this issue is fixed.

**Comment by perrinjerome** [comment]
Note that the whole `pkg_resources` API (that buildout uses) is deprecated , there's a warning in 
https://github.com/pypa/setuptools/blob/52d732434377dac92df9b50a93eb78fe743b9e24/pkg_resources/__init__.py#L104-L109 referencing https://setuptools.pypa.io/en/latest/pkg_resources.html , so it's possible that more usages becomes broken in the future.

**Comment by mauritsvanrees** [comment]
I have a PR to fix this: https://github.com/buildout/buildout/pull/649

But the tests fail in the same way as they were failing earlier on master.  I tried fixing it, but failed, so help would be appreciated.

**Comment by npilon** [comment]
I think that properly fixing this requires making some headway on the PEP 420 implicit namespace packages issue; I've started to make some headway on that here: https://github.com/npilon/buildout/tree/setuptools-70-prep

But:

- I've got a lot of slightly different doctest output to adjust for, including a couple of warnings I'd like to get rid of.
- The tests that create a new distribution need adjustment.
- I need `zc.recipe.testrunner`, `zc.zdaemonrecipe`, `zc.recipe.deployment` built using implicit namespace packages - I worked around this for some tests by creating a `zc.recipe.testrunner_` local just like `zc.recipe.egg_` but I don't think anyone will be thrilled by that solution.

**Comment by mauritsvanrees** [comment]
@npilon Your commit https://github.com/buildout/buildout/commit/0e06073ebf879a1d95c2dfe970217edcf7e88def to change `easy_install.py` to no longer call `setup.py develop` sounds useful.

But I don't think implicit namespaces have anything to do with this.

**Comment by npilon** [comment]
My thinking was to try to deal with them all at the same time because the namespace packages style uses the same deprecated pkg_resources api, but I’m certainly game to try to bite off smaller chunks.

Why don’t I see if I can get the tests passing with 70.0 and <70.0 using the pip-ified version, then we can discuss further changes?

**Comment by npilon** [comment]
Okay I've got a few more branches on the go now:

- https://github.com/buildout/buildout/compare/master...npilon:buildout:no-more-setup-develop - this just does the `setup.py develop` to `pip install -e` swap.
- https://github.com/buildout/buildout/compare/master...npilon:buildout:pkg-resources-packaging-to-packaging - this is that plus fixes for setuptools 70

Unfortunately this results in a *lot* of new output from setuptools, and trying to convince it to quiet down hits some frustrating-to-handle deprecations and feature removals, as the maintainer of `zstandard` details in this blog post: https://gregoryszorc.com/blog/2023/10/30/my-user-experience-porting-off-setup.py/

- https://github.com/buildout/buildout/compare/master...npilon:buildout:quiet-setuptools - that's the best I could do for quieting those output lines down, but even there there's some tests that are still producing that extra output and I haven't had much luck tracking down how or why. Even then it relies on a deprecated `pip install` option, and using the new option forces setuptools into PEP-517 mode, which means it no longer produces `.egg-link` files.
