### ISSUE TITLE
Multiple +=/-= in one file loses assignment in a previous file

### ISSUE THREAD

**Issue by distributist** [buildout/buildout#656]
If you define an option in one file, then add or subtract from it twice in a subsequent file, the original value is lost, not extended. This happens when you extend the option in the second file, then need to use a conditional section in the same file to extend it further, depending on some condition.

**buildout.cfg**
```
[buildout]
extends =
    b1.cfg
    b2.cfg

parts = check

[check]
recipe = plone.recipe.command
command =
    echo "${test:foo}"
update-command = ${:command}
```
**b1.cfg**
```
[test]
foo =
    abc
    def
```
**b2.cfg**
```
[test]
foo +=
    ghi
    jkl

[test:False]
foo +=
    xzy

[test:True]
foo +=
    mno
```

**Expected:**
```
abc
def
ghi
jkl
mno
```
**Actual:**
```
ghi
jkl
mno
```

I have a patch and will be submitting a pull request shortly

**Comment by mauritsvanrees** [comment]
Your fix is in release [3.1.1](https://pypi.org/project/zc.buildout/3.1.1/).
