### ISSUE TITLE
Update boostrap.py on: http://downloads.buildout.org/2/bootstrap.py

### ISSUE THREAD

**Issue by rvanlaar** [buildout/buildout#86]
Bootstrap.py on github is newer then the one on: http://downloads.buildout.org/2/bootstrap.py

Please upload a new one to buildout.org.

**Comment by idgserpro** [comment]
Since we have bootstrap.py as "stable", wouldn't it just be easier point this url to https://raw.githubusercontent.com/buildout/buildout/master/bootstrap/bootstrap.py?

**Comment by dstufft** [comment]
Just for completeness sake, Jim had asked us to pull the bootstrap.py file from the ``bootstrap-release`` branch. We can of course change that if it's no longer desireable to pull from that branch.

**Comment by tseaver** [comment]
Seems like the fix for this issue is to make a new release (which will update `bootstrap/bootstrap.py` on the 'bootstrap-release' branch, presumably).

**Comment by idgserpro** [comment]
@dstufft  The bootstrap.py from ```bootstrap-release``` is indeed, right now, equal to the one from
http://downloads.buildout.org/2/bootstrap.py (that redirects to https://bootstrap.pypa.io/bootstrap-buildout.py). I don't mind the bootstrap.py being from ```bootstrap-release``` branch. I just wanted to know where exactly it came from to avoid confusion. Thanks for the clarification. If this is true, this issue can be closed, am I correct? Or @rvanlaar is talking about master? Maybe he had the same doubts as me.

Do you think it's worth to explicitly state that the bootstrap.py from pypa comes from this branch, in zc.buildout readme or even bootstrap.py comments itself?

When the branch is updated, will you update the bootstrap.py in http://downloads.buildout.org/2/bootstrap.py? Is this process automated, to avoid issues like this one being opened to each bootstrap.py release? It *can* be automated?

**Comment by dstufft** [comment]
The server backing bootstrap.pypa.io pulls the branches every 15 minutes and if I recall the CDN caches it for an hour. So it may take up to an hour and 15 minutes or so from when it gets merged till it updates.

**Comment by idgserpro** [comment]
This is great to hear @dstufft. Do you think this can be written down in the readme as proposed in [my last comment](https://github.com/buildout/buildout/issues/86#issuecomment-114943615), along with the ```bootstrap-release``` info at the bootstrap.py section? What @tseaver @reinout @jimfulton think about it?

**Comment by reinout** [comment]
A new bootstrap has been released.

I've included the information on how the bootstrap.py ends up on bootstrap.pypa.io in buildout's `DEVELOPERS.rst`.

So... this one can be closed!
